bna: Fix build due to missing use of dma_unmap_len_set()
Patchwork-id: 131257
O-Subject: [RHEL6.8 PATCH 03/46] bna: Fix build due to missing use of dma_unmap_len_set()
Bugzilla: 1258535
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ: #1258535

Upstream commit(s):
commit ecca6a968fc454da641cda7aece35c4e103ad633
Author: David S. Miller <davem@davemloft.net>
Date:   Mon Jan 6 20:37:41 2014 -0500

    bna: Fix build due to missing use of dma_unmap_len_set()

    > as reported for linux-next of Dec.20, 2013
    > when CONFIG_NEED_DMA_MAP_STATE is not enabled:
    >
    > drivers/net/ethernet/brocade/bna/bnad.c: In function 'bnad_start_xmit':
    > drivers/net/ethernet/brocade/bna/bnad.c:3074:26: error: 'struct bnad_tx_vector' has no member named 'dma_len'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>