fix TUN=m VHOST_NET=y
Patchwork-id: 23204
O-Subject: [RHEL6 PATCH 8/8] vhost: fix TUN=m VHOST_NET=y
Bugzilla: 562837
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

BZ#562837
https://bugzilla.redhat.com/show_bug.cgi?id=562837

Description
drivers/built-in.o: In function `get_tun_socket':
    net.c:(.text+0x15436e): undefined reference to `tun_get_socket'

If tun is a module, vhost must be a module, too.
If tun is built-in or disabled, vhost can be built-in.

Note: TUN || !TUN might look a bit strange until you realize
that boolean logic rules do not apply for tristate variables.

Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

Upstream Status of the patches
This is upstream commit 17660f81243e998f36257881ac3ae61685bf91c1

Brew build#: 2247495

Test Status:
This has been tested upstream by Randy Dunlap.
brew build passed

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>