scsi: qla2xxx: Fix issue reported by static checker for qla2x00_els_dcmd2_sp_done()
Message-id: <20190320185115.6802-1-hmadhani@redhat.com>
Patchwork-id: 247141
O-Subject: [RHEL8.1 e-stor PATCH 110/109] scsi: qla2xxx: Fix issue reported by static checker for qla2x00_els_dcmd2_sp_done()
Bugzilla: 1664534
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Quinn Tran <quinn.tran@cavium.com>

Bugzilla 1664534

This patch fixes following Smatch complaint:

drivers/scsi/qla2xxx/qla_iocb.c:2647 qla2x00_els_dcmd2_sp_done()
error: we previously assumed 'e' could be null (see line 2631)

Fixes: 8777e4314d39 ("scsi: qla2xxx: Migrate NVME N2N handling into state machine")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Quinn Tran <quinn.tran@cavium.com>
Signed-off-by: Himanshu Madhani <himanshu.madhani@cavium.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit e9f7be0c4316a0ea1c47b1e800baa58fb937096c)
Signed-off-by: Himanshu Madhani <hmadhani@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>