ALSA: uapi: #include <time.h> in asound.h
Message-id: <15580872947136052-2102-patchset-jkysela@redhat.com>
Patchwork-id: 258566
O-Subject: [RHEL 8.1 PATCH 2101/2119] ALSA: uapi: #include <time.h> in asound.h
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The uapi header asound.h defines types based on struct timespec. We need
to #include <time.h> to get access to the definition of this struct.

Previously, we encountered the following error message when building
applications with a clang/bionic toolchain:

kernel-headers/sound/asound.h:350:19: error: field has incomplete type 'struct timespec'
  struct timespec trigger_tstamp;
                  ^

The absence of the time.h #include statement does not cause build errors
with glibc, because its version of stdlib.h indirectly includes time.h.

Signed-off-by: Daniel Mentz <danielmentz@google.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit b5bdbb6ccd1117896bf4fba6bff75336ca423e8c)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>