APEI build fix
Patchwork-id: 61434
O-Subject: [RHEL6.5 PATCH 08/31] ACPI: APEI build fix
Bugzilla: 816520
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 816520
https://bugzilla.redhat.com/show_bug.cgi?id=816520
Upstream Status: a7e09d450b2e0b068e850d103b6ee1af537d1910

commit a7e09d450b2e0b068e850d103b6ee1af537d1910
Author: Len Brown <len.brown@intel.com>
Date:   Sat Jul 16 18:14:21 2011 -0400

ACPI: APEI build fix

as GHES is optional...

When # CONFIG_ACPI_APEI_GHES is not set:

(.init.text+0x4c22): undefined reference to `ghes_disable'

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Acked-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Len Brown <len.brown@intel.com>