Fix migration.c compilation on s390
Patchwork-id: 30885
O-Subject: [RHEL6.1 PATCH 43/46] Fix migration.c compilation on s390
Bugzilla: 531476
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Bob Picco <bpicco@redhat.com>

Resolves RHBZ 531476

Backport of:

commit 3ef8fd7f720fc4f462fcdcae2fcde6f1c0536bfe
Author: Andi Kleen <ak@linux.intel.com>
Date:   Mon Oct 11 16:03:21 2010 +0200

    Fix migration.c compilation on s390

    31bit s390 doesn't have huge pages and failed with:

    > mm/migrate.c: In function 'remove_migration_pte':
    > mm/migrate.c:143:3: error: implicit declaration of function 'pte_mkhuge'
    > mm/migrate.c:143:7: error: incompatible types when assigning to type 'pte_t' from type 'int'

    Put that code into a ifdef.

    Reported by Heiko Carstens

    Signed-off-by: Andi Kleen <ak@linux.intel.com>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>