ALSA: soundwire: intel: Fix uninitialized adev deref
Message-id: <15580872947136052-2114-patchset-jkysela@redhat.com>
Patchwork-id: 258493
O-Subject: [RHEL 8.1 PATCH 2113/2119] ALSA: soundwire: intel: Fix uninitialized adev deref
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

In case of error, we can dereference uninitialized 'adev'

drivers/soundwire/intel_init.c:154 sdw_intel_acpi_cb()
error: uninitialized symbol 'adev'.

Fix that by not using adev for warn print and make it pr_err.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit e1c815f4b24a305e5bc9eceb541674bf4d02b709)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>