perf data convert: Include config.h header
Message-id: <1477399629-8377-130-git-send-email-jolsa@redhat.com>
Patchwork-id: 159738
O-Subject: [PATCH RHEL7.4 BZ1387909 129/322] perf data convert: Include config.h header
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit f6c12a004c149a7b0ea1332fa715979888dd4695
Author: Jiri Olsa <jolsa@kernel.org>
Date: Fri Jun 24 14:40:24 2016 +0200

description
===========
Otherwise some compiler might scream:

  $ make LIBBABELTRACE_DIR=/opt/libbabeltrace/ LIBBABELTRACE=1
    BUILD:   Doing 'make -j4' parallel build
    CC       util/data-convert-bt.o
  util/data-convert-bt.c: In function convert__config:
  util/data-convert-bt.c:1299:19: error: implicit declaration of function perf_config_u64 [-Werror=implicit-function-declaration]
     c->queue_size = perf_config_u64(var, value);
  ...

Fixes: 41840d211c51 ("perf config: Move config declarations from util/cache.h to util/config.h")
Signed-off-by: Rafael Aquini <aquini@redhat.com>