perf tools: Fix NO_NEWT=1 python build error
Patchwork-id: 36571
O-Subject: [PATCH RHEL6.2 BZ691343 130/142] perf tools: Fix NO_NEWT=1 python build error
Bugzilla: 691343
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 691343
https://bugzilla.redhat.com/show_bug.cgi?id=691343

upstream status
---------------
commit 1b7155f7de119870f0d3fad89f125de2ff6c16be
Author: Robert Richter <robert.richter@amd.com>
Date:   Tue Mar 29 20:02:57 2011 +0200

description
-----------
Fix the following build error:

     GEN python/perf.so
 In file included from util/evsel.h:10,
                  from util/python.c:6:
 util/hist.h:106:18: error: newt.h: No such file or directory
 error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
 make: *** [python/perf.so] Error 1

by passing BASIC_CFLAGS to setup.py. BASIC_CFLAGS variable contains
the -DNO_NEWT_SUPPORT switch which prevents building python c
extension with newt.

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>