rdma: Don't reference kernel private header from UAPI header
Message-id: <1488853076-16738-338-git-send-email-ddutile@redhat.com>
Patchwork-id: 172016
O-Subject: [PATCH RHEL-7.4 337/340] RDMA: Don't reference kernel private header from UAPI header
Bugzilla: 1385326 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385326

commit 646ebd4166ca00bdf682a36bd2e1c9a74d848ac6
Author: Leon Romanovsky <leon@kernel.org>
Date:   Wed Feb 8 17:04:09 2017 +0200

    RDMA: Don't reference kernel private header from UAPI header

    Remove references to private kernel header and defines from exported
    ib_user_verb.h file.

    The code snippet below is used to reproduce the issue:

     #include <stdio.h>
     #include <rdma/ib_user_verb.h>

     int main(void)
     {
    	printf("IB_USER_VERBS_ABI_VERSION = %d\n", IB_USER_VERBS_ABI_VERSION);
    	return 0;
     }

    It fails during compilation phase with an error:
      /tmp gcc main.c
    main.c:2:31: fatal error: rdma/ib_user_verb.h: No such file or directory
     #include <rdma/ib_user_verb.h>
                                   ^
    compilation terminated.

    Fixes: 189aba99e700 ("IB/uverbs: Extend modify_qp and support packet pacing")
    CC: Bodong Wang <bodong@mellanox.com>
    CC: Matan Barak <matanb@mellanox.com>
    CC: Christoph Hellwig <hch@infradead.org>
    Tested-by: Slava Shwartsman <slavash@mellanox.com>
    Signed-off-by: Leon Romanovsky <leon@kernel.org>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>