perf tools: Avoid double free in read_event_file()
Message-id: <c50f8cde12a2096adeb831d2b87406c2a3e0c187.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261521
O-Subject: [RHEL8.1 BZ1709243 140/217] perf tools: Avoid double free in read_event_file()
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit 470c8f7c88de013d266e1b61044efe8937728b7f
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:13 2018 -0400

description
===========
The temporary 'buf' buffer allocated in read_event_file() may be freed
twice.  Move the free() call to the common function exit point.

Fixes the following coverity complaints:

  Error: USE_AFTER_FREE (CWE-825):
  tools/perf/util/trace-event-read.c:309: double_free: Calling "free"
  frees pointer "buf" which has already been freed.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>