btrfs: fix min csum item size warnings in 32bit
Patchwork-id: 52881
O-Subject: [RHEL6.4 PATCH 7/9] btrfs: fix min csum item size warnings in 32bit
Bugzilla: 698324
RH-Acked-by: Eric Sandeen <sandeen@redhat.com>

BZ 698324 - Rebase btrfs

This fixes compiler warnings in btrfs that were introduced before our
backport but which aren't fixed upstream as of this writing.  I've sent
the fix to the upstream list:

 http://marc.info/?l=linux-btrfs&m=134817319014055

btrfs has a habit of rebasing, so this hash in btrfs-next might not mean
much for long, but here it is..

commit cea7c0b16915e1a4aa497d4037179ddc7fc40419
Author: Zach Brown <zab@zabbo.net>
Date:   Thu Sep 20 12:01:35 2012 -0700

    btrfs: fix min csum item size warnings in 32bit

    commit 7ca4be45a0255ac8f08c05491c6add2dd87dd4f8 limited csum items to
    PAGE_CACHE_SIZE.  It used min() with incompatible types in 32bit which
    generates warnings:

    fs/btrfs/file-item.c: In function ‘btrfs_csum_file_blocks’:
    fs/btrfs/file-item.c:717: warning: comparison of distinct pointer types lack

    This uses min_t(u32,) to fix the warnings.  u32 seemed reasonable
    because btrfs_root->leafsize is u32 and PAGE_CACHE_SIZE is unsigned
    long.

    Signed-off-by: Zach Brown <zab@zabbo.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>