vfio-mdev: fix non-standard ioctl return val causing i386 build fail
Message-id: <1484162159-4262-56-git-send-email-tgupta@redhat.com>
Patchwork-id: 162326
O-Subject: [RHEL7.4 55/56] vfio-mdev: fix non-standard ioctl return val causing i386 build fail
Bugzilla: 1116064
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Auger Eric <eric.auger@redhat.com>
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1116064

commit c6ef7fd40eddad38a8825cbd6bb2ce8bdbba88f5
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Wed Jan 4 15:08:15 2017 -0500

    vfio-mdev: fix non-standard ioctl return val causing i386 build fail

    What appears to be a copy and paste error from the line above gets
    the ioctl a ssize_t return value instead of the traditional "int".

    The associated sample code used "long" which meant it would compile
    for x86-64 but not i386, with the latter failing as follows:

      CC [M]  samples/vfio-mdev/mtty.o
    samples/vfio-mdev/mtty.c:1418:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
      .ioctl          = mtty_ioctl,
                        ^
    samples/vfio-mdev/mtty.c:1418:20: note: (near initialization for mdev_fops.ioctl)
    cc1: some warnings being treated as errors

    Since in this case, vfio is working with struct file_operations; as such:

        long (*unlocked_ioctl) (struct file *, unsigned int, unsigned long);
        long (*compat_ioctl) (struct file *, unsigned int, unsigned long);

    ...and so here we just standardize on long vs. the normal int that user
    space typically sees and documents as per "man ioctl" and similar.

    Fixes: 9d1a546c53b4 ("docs: Sample driver to demonstrate how to use Mediated device framework.")
    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Signed-off-by: Alex Williamson <alex.williamson@redhat.com>

Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Auger Eric <eric.auger@redhat.com>
Cc: Paolo Bonzini <pbonzini@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>