perf: Fix compile error on NO_NEWT=1 build
Patchwork-id: 60043
O-Subject: [PATCH RHEL6.5 BZ970529 131/146] perf tools: Fix compile error on NO_NEWT=1 build
Bugzilla: 970529
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Namhyung Kim <namhyung.kim@lge.com>

Bugzilla: 970529
https://bugzilla.redhat.com/show_bug.cgi?id=970529

upstream status
===============
commit 4f746c95f18ad4d85599d9c157da7e6da766c3d9
Author: Namhyung Kim <namhyung.kim@lge.com>
Date:   Mon Nov 12 14:14:00 2012 +0900

description
===========
    CC builtin-annotate.o
In file included from util/evsel.h:10:0,
                 from util/evlist.h:8,
                 from builtin-annotate.c:20:
util/hist.h: In function ‘script_browse’:
util/hist.h:198:45: error: unused parameter ‘script_opt’ [-Werror=unused-parameter]
cc1: all warnings being treated as errors
make: *** [builtin-annotate.o] Error 1
make: *** Waiting for unfinished jobs....