tg3: Fix sparse warnings
Patchwork-id: 60899
O-Subject: [RHEL6.5 PATCH 22/90] tg3: Fix sparse warnings.
Bugzilla: 915516
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: #915516

Upstream commit:
commit 864499449f256e32815575a9b860267ebefa6d70
Author: Michael Chan <mchan@broadcom.com>
Date:   Tue Oct 2 20:31:14 2012 -0700

    tg3: Fix sparse warnings.

    drivers/net/ethernet/broadcom/tg3.c:8121:8: warning: symbol 'i' shadows an earlier one
    drivers/net/ethernet/broadcom/tg3.c:8003:6: originally declared here
    drivers/net/ethernet/broadcom/tg3.c:785:5: warning: symbol 'tg3_ape_scratchpad_read' was not declared. Should it be static?
    drivers/net/ethernet/broadcom/tg3.c:7781:19: warning: Using plain integer as NULL pointer
    drivers/net/ethernet/broadcom/tg3.c:10231:31: error: bad constant expression

    Reported-by: Fengguang Wu <fenguang.wu@intel.com>
    Signed-off-by: Michael Chan <mchan@broadcom.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>