perf: Check libaudit availability for perf-trace builtin
Patchwork-id: 58041
O-Subject: [PATCH RHEL6.5 BZ927866 202/264] perf tools: Check libaudit availability for perf-trace builtin
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Namhyung Kim <namhyung.kim@lge.com>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit 4d29089c2b70ffeb61656ffd1b9c9c52602ddd44
Author: Namhyung Kim <namhyung.kim@lge.com>
Date:   Thu Sep 27 20:23:38 2012 +0900

description
===========
The newly added trace command requires an external audit library.

However it can cause a build error because it's not checked whether the
libaudit is installed on system:

    CC builtin-trace.o
  builtin-trace.c:7:22: fatal error: libaudit.h: No such file or directory
  compilation terminated.
  make: *** [builtin-trace.o] Error 1

[ committer note: Added ", disables 'trace tool' to the feature warning msg ]