genirq: Export handle_bad_irq
Message-id: <1485834706-31516-6-git-send-email-ssuthiku@redhat.com>
Patchwork-id: 164334
O-Subject: [RHEL74 PATCH v4 BZ 1329005 05/28] genirq: Export handle_bad_irq
Bugzilla: 1329005
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1329005

commit 9d67dc5da59d63f746aad8f6ec4fbb86d6486f76
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 6 22:24:50 2015 +0200

    genirq: Export handle_bad_irq

    A cleanup of the omap gpio driver introduced a use of the
    handle_bad_irq() function in a device driver that can be
    a loadable module.

    This broke the ARM allmodconfig build:

    ERROR: "handle_bad_irq" [drivers/gpio/gpio-omap.ko] undefined!

    This patch exports the handle_bad_irq symbol in order to
    allow the use in modules.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Grygorii Strashko <grygorii.strashko@ti.com>
    Cc: Santosh Shilimkar <ssantosh@kernel.org>
    Cc: Linus Walleij <linus.walleij@linaro.org>
    Cc: Austin Schuh <austin@peloton-tech.com>
    Cc: Tony Lindgren <tony@atomide.com>
    Cc: linux-arm-kernel@lists.infradead.org
    Link: http://lkml.kernel.org/r/5847725.4IBopItaOr@wuerfel
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

Cc: Suravee Suthikulpanit <ssuthiku@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>