bench: Fix two warnings
Patchwork-id: 99663
O-Subject: [PATCH RHEL6.7 BZ1159929 232/320] perf bench: Fix two warnings
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 32bf5bd181026fc99c0e15045abe409167285ba8
Author: Wei Yang <weiyang@linux.vnet.ibm.com>
Date: Sun Sep 22 16:49:24 2013 +0800

RHEL6
=====
The missing hunk is already there via:
  perf tools: Fix bench/numa.c for 32-bit build
These 2 patches were in through different branches
and sorted out via merge in upstream.

description
===========
There are two warnings in bench/numa, when building this on 32-bit
machine.

The warning output is attached:

bench/numa.c:1113:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
bench/numa.c:1161:6: error: format %lx expects argument of t'long unsigned int, but argument 5 has type u64 [-Werror=format]

This patch fixes these two warnings.

Signed-off-by: Rafael Aquini <aquini@redhat.com>