libertas: fix uninitialized variable warning
Patchwork-id: 26145
O-Subject: [RHEL6 PATCH BZ 603733 21/59] libertas: fix uninitialized variable
	warning
Bugzilla: 603733
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>

Backport linux-2.6 commit c6a6368b32aa4fd145e840c8d8dac6923fae2688

Fixes

drivers/net/wireless/libertas/rx.c: In function 'process_rxed_802_11_packet':
drivers/net/wireless/libertas/rx.c:361: error: 'radiotap_hdr.flags' may be used uninitialized in this function

Resolves BZ 603733.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>