coretemp: Fix checkpatch error
Patchwork-id: 126391
O-Subject: [RHEL6.8 PATCH BZ 1262397 22/49] hwmon: (coretemp) Fix checkpatch error
Bugzilla: 1262397
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1262397

Conflicts: Minor differences due to some code drift.

commit 780affe0e9162bd6aec8acdb6255d61e4b04abba
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Fri Jan 20 09:31:17 2012 -0800

    hwmon: (coretemp) Fix checkpatch error

    Fix:
    ERROR: Macros with complex values should be enclosed in parenthesis

    Cc: Fenghua Yu <fenghua.yu@intel.com>
    Acked-By: Durgadoss R <durgadoss.r@intel.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>

Cc: Dean Nelson <dnelson@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>