rtnl: avoid uninitialized data in IFLA_VF_VLAN_LIST handling
Message-id: <1479292191-17634-59-git-send-email-ivecera@redhat.com>
Patchwork-id: 160545
O-Subject: [RHEL7.4 net PATCH 58/59] net: rtnl: avoid uninitialized data in IFLA_VF_VLAN_LIST handling
Bugzilla: 1382040
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ#1382040

Upstream commit(s):
commit fa34cd94fb01fcb8d79d91e009451b37692e94e5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Sep 30 18:13:49 2016 +0200

    net: rtnl: avoid uninitialized data in IFLA_VF_VLAN_LIST handling

    With the newly added support for IFLA_VF_VLAN_LIST netlink messages,
    we get a warning about potential uninitialized variable use in
    the parsing of the user input when enabling the -Wmaybe-uninitialized
    warning:

    net/core/rtnetlink.c: In function 'do_setvfinfo':
    net/core/rtnetlink.c:1756:9: error: 'ivvl$' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    I have not been able to prove whether it is possible to arrive in
    this code with an empty IFLA_VF_VLAN_LIST block, but if we do,
    then ndo_set_vf_vlan gets called with uninitialized arguments.

    This adds an explicit check for an empty list, making it obvious
    to the reader and the compiler that this cannot happen.

    Fixes: 79aab093a0b5 ("net: Update API for VF vlan protocol 802.1ad support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Moshe Shemesh <moshe@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>