enic: fix build warning without CONFIG_CPUMASK_OFFSTACK
Message-id: <e737eb4e1cad07d87679cbe59dac86377b724143.1557862523.git.jtoppins@redhat.com>
Patchwork-id: 255806
O-Subject: [PATCH RDMAv5.1 RHEL-8.1 36/41] enic: fix build warning without CONFIG_CPUMASK_OFFSTACK
Bugzilla: 1685313
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The enic driver relies on the CONFIG_CPUMASK_OFFSTACK feature to
dynamically allocate a struct member, but this is normally intended for
local variables.

Building with clang, I get a warning for a few locations that check the
address of the cpumask_var_t:

drivers/net/ethernet/cisco/enic/enic_main.c:122:22: error: address of array 'enic->msix[i].affinity_mask' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]

As far as I can tell, the code is still correct, as the truth value of
the pointer is what we need in this configuration. To get rid of
the warning, use cpumask_available() instead of checking the
pointer directly.

Fixes: 322cf7e3a4e8 ("enic: assign affinity hint to interrupts")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 43d281662fdb46750d49417559b71069f435298d)
Bugzilla: 1685313
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21638863
Tested: basic regression RDMA regression tests
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>