python: Add cgroup.c to setup.py to get it building again
Patchwork-id: 38918
O-Subject: [PATCH RHEL6.2 BZ725522 02/67] perf python: Add cgroup.c to setup.py
	to get it building again
Bugzilla: 725522
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 725522
https://bugzilla.redhat.com/show_bug.cgi?id=725522

upstream status
---------------
commit 4498062e72fd55b2a9a4ac1b44fab8cb44ad5367
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Thu Feb 17 10:07:42 2011 -0200

description
-----------
The 023695d cset added a new file, util/cgroup.c, that is referenced from
util/evsel.c, so it needs to be present in util/setup.py so that the python
shared object binding works, fixing this:

[root@emilia linux]# export PYTHONPATH=~acme/git/build/perf/python/
[root@emilia linux]# ./tools/perf/python/twatch.py
Traceback (most recent call last):
  File "./tools/perf/python/twatch.py", line 16, in <module>
    import perf
ImportError: /home/acme/git/build/perf/python/perf.so: undefined symbol: close_cgroup

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>