perf: Fix build error with bison 2.6
Patchwork-id: 53776
O-Subject: [PATCH RHEL6.4 BZ860404 54/74] perf tools: Fix build error with bison 2.6
Bugzilla: 860404
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 860404
https://bugzilla.redhat.com/show_bug.cgi?id=860404

upstream status
===============
commit 043d1a5c14e95212dbf48251051804ede1ed1862
Author: Kirill A. Shutemov <kirill@shutemov.name>
Date:   Tue Jul 24 00:04:07 2012 +0300

description
===========
Bison 2.6 started to generate parse_events_parse() declaration in header. In
this case we have redundant redeclaration:

util/parse-events.c:29:5: error: redundant redeclaration of ‘parse_events_parse’ [-Werror=redundant-decls]
In file included from util/parse-events.c:14:0:
util/parse-events-bison.h:99:5: note: previous declaration of ‘parse_events_parse’ was here
cc1: all warnings being treated as errors

Let's disable -Wredundant-decls for util/parse-events.c since it includes
header we can't control.

Signed-off-by: Jarod Wilson <jarod@redhat.com>