perf: Fix LIBELF_MMAP checking
Patchwork-id: 59954
O-Subject: [PATCH RHEL6.5 BZ970529 044/146] perf tools: Fix LIBELF_MMAP checking
Bugzilla: 970529
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Namhyung Kim <namhyung.kim@lge.com>

Bugzilla: 970529
https://bugzilla.redhat.com/show_bug.cgi?id=970529

upstream status
===============
commit fcc328032e7382bf413517ee4dddf1eca7970fe4
Author: Namhyung Kim <namhyung.kim@lge.com>
Date:   Fri Oct 26 17:55:52 2012 +0900

description
===========
Currently checking mmap support in libelf failed due to wrong flags.

    CHK libelf
    CHK libdw
    CHK libunwind
    CHK -DLIBELF_MMAP
/tmp/ccYJwdR0.o: In function `main':
:(.text+0x18): undefined reference to `elf_begin'
collect2: error: ld returned 1 exit status

This cannot happen since we checked the elf_begin() when checking
libelf and it succeeded.

Fix it by using a same flag with libelf checking.