ALSA: ASoC: wm9712: fix unused variable warning
Message-id: <15580872947136052-716-patchset-jkysela@redhat.com>
Patchwork-id: 257303
O-Subject: [RHEL 8.1 PATCH 0715/2119] ALSA: ASoC: wm9712: fix unused variable warning
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The 'ret' variable is now only used in an #ifdef, and causes a
warning if it is declared outside of that block:

sound/soc/codecs/wm9712.c: In function 'wm9712_soc_probe':
sound/soc/codecs/wm9712.c:641:6: error: unused variable 'ret' [-Werror=unused-variable]

Fixes: 2ed1a8e0ce8d ("ASoC: wm9712: add ac97 new bus support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Charles Keepax <ckeepax@opensource.cirrus.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 18380dcc52cc8965e5144ce33fdfad7e168679a5)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>