selftests/bpf: use proper type when passing prog_type
Message-id: <20190604085256.3304-430-yauheni.kaliuta@redhat.com>
Patchwork-id: 262431
O-Subject: [RHEL8.1 PATCH v2 430/627] selftests/bpf: use proper type when passing prog_type
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit aca1a80ebe3e4d49adaf6516c61a6786b1ee7dad
Author: Stanislav Fomichev <sdf@google.com>
Date:   Mon Dec 10 15:25:04 2018 -0800

    selftests/bpf: use proper type when passing prog_type

    Use bpf_prog_type instead of bpf_map_type when passing prog_type.

    -Wenum-conversion might be unhappy about it:
            error: implicit conversion from enumeration type
            'enum bpf_map_type' to different enumeration type
            'enum bpf_prog_type'

    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>