vfio/pci: set TRACE_INCLUDE_PATH to fix the build error
Message-id: <1555481285-31844-24-git-send-email-sbobroff@redhat.com>
Patchwork-id: 250217
O-Subject: [RHEL8.1 BZ1524679 PATCH v2 23/25] vfio/pci: set TRACE_INCLUDE_PATH to fix the build error
Bugzilla: 1524679
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Masahiro Yamada <yamada.masahiro@socionext.com>

drivers/vfio/pci/vfio_pci_nvlink2.c cannot be compiled for in-tree
building.

    CC      drivers/vfio/pci/vfio_pci_nvlink2.o
  In file included from drivers/vfio/pci/trace.h:102,
                   from drivers/vfio/pci/vfio_pci_nvlink2.c:29:
  ./include/trace/define_trace.h:89:42: fatal error: ./trace.h: No such file or directory
   #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                          ^
  compilation terminated.
  make[1]: *** [scripts/Makefile.build;277: drivers/vfio/pci/vfio_pci_nvlink2.o] Error 1

To fix the build error, let's tell include/trace/define_trace.h the
location of drivers/vfio/pci/trace.h

Fixes: 7f92891778df ("vfio_pci: Add NVIDIA GV100GL [Tesla V100 SXM2] subdriver")
Reported-by: Laura Abbott <labbott@redhat.com>
Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
Reviewed-by: Cornelia Huck <cohuck@redhat.com>
Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
(cherry picked from commit d1fc1176c055c9ec9c6ec4d113a284e0bad9d09a)

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1524679
Testing: Use QEMU/KVM to pass an Nvidia Volta (GPU) to a guest
Signed-off-by: Sam Bobroff <sbobroff@redhat.com>
Upstream: Patch is upstream
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>