tg3: unconditionally select HWMON support when tg3 is enabled
Patchwork-id: 60904
O-Subject: [RHEL6.5 PATCH 21/90] tg3: unconditionally select HWMON support when tg3 is enabled.
Bugzilla: 915516
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ: #915516

Upstream commit:
commit de0a41484c47d783dd4d442914815076aa2caac2
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Mon Oct 1 11:43:49 2012 -0400

    tg3: unconditionally select HWMON support when tg3 is enabled.

    There is the seldom used corner case where HWMON=m at the same
    time as TIGON3=y (typically randconfigs) which will cause a link
    fail like:

    drivers/built-in.o: In function `tg3_close':
    tg3.c:(.text+0x16bd86): undefined reference to `hwmon_device_unregister'
    drivers/built-in.o: In function `tg3_hwmon_open':
    tg3.c:(.text+0x16fc4b): undefined reference to `hwmon_device_register'
    make[1]: *** [vmlinux] Error 1

    Fix it as suggested by DaveM[1] by having the Kconfig logic simply
    select HWMON when TIGON3 is selected.  This gets rid of all the
    extra IS_ENABLED ifdeffery in tg3.c as a side benefit.

    [1] http://marc.info/?l=linux-netdev&m=134250573718151&w=2

    Cc: Michael Chan <mchan@broadcom.com>
    Reported-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
    Reported-by: Anisse Astier <anisse@astier.eu>
    Suggested-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>