x86: Perf_event_amd.c needs <asm/apicdef.h>
Patchwork-id: 57793
O-Subject: [PATCH RHEL6.5 BZ927177 12/22] x86: Perf_event_amd.c needs <asm/apicdef.h>
Bugzilla: 927177
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Randy Dunlap <rdunlap@xenotime.net>

Bugzilla: 927177
https://bugzilla.redhat.com/show_bug.cgi?id=927177

upstream status
===============
commit d6eed550a9d08fbd1fce32e517e8c49afa6edbf7
Author: Randy Dunlap <rdunlap@xenotime.net>
Date:   Tue Sep 27 10:00:40 2011 -0700

description
===========
Fix (rare) build error by adding <asm/apicdef.h> header file:

  arch/x86/kernel/cpu/perf_event_amd.c:350:2: error: 'BAD_APICID' undeclared (first use in this function)

Signed-off-by: Jarod Wilson <jarod@redhat.com>