sched: fix ->get helper of the matchall cls
Message-id: <20190610212005.12299-155-ivecera@redhat.com>
Patchwork-id: 264141
O-Subject: [RHEL-8.1 net PATCH 154/194] net/sched: fix ->get helper of the matchall cls
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 0db6f8befc32c68bb13d7ffbb2e563c79e913e13
Author: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Date:   Thu Mar 28 10:35:06 2019 +0100

    net/sched: fix ->get helper of the matchall cls

    It returned always NULL, thus it was never possible to get the filter.

    Example:
    $ ip link add foo type dummy
    $ ip link add bar type dummy
    $ tc qdisc add dev foo clsact
    $ tc filter add dev foo protocol all pref 1 ingress handle 1234 \
            matchall action mirred ingress mirror dev bar

    Before the patch:
    $ tc filter get dev foo protocol all pref 1 ingress handle 1234 matchall
    Error: Specified filter handle not found.
    We have an error talking to the kernel

    After:
    $ tc filter get dev foo protocol all pref 1 ingress handle 1234 matchall
    filter ingress protocol all pref 1 matchall chain 0 handle 0x4d2
      not_in_hw
            action order 1: mirred (Ingress Mirror to device bar) pipe
            index 1 ref 1 bind 1

    Fixes: fd62d9f5c575 ("net/sched: matchall: Fix configuration race")
    Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>