rh_kabi: Provide better error messages for size and align checks
Message-id: <1488931957-2917-1-git-send-email-prarit@redhat.com>
Patchwork-id: 172784
O-Subject: [RHEL7.4 PATCH BZ 1425864 v6] rh_kabi: Provide better error messages for size and align checks
Bugzilla: 1425864
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1425864

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12706703

RHEL_only.

When enabling CONFIG_DEBUG_SPINLOCK, the kernel compile fails with a medium
sized list of errors.

	include/linux/rh_kabi.h:64:3: error: static assertion failed: "kabi sizeof test panic"
	   _Static_assert(sizeof(struct{_new;}) <= sizeof(struct{_orig;}), \
	   ^
	<snip 9 lines of boring error messages>

	include/linux/sched.h:706:2: note: in expansion of macro 'RH_KABI_USE'
	  RH_KABI_USE(1, seqlock_t stats_lock)
	  ^
	make[1]: *** [arch/x86/kernel/asm-offsets.s] Error 1
	make: *** [prepare0] Error 2

Change the error message so that it provides file and line information, as
well as information on how to proceed if someone is debugging the kernel.

After the change the 1st error message is

include/linux/rh_kabi.h:66:3: error: static assertion failed:
"include/linux/sched.h:706: seqlock_t stats_lock is larger than unsigned
long rh_reserved1.  Disable CONFIG_RH_KABI_SIZE_ALIGN_CHECKS if
debugging."

tcamuso found this when he enabled CONFIG_DEBUG_SPINLOCK in the .config

[v2]: jbenc, use __stringify
[v3]: remove extra line
[v4]: I gud spel.
[v5]: jarod, Change size assert check wording to "is larger than"
[v6]: aquini, some architectures don't have __stringify defined

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: tcamuso@redhat.com
Signed-off-by: Rafael Aquini <aquini@redhat.com>