sched: cls_flower: fix use of uninitialized ethertype variable in cls_flower
Message-id: <9348af26f39f5d9be548e920c008bad0f8883740.1490136269.git.jtoppins@redhat.com>
Patchwork-id: 174952
O-Subject: [RHEL7.4 net v4 17/59] net_sched: fix use of uninitialized ethertype variable in cls_flower
Bugzilla: 1393375
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

The addition of VLAN support caused a possible use of uninitialized
data if we encounter a zero TCA_FLOWER_KEY_ETH_TYPE key, as pointed
out by "gcc -Wmaybe-uninitialized":

net/sched/cls_flower.c: In function 'fl_change':
net/sched/cls_flower.c:366:22: error: 'ethertype' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This changes the code to only set the ethertype field if it
was nonzero, as before the patch.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 9399ae9a6cb2 ("net_sched: flower: Add vlan support")
Cc: Hadar Hen Zion <hadarh@mellanox.com>
Cc: Jiri Pirko <jiri@mellanox.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 0b498a52778368ff501557d68c7b50878ab1701e)
Bugzilla: 1393375
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12825917
Tested: compile tested

Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>