benet: fix build error on 32bit arch
Patchwork-id: 44804
O-Subject: [RHEL6.3 PATCH 09/62] benet: fix build error on 32bit arch
Bugzilla: 738041
RH-Acked-by: David S. Miller <davem@redhat.com>

BZ: #738041

Upstream commit:
commit 68c3e5a7b91513010d2536e4bcd7bdd54d0e6acf
Author: Eric Dumazet <eric.dumazet@gmail.com>
Date:   Tue Aug 9 06:23:07 2011 +0000

    benet: fix build error on 32bit arch

    Error comes from commit ac124ff973e27802797
    (be2net: cleanup and refactor stats code)

    ERROR: "__udivdi3" [drivers/net/benet/be2net.ko] undefined!

    Signed-off-by: Eric Dumazet <eric.dumazet@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>