blkio-throttle: Fix link failure failure on i386
Patchwork-id: 29026
O-Subject: [RHEL6.1 PATCH 12/17] blkio-throttle: Fix link failure failure on i386
Bugzilla: 636022
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

BZ:636022

Upstream commit 3aad5d3ee4e4fce8f4b5bb6ca73342dcade42b33

o Randy Dunlap reported following linux-next failure. This patch fixes it.

on i386:

blk-throttle.c:(.text+0x1abb8): undefined reference to `__udivdi3'
blk-throttle.c:(.text+0x1b1dc): undefined reference to `__udivdi3'

o bytes_per_second interface is 64bit and I was continuing to do 64 bit
  division even on 32bit platform without help of special macros/functions
  hence the failure.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>
Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Jens Axboe <jaxboe@fusionio.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>