ALSA: ASoC: davinci-mcasp: Fix clang warning without CONFIG_PM
Message-id: <15580872947136052-1645-patchset-jkysela@redhat.com>
Patchwork-id: 257877
O-Subject: [RHEL 8.1 PATCH 1644/2119] ALSA: ASoC: davinci-mcasp: Fix clang warning without CONFIG_PM
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Building with clang shows a variable that is only used by the
suspend/resume functions but defined outside of their #ifdef block:

sound/soc/ti/davinci-mcasp.c:48:12: error: variable 'context_regs' is not needed and will not be emitted

We commonly fix these by marking the PM functions as __maybe_unused,
but here that would grow the davinci_mcasp structure, so instead
add another #ifdef here.

Fixes: 1cc0c054f380 ("ASoC: davinci-mcasp: Convert the context save/restore to use array")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 8ca5104715cfd14254ea5aecc390ae583b707607)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>