perf/evsel: Fix a build failure on cross compilation
Patchwork-id: 53759
O-Subject: [PATCH RHEL6.4 BZ860404 23/74] perf evsel: Fix a build failure on cross compilation
Bugzilla: 860404
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 860404
https://bugzilla.redhat.com/show_bug.cgi?id=860404

upstream status
===============
commit 35a468732289372aab506d7cf73f98f0379888ae
Author: Namhyung Kim <namhyung.kim@lge.com>
Date:   Thu Jun 21 17:52:52 2012 +0900

description
===========
The commit c410431cefefd ("perf tools: Reconstruct event with modifiers
from perf_event_attr") added the line, but it's broken since it needs to
go up 3 directories to get to the kernel root directory, not 2.

However host gcc contains /usr/local/include in its search path, so that
it can find the perf_event.h in /usr/include. This why we didn't notice
the problem yet.  But when I tried to cross compile it appears like:

      CC util/evsel.o
  util/evsel.c:18:44: error: ../../include/linux/perf_event.h: No such file or directory
  make: *** [util/evsel.o] Error 1

Looking at the source, it isn't needed at all as evsel.h already
included the perf_event.h. So simply remove it would solve the problem.

Signed-off-by: Jarod Wilson <jarod@redhat.com>