sched: avoid unused-label warning
Message-id: <20190610212005.12299-127-ivecera@redhat.com>
Patchwork-id: 264112
O-Subject: [RHEL-8.1 net PATCH 126/194] net/sched: avoid unused-label warning
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 096461de96a94c856190ba892ebf62dfba5a38f1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 4 21:40:32 2019 +0100

    net/sched: avoid unused-label warning

    The label is only used from inside the #ifdef and should be
    hidden the same way, to avoid this warning:

    net/sched/act_tunnel_key.c: In function 'tunnel_key_init':
    net/sched/act_tunnel_key.c:389:1: error: label 'release_tun_meta' defined but not used [-Werror=unused-label]
     release_tun_meta:

    Fixes: 41411e2fd6b8 ("net/sched: act_tunnel_key: Add dst_cache support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>