perf tools: Add missing open_memstream() prototype for systems lacking it
Message-id: <07524998af8695c8cd0ff847e4187a062de22821.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265020
O-Subject: [RHEL8.1 BZ1715507 127/234] perf tools: Add missing open_memstream() prototype for systems lacking it
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit d7a8c4a6a055097a67ccfa3ca7c9ff1b64603a70
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Dec 11 16:31:19 2018 -0300

description
===========
There are systems such as the Android NDK API level 24 has the
open_memstream() function but doesn't provide a prototype, adding noise
to the build:

  builtin-timechart.c: In function 'cat_backtrace':
  builtin-timechart.c:486:2: warning: implicit declaration of function 'open_memstream' [-Wimplicit-function-declaration]
    FILE *f = open_memstream(&p, &p_len);
    ^
  builtin-timechart.c:486:2: warning: nested extern declaration of 'open_memstream' [-Wnested-externs]
  builtin-timechart.c:486:12: warning: initialization makes pointer from integer without a cast
    FILE *f = open_memstream(&p, &p_len);
              ^

Define a LACKS_OPEN_MEMSTREAM_PROTOTYPE define so that code needing that
can get a prototype.

Checked in the bionic git repo to be available since level 23:

https://android.googlesource.com/platform/bionic/+/master/libc/include/stdio.h#241

  FILE* open_memstream(char** __ptr, size_t* __size_ptr) __INTRODUCED_IN(23);

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>