flow_dissector: fix build failure without CONFIG_NET
Message-id: <20190604085256.3304-126-yauheni.kaliuta@redhat.com>
Patchwork-id: 262119
O-Subject: [RHEL8.1 PATCH v2 126/627] flow_dissector: fix build failure without CONFIG_NET
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 2dfd184abd38fd72d80715fa8b00c9de78490200
Author: Willem de Bruijn <willemb@google.com>
Date:   Tue Sep 18 16:20:18 2018 -0400

    flow_dissector: fix build failure without CONFIG_NET

    If boolean CONFIG_BPF_SYSCALL is enabled, kernel/bpf/syscall.c will
    call flow_dissector functions from net/core/flow_dissector.c.

    This causes this build failure if CONFIG_NET is disabled:

        kernel/bpf/syscall.o: In function `__x64_sys_bpf':
        syscall.c:(.text+0x3278): undefined reference to
        `skb_flow_dissector_bpf_prog_attach'
        syscall.c:(.text+0x3310): undefined reference to
        `skb_flow_dissector_bpf_prog_detach'
        kernel/bpf/syscall.o:(.rodata+0x3f0): undefined reference to
        `flow_dissector_prog_ops'
        kernel/bpf/verifier.o:(.rodata+0x250): undefined reference to
        `flow_dissector_verifier_ops'

    Analogous to other optional BPF program types in syscall.c, add stubs
    if the relevant functions are not compiled and move the BPF_PROG_TYPE
    definition in the #ifdef CONFIG_NET block.

    Fixes: d58e468b1112 ("flow_dissector: implements flow dissector BPF hook")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Willem de Bruijn <willemb@google.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>