ib/mlx5: avoid bogus -Wmaybe-uninitialized warning
Message-id: <1488853076-16738-232-git-send-email-ddutile@redhat.com>
Patchwork-id: 171949
O-Subject: [PATCH RHEL-7.4 231/340] IB/mlx5: avoid bogus -Wmaybe-uninitialized warning
Bugzilla: 1385330 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385330

commit 14ab8896f5d993c5f427504276e3c42ccb3cc354
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 24 22:48:21 2016 +0200

    IB/mlx5: avoid bogus -Wmaybe-uninitialized warning

    We get a false-positive warning in linux-next for the mlx5 driver:

    infiniband/hw/mlx5/mr.c: In function mlx5_ib_reg_user_mr:
    infiniband/hw/mlx5/mr.c:1172:5: error: order may be used uninitialized in this function [-Werror=maybe-uninitialized]
    infiniband/hw/mlx5/mr.c:1161:6: note: order was declared here
    infiniband/hw/mlx5/mr.c:1173:6: error: ncont may be used uninitialized in this function [-Werror=maybe-uninitialized]
    infiniband/hw/mlx5/mr.c:1160:6: note: ncont was declared here
    infiniband/hw/mlx5/mr.c:1173:6: error: page_shift may be used uninitialized in this function [-Werror=maybe-uninitialized]
    infiniband/hw/mlx5/mr.c:1158:6: note: page_shift was declared here
    infiniband/hw/mlx5/mr.c:1143:13: error: npages may be used uninitialized in this function [-Werror=maybe-uninitialized]
    infiniband/hw/mlx5/mr.c:1159:6: note: npages was declared here

    I had a trivial workaround for gcc-5 or higher, but that didn't work
    on gcc-4.9 unfortunately.

    The only way I found to avoid the warnings for gcc-4.9, short of
    initializing each of the arguments first was to change the calling
    conventions to separate the error code from the umem pointer. This
    avoids casting the error codes from one pointer to another incompatible
    pointer, and lets gcc figure out when that the data is actually valid
    whenever we return successfully.

    Acked-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>

Conflict patch:
10871-infiniband-ib-mlx5-avoid-bogus-Wmaybe-uninitialized-warning.patch

Merge log:
patching file drivers/infiniband/hw/mlx5/mr.c
Hunk #1 merged at 848-851,857-862,867, NOT MERGED at 871-876,879-880,888.
(EScore specific version string)