fix undefined reference to 'pci_fixup_final_inited'
Patchwork-id: 86831
O-Subject: [RHEL6.6 PATCH BZ 1084398 2/6 v2] PCI: fix undefined reference to 'pci_fixup_final_inited'
Bugzilla: 1084398
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1084398
Upstream Status: 95df8b8708a8b381bf276d83c56f7b4e7de04a71

commit 95df8b8708a8b381bf276d83c56f7b4e7de04a71
Author: Myron Stowe <myron.stowe@redhat.com>
Date:   Fri Jul 13 14:29:00 2012 -0600

    PCI: fix undefined reference to 'pci_fixup_final_inited'

    My "PCI: Integrate 'pci_fixup_final' quirks into hot-plug paths" patch
    introduced an undefined reference to 'pci_fixup_final_inited' when
    CONFIG_PCI_QUIRKS is not enabled (on x86_64):
      drivers/built-in.o: In function `pci_bus_add_device':
      (.text+0x4f62): undefined reference to `pci_fixup_final_inited'

    This patch removes the external reference ending up with a result closer
    to what we ultimately want when the boot path issues described in the
    original patch are resolved.

    References:
      https://lkml.org/lkml/2012/7/9/542    Original, offending, patch
      https://lkml.org/lkml/2012/7/12/338	Randy's catch

    Reported-by: Randy Dunlap <rdunlap@xenotime.net>
    Signed-off-by: Myron Stowe <myron.stowe@redhat.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Acked-by: Randy Dunlap <rdunlap@xenotime.net>

Conflicts:

	drivers/pci/quirks.c

*remove context lines from 4e344b1c and ac1aa47b

Signed-off-by: Michael Roth <mdroth@linux.vnet.ibm.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>