mlx4: fix unresolved 64bit math in mellanox/mlx4/en_dcb_nl.c
Patchwork-id: 64166
O-Subject: [RHEL 6.5 PATCH 117/129] drivers/net: fix unresolved 64bit math in mellanox/mlx4/en_dcb_nl.c
Bugzilla: 950401 950910 950913 950915
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Doug Ledford <dledford@redhat.com>

From: Paul Gortmaker <paul.gortmaker@windriver.com>

Commit 109d2446052a484c58f07f71f9457bf7b71017f8

    "net/mlx4_en: Set max rate-limit for a TC"

introduced 64 bit math operations into mlx4_en_dcbnl_ieee_setmaxrate()

causing the following final link failure on an x86_32 allmodconfig

  ERROR: "__udivdi3" [drivers/net/ethernet/mellanox/mlx4/mlx4_en.ko] undefined!

Convert it to use div_u64() instead.

Cc: Amir Vadai <amirv@mellanox.com>
Cc: David S. Miller <davem@davemloft.net>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 43c880dff302b30a17044a2d5e4d2f343bf493dc)

Signed-off-by: Amir Vadai <avadai@redhat.com>