tools/bpftool: move set_max_rlimit() before __bpf_object__open_xattr()
Message-id: <20190604085256.3304-625-yauheni.kaliuta@redhat.com>
Patchwork-id: 262622
O-Subject: [RHEL8.1 PATCH v2 625/627] tools/bpftool: move set_max_rlimit() before __bpf_object__open_xattr()
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit ac4e0e055fee5751c78bba1fc9ce508a6874d916
Author: Yonghong Song <yhs@fb.com>
Date:   Thu May 16 10:17:31 2019 -0700

    tools/bpftool: move set_max_rlimit() before __bpf_object__open_xattr()

    For a host which has a lower rlimit for max locked memory (e.g., 64KB),
    the following error occurs in one of our production systems:
      # /usr/sbin/bpftool prog load /paragon/pods/52877437/home/mark.o \
        /sys/fs/bpf/paragon_mark_21 type cgroup/skb \
        map idx 0 pinned /sys/fs/bpf/paragon_map_21
      libbpf: Error in bpf_object__probe_name():Operation not permitted(1).
        Couldn't load basic 'r0 = 0' BPF program.
      Error: failed to open object file

    The reason is due to low locked memory during bpf_object__probe_name()
    which probes whether program name is supported in kernel or not
    during __bpf_object__open_xattr().

    bpftool program load already tries to relax mlock rlimit before
    bpf_object__load(). Let us move set_max_rlimit() before
    __bpf_object__open_xattr(), which fixed the issue here.

    Fixes: 47eff61777c7 ("bpf, libbpf: introduce bpf_object__probe_caps to test BPF capabilities")
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>