TCG_ATMEL should depend on HAS_IOPORT
Patchwork-id: 129701
O-Subject: [RHEL6.8 PATCH BZ1254015 032/118] TPM: TCG_ATMEL should depend on HAS_IOPORT
Bugzilla: 1254015
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10222730
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1254015

        commit 5ce5ed35939ece8a9c7e0f10c7f3d5bc000c6b64
	Author: Geert Uytterhoeven <geert@linux-m68k.org>
	Date:   Mon Aug 8 13:08:19 2011 +0200

	TPM: TCG_ATMEL should depend on HAS_IOPORT

	On m68k, I get:

	drivers/char/tpm/tpm_atmel.h: In function 'atmel_get_base_addr':
	drivers/char/tpm/tpm_atmel.h:129: error: implicit declaration of function 'ioport_map'
	drivers/char/tpm/tpm_atmel.h:129: warning: return makes pointer from integer without a cast

	The code in tpm_atmel.h supports PPC64 (using the device tree and ioremap())
	and "anything else" (using ioport_map()). However, ioportmap() is only
	available on platforms that set HAS_IOPORT.

	Although PC64 seems to have HAS_IOPORT, a "depends on HAS_IOPORT" should work,
	but I think it's better to expose the special PPC64 handling explicit using
	"depends on PPC64 || HAS_IOPORT".

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Rajiv Andrade <srajiv@linux.vnet.ibm.com>
	Signed-off-by: James Morris <jmorris@namei.org>

Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>