ALSA: ASoC: soc-utils: Rename dummy_dma_ops to snd_dummy_dma_ops
Message-id: <15580872947136052-713-patchset-jkysela@redhat.com>
Patchwork-id: 257228
O-Subject: [RHEL 8.1 PATCH 0712/2119] ALSA: ASoC: soc-utils: Rename dummy_dma_ops to snd_dummy_dma_ops
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The symbols 'dummy_dma_ops' is declared with different data types by
sound/soc/soc-utils.c and arch/arm64/include/asm/dma-mapping.h. This
leads to conflicts when soc-utils.c (indirectly) includes dma-mapping.h:

sound/soc/soc-utils.c:282:33: error: conflicting types for 'dummy_dma_ops'
  static const struct snd_pcm_ops dummy_dma_ops = {
                                  ^
...
arch/arm64/include/asm/dma-mapping.h:27:33: note: previous declaration of 'dummy_dma_ops' was here
  extern const struct dma_map_ops dummy_dma_ops;
                                  ^

Rename the symbol in soc-utils.c to 'snd_dummy_dma_ops' to avoid the
conflict.

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 42cfb412e24ffbb46d6de9590293bc44f921a0fb)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>