perf tools: Fix arm64 build error
Patchwork-id: 123636
O-Subject: [PATCH RHEL6 BZ1216217 133/341] perf tools: Fix arm64 build error
Bugzilla: 1216217
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1216217
https://bugzilla.redhat.com/show_bug.cgi?id=1216217

upstream
========
commit 7d885749b6de2c9a1168d566e2380207b9177108
Author: Mark Salter <msalter@redhat.com>
Date: Fri Jul 25 18:02:46 2014 -0400

description
===========
I'm seeing the following build error on arm64:

  In file included from util/event.c:3:0:
  util/event.h:95:17: error: 'PERF_REGS_MAX' undeclared here (not in a function)
    u64 cache_regs[PERF_REGS_MAX];
                 ^

This patch adds a PERF_REGS_MAX definition for arm64.