perf python: Fix undefined symbol problem
Patchwork-id: 43557
O-Subject: [PATCH RHEL6.3 BZ784888 93/97] perf python: Fix undefined symbol
	problem
Bugzilla: 784888
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 784888
https://bugzilla.redhat.com/show_bug.cgi?id=784888

upstream status
===============
commit 0e2a5f10fb550835e199a3b56a80ed88232188e9
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Fri Nov 4 08:16:58 2011 -0200

description
===========
Recently we made perf_evsel__init call hists__init, which broke the perf
python binding:

[root@emilia linux]# ./tools/perf/python/twatch.py
Traceback (most recent call last):
  File "./tools/perf/python/twatch.py", line 16, in <module>
    import perf
ImportError: /home/acme/git/build/perf/python/perf.so: undefined symbol: hists__init

Fix it by moving the hists__init function to its only caller, evsel.c.

This way we avoid dragging in other parts of tools/perf/util/ to the
perf python binding.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>