qedf: fix wrong le16 conversion
Message-id: <1491962485-29074-4-git-send-email-hpatil@redhat.com>
Patchwork-id: 176653
O-Subject: [PATCH RHEL 7.4 3/5] qedf: fix wrong le16 conversion
Bugzilla: 1432196
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ 1432196

upstream (net-next) commit id 6f359f99b8c2ff3b09329611da00fe39a7c10e7e

gcc points out that we are converting a 16-bit integer into a 32-bit
little-endian type and assigning that to 16-bit little-endian
will end up with a zero:

drivers/scsi/qedf/drv_fcoe_fw_funcs.c: In function 'init_initiator_rw_fcoe_task':
include/uapi/linux/byteorder/big_endian.h:32:26: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
  t_st_ctx->read_write.rx_id = cpu_to_le32(FCOE_RX_ID);

The correct solution appears to be to just use a 16-bit byte swap instead.

Fixes: be086e7c53f1 ("qed*: Utilize Firmware 8.15.3.0")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Chad Dupuis <chad.dupuis@cavium.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 6f359f99b8c2ff3b09329611da00fe39a7c10e7e)
Signed-off-by: Harish Patil <hpatil@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>