sctp: dubious bitfields in sctp_transport
Patchwork-id: 38484
O-Subject: [RHEL6.2 PATCH 39/63] sctp: dubious bitfields in sctp_transport
Bugzilla: 679456
RH-Acked-by: Neil Horman <nhorman@redhat.com>

Backport of:
commit ff937938e7781b2c1bffce0a5400af308e3946d5
Author: Dan Carpenter <error27@gmail.com>
Date:   Wed May 26 00:40:11 2010 -0700

    sctp: dubious bitfields in sctp_transport

    Sparse complains because these one-bit bitfields are signed.
      include/net/sctp/structs.h:879:24: error: dubious one-bit signed bitfield
      include/net/sctp/structs.h:889:31: error: dubious one-bit signed bitfield
      include/net/sctp/structs.h:895:26: error: dubious one-bit signed bitfield
      include/net/sctp/structs.h:898:31: error: dubious one-bit signed bitfield
      include/net/sctp/structs.h:901:27: error: dubious one-bit signed bitfield

    It doesn't cause a problem in the current code, but it would be better
    to clean it up.  This was introduced by c0058a35aacc7: "sctp: Save some
    room in the sctp_transport by using bitfields".

    Signed-off-by: Dan Carpenter <error27@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>