fix compiling problem with i386
Patchwork-id: 32793
O-Subject: Re: [RHEL6.1 Patch 021/386] RDMA/cxgb4: Add driver for Chelsio T4 RNIC
Bugzilla: 607396 633157 633329 633875 635914 660674 660680
CVE: CVE-2010-3296

> cc1: warnings being treated as errors
> drivers/infiniband/hw/cxgb4/device.c: In function 'c4iw_rdev_open':
> drivers/infiniband/hw/cxgb4/device.c:316: error: cast to pointer from
> integer of different size
> make[3]: *** [drivers/infiniband/hw/cxgb4/device.o] Error 1
> make[2]: *** [drivers/infiniband/hw/cxgb4] Error 2
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [drivers/infiniband] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make: *** [drivers] Error 2
> make: *** Waiting for unfinished jobs....
> + exit 1

OK, so that's weird.  Took me a while to track it down.  Anyway, the
attached patch resolves the issue.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>