Fix core compile with CONFIG_USB_SUSPEND=n
Patchwork-id: 64212
O-Subject: [RHEL6 PATCH 14/70] USB: Fix core compile with CONFIG_USB_SUSPEND=n
Bugzilla: 815547
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=815547

commit e9261fb62a8b6a79a58c57cc6f4a40530b040b61
Author: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Date:   Mon May 21 08:29:01 2012 -0700

    USB: Fix core compile with CONFIG_USB_SUSPEND=n

    When CONFIG_PM=n, make sure that the usb_[unlocked_][en/dis]able_lpm
    declarations are visible in include/linux/usb.h, and exported from
    drivers/usb/core/hub.c.

    Before this patch, if CONFIG_USB_SUSPEND was turned off, it would cause
    build errors:

    drivers/usb/core/hub.c: In function 'usb_disable_lpm':
    drivers/usb/core/hub.c:3394:2: error: implicit declaration of function 'usb_enable_lpm' [-Werror=implicit-function-declaration]
    drivers/usb/core/hub.c: At top level:
    drivers/usb/core/hub.c:3424:6: warning: conflicting types for 'usb_enable_lpm' [enabled by default]
    drivers/usb/core/hub.c:3394:2: note: previous implicit declaration of 'usb_enable_lpm' was here
    drivers/usb/core/driver.c: In function 'usb_probe_interface':
    drivers/usb/core/driver.c:339:2: error: implicit declaration of function 'usb_unlocked_disable_lpm' [-Werror=implicit-function-declaration]
    drivers/usb/core/driver.c:364:3: error: implicit declaration of function 'usb_unlocked_enable_lpm' [-Werror=implicit-function-declaration]
    drivers/usb/core/message.c: In function 'usb_set_interface':
    drivers/usb/core/message.c:1314:2: error: implicit declaration of function 'usb_disable_lpm' [-Werror=implicit-function-declaration]
    drivers/usb/core/message.c:1323:3: error: implicit declaration of function 'usb_enable_lpm' [-Werror=implicit-function-declaration]
    drivers/usb/core/message.c:1368:2: error: implicit declaration of function 'usb_unlocked_enable_lpm' [-Werror=implicit-function-declaration]

    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reported-by: Chen Peter-B29397 <B29397@freescale.com>