UV: uv_irq.c: Fix all sparse warnings
Patchwork-id: 25456
O-Subject: [PATCH 12/12] x86, UV: uv_irq.c: Fix all sparse warnings
Bugzilla: 573095
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

commit a289cc7c70da784a2d370b91885cab4f966dcb0f
Author: Randy Dunlap <randy.dunlap@oracle.com>
Date:   Fri Apr 16 17:51:42 2010 -0700

    x86, UV: uv_irq.c: Fix all sparse warnings

    Fix all sparse warnings in building uv_irq.c.

     arch/x86/kernel/uv_irq.c:46:17: warning: symbol 'uv_irq_chip' was not declared. Should it be static?
     arch/x86/kernel/uv_irq.c:143:50: error: no identifier for function argument
     arch/x86/kernel/uv_irq.c:162:13: error: typename in expression
     arch/x86/kernel/uv_irq.c:162:13: error: undefined identifier 'restrict'
     arch/x86/kernel/uv_irq.c:250:44: error: no identifier for function argument
     arch/x86/kernel/uv_irq.c:260:17: error: typename in expression
     arch/x86/kernel/uv_irq.c:260:17: error: undefined identifier 'restrict'
     arch/x86/kernel/uv_irq.c:233:50: warning: incorrect type in argument 3 (different signedness)
     arch/x86/kernel/uv_irq.c:233:50:    expected int *pnode
     arch/x86/kernel/uv_irq.c:233:50:    got unsigned int *<noident>
     arch/x86/include/asm/uv/uv_hub.h:318:44: warning: incorrect type in argument 2 (different address spaces)
     arch/x86/include/asm/uv/uv_hub.h:318:44:    expected void volatile [noderef] <asn:2>*addr
     arch/x86/include/asm/uv/uv_hub.h:318:44:    got unsigned long *

    Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
    Cc: Dimitri Sivanich <sivanich@sgi.com>
    Cc: Russ Anderson <rja@sgi.com>
    Cc: Robin Holt <holt@sgi.com>
    Cc: Mike Travis <travis@sgi.com>
    Cc: Cliff Wickman <cpw@sgi.com>
    Cc: Jack Steiner <steiner@sgi.com>
    LKML-Reference: <20100416175142.f4b59683.randy.dunlap@oracle.com>
    Signed-off-by: Ingo Molnar <mingo@elte.hu>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>