qedi: fix build, depends on UIO
Message-id: <1487183954-4614-3-git-send-email-cdupuis@redhat.com>
Patchwork-id: 166301
O-Subject: [PATCH RHEL 7.4 e-stor 2/3] scsi: qedi: fix build, depends on UIO
Bugzilla: 1384083
RH-Acked-by: Chris Leech <cleech@redhat.com>
RH-Acked-by: Maurizio Lombardi <mlombard@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Randy Dunlap <rdunlap@infradead.org>

linux commit 7961d53d22375bb9e8ae8063533b9059102ed39d

Fix build of SCSI qedi driver. It uses uio interfaces so it should
depend on UIO.

ERROR: "uio_unregister_device" [drivers/scsi/qedi/qedi.ko] undefined!
ERROR: "uio_event_notify" [drivers/scsi/qedi/qedi.ko] undefined!
ERROR: "__uio_register_device" [drivers/scsi/qedi/qedi.ko] undefined!

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: QLogic-Storage-Upstream@cavium.com
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>