perf script python: Add Python3 support to tests/attr.py
Message-id: <d02003f0a1c5482705150d48234db2b192ae2e36.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265112
O-Subject: [RHEL8.1 BZ1715507 232/234] perf script python: Add Python3 support to tests/attr.py
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 8f2f350cbdb2c2fbff654cb778139144b48a59ba
Author: Tony Jones <tonyj@suse.de>
Date: Wed Jan 23 16:52:29 2019 -0800

description
===========
Support both Python 2 and Python 3 in tests/attr.py

The use of "except as" syntax implies the minimum supported Python2 version is
now v2.6

Committer testing:

  $ make -C tools/perf PYTHON3=python install-bin

Before:

  # perf test attr
  16: Setup struct perf_event_attr                          : FAILED!
  48: Synthesize attr update                                : Ok
  [root@quaco ~]# perf test -v attr
  16: Setup struct perf_event_attr                          :
  --- start ---
  test child forked, pid 3121
    File "/home/acme/libexec/perf-core/tests/attr.py", line 324
      except Unsup, obj:
                ^
  SyntaxError: invalid syntax
  test child finished with -1
  ---- end ----
  Setup struct perf_event_attr: FAILED!
  48: Synthesize attr update                                :
  --- start ---
  test child forked, pid 3124
  test child finished with 0
  ---- end ----
  Synthesize attr update: Ok
  #

After:

   # perf test attr
  16: Setup struct perf_event_attr                          : Ok
  48: Synthesize attr update                                : Ok
  #

RHEL8
=====
Python 3 compatibility has been already fixed for this file in RHEL-8
by commit a2fa767af1da968aa6f45324577fd6c6a69a0bab which was not taken
from upstream. The fix is almost the same, so within this patch, I just
polish the file to match upstream for easier future maintenance.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>