qed: fix link config error handling
Message-id: <20190520064507.24882-45-mchopra@redhat.com>
Patchwork-id: 258990
O-Subject: [PATCH v2 RHEL8.1 044/109] qed: fix link config error handling
Bugzilla: 1663274
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1663274
Upstream: linux.git

commit 92619210529a6b77b2cbedbadba3ff5eaa6e28ed
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 2 16:36:24 2018 +0100

    qed: fix link config error handling

    gcc-8 notices that qed_mcp_get_transceiver_data() may fail to
    return a result to the caller:

    drivers/net/ethernet/qlogic/qed/qed_mcp.c: In function 'qed_mcp_trans_speed_mask':
    drivers/net/ethernet/qlogic/qed/qed_mcp.c:1955:2: error: 'transceiver_type' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    When an error is returned by qed_mcp_get_transceiver_data(), we
    should propagate that to the caller of qed_mcp_trans_speed_mask()
    rather than continuing with uninitialized data.

    Fixes: c56a8be7e7aa ("qed: Add supported link and advertise link to display in ethtool.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>