net/mlx5: Fix compilation warning in eq.c
Message-id: <20190611144900.12371-41-ahleihel@redhat.com>
Patchwork-id: 265175
O-Subject: [RHEL8.1 BZ 1691238 v2 40/45] net/mlx5: Fix compilation warning in eq.c
Bugzilla: 1691238
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691238
Upstream: net-next/master

commit 092ead48290b43afe5d548797c73b179dbaf6523
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Thu Mar 21 15:51:31 2019 -0700

    net/mlx5: Fix compilation warning in eq.c

    mlx5_eq_table_get_rmap is being used only when CONFIG_RFS_ACCEL is
    enabled, this patch fixes the below warning when CONFIG_RFS_ACCEL is
    disabled.

    drivers/.../mlx5/core/eq.c:903:18: [-Werror=missing-prototypes]
    error: no previous prototype for ‘mlx5_eq_table_get_rmap’

    Fixes: f2f3df550139 ("net/mlx5: EQ, Privatize eq_table and friends")
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>