tools: Sharpen the libaudit dependencies test
Patchwork-id: 80763
O-Subject: [PATCH RHEL6.6 BZ1101039 198/233] perf tools: Sharpen the libaudit dependencies test
Bugzilla: 1101039
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

[perf] tools: Sharpen the libaudit dependencies test

Message-id: <1401193895-15711-199-git-send-email-jolsa@redhat.com>
Patchwork-id: 80763
O-Subject: [PATCH RHEL6.6 BZ1101039 198/233] perf tools: Sharpen the libaudit dependencies test
Bugzilla: 1101039

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1101039
https://bugzilla.redhat.com/show_bug.cgi?id=1101039

upstream
========
commit 33cbbdccf39f6d7e01c282c4320d818a75b67d54
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Sep 12 15:27:06 2013 +0200

description
===========
There are older libaudit versions that don't have an
audit_errno_to_name() method, resulting in a builtin-trace.c build
error:

  builtin-trace.c: In function 'trace__sys_exit':
  builtin-trace.c:794: warning: implicit declaration of function 'audit_errno_to_name'

Expand the libaudit test to detect this.

[ Fix the test by escaping the double quotes ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>