lpfc: Use %zd format string for size_t
Message-id: <1485886737-16352-42-git-send-email-revers@redhat.com>
Patchwork-id: 164451
O-Subject: [RHEL7.4 e-stor PATCH 41/56] scsi: lpfc: Use %zd format string for size_t
Bugzilla: 1382101
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Maurizio Lombardi <mlombard@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

A recent bugfix introduced a harmless warning in the lpfc driver:

drivers/scsi/lpfc/lpfc_init.c: In function 'lpfc_write_firmware':
drivers/scsi/lpfc/lpfc_logmsg.h:56:45: error: format '%ld' expects argument of type 'long int', but argument 9 has type 'size_t {aka const unsigned int}' [-Werror=format=]

'size_t' is always the same width as 'long' in the kernel, but the
compiler doesn't know that. The %z modifier is what the standard expects
to be used here, and this shuts up the warning.

Fixes: 679053c651fb ("scsi: lpfc: Fix fw download on SLI-4 FC adapters")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
Acked-by: James Smart <james.smart@broadcom.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit efe583c6d3cdafbeb0c039cd5d0f88fd26637065)
Signed-off-by: Rob Evers <revers@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>