tools: Fix LIBNUMA build with glibc 2.12 and older
Patchwork-id: 71409
O-Subject: [PATCH RHEL6.6 BZ1034843 172/172] perf tools: Fix LIBNUMA build with glibc 2.12 and older.
Bugzilla: 1034843
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: 1034843
https://bugzilla.redhat.com/show_bug.cgi?id=1034843

upstream
========
commit d1398ccfec56e54010476efd6a316427d29045a6
Author: Vinson Lee <vlee@twitter.com>
Date: Wed Mar 13 15:34:24 2013 -0700

description
===========
The tokens MADV_HUGEPAGE and MADV_NOHUGEPAGE are not available with
glibc 2.12 and older. Define these tokens if they are not already
defined.

This patch fixes these build errors with older versions of glibc.

    CC bench/numa.o
bench/numa.c: In function 'alloc_data':
bench/numa.c:334: error: 'MADV_HUGEPAGE' undeclared (first use in this function)
bench/numa.c:334: error: (Each undeclared identifier is reported only once
bench/numa.c:334: error: for each function it appears in.)
bench/numa.c:341: error: 'MADV_NOHUGEPAGE' undeclared (first use in this function)
make: *** [bench/numa.o] Error 1

Signed-off-by: Rafael Aquini <aquini@redhat.com>