perf, stat: handle ENXIO error for perf_event_open
Patchwork-id: 48087
O-Subject: [PATCH RHEL6.4 BZ827474 118/122] perf stat: handle ENXIO error for perf_event_open
Bugzilla: 827474
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 827474
https://bugzilla.redhat.com/show_bug.cgi?id=827474

upstream status
===============
commit 20d23aaa31da295378abff4272716e3dfc72baf0
Author: David Ahern <dsahern@gmail.com>
Date:   Tue May 8 09:29:16 2012 -0600

description
===========
perf stat on PPC currently fails to run:

$ perf stat -- sleep 1
  Error: open_counter returned with 6 (No such device or address). /bin/dmesg may provide additional information.

  Fatal: Not all events could be opened.

The problem is that until 2.6.37 (behavior changed with commit b0a873e)
perf on PPC returns ENXIO when hw_perf_event_init() fails. With this
patch we get the expected behavior:

$ perf stat -v -- sleep 1
cycles event is not supported by the kernel.
stalled-cycles-frontend event is not supported by the kernel.
stalled-cycles-backend event is not supported by the kernel.
instructions event is not supported by the kernel.
branches event is not supported by the kernel.
branch-misses event is not supported by the kernel.

...