ipv6: Return error for RTA_VIA attribute
Message-id: <0e668cc0b581aba9c7f25a7e6975f62a3e8652eb.1559966963.git.sbrivio@redhat.com>
Patchwork-id: 263854
O-Subject: [RHEL8.1 net 37/59] ipv6: Return error for RTA_VIA attribute
Bugzilla: 1718503
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1718503
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22066353
Tested: commands from commit message, net/fib_tests.sh and net/pmtu.sh
	upstream selftests with KASan and lockdep debugging, CKI networking tests

commit e3818541b49fb88650ba339d33cc53e4095da5b3
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Feb 26 09:00:03 2019 -0800

    ipv6: Return error for RTA_VIA attribute

    IPv6 currently does not support nexthops outside of the AF_INET6 family.
    Specifically, it does not handle RTA_VIA attribute. If it is passed
    in a route add request, the actual route added only uses the device
    which is clearly not what the user intended:

      $ ip -6 ro add 2001:db8:2::/64 via inet 172.16.1.1 dev eth0
      $ ip ro ls
      ...
      2001:db8:2::/64 dev eth0 metric 1024 pref medium

    Catch this and fail the route add:
      $ ip -6 ro add 2001:db8:2::/64 via inet 172.16.1.1 dev eth0
      Error: IPv6 does not support RTA_VIA attribute.

    Fixes: 03c0566542f4c ("mpls: Netlink commands to add, remove, and dump routes")
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>