mlx4_en: fix a build error on 32bit arches
Patchwork-id: 64115
O-Subject: [RHEL 6.5 PATCH 089/129] mlx4_en: fix a build error on 32bit arches
Bugzilla: 950401 950910 950913 950915
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Doug Ledford <dledford@redhat.com>

From: Eric Dumazet <edumazet@google.com>

commit b6c39bfcf1d7d63 ("net/mlx4_en: Add a service task")
added a build error on 32bit arches.

ERROR: "__udivdi3" [drivers/net/ethernet/mellanox/mlx4/mlx4_en.ko]
undefined!

Fix this problem by using do_div()

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Eric Dumazet <edumazet@google.com>
Acked-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Amir Vadai <amirv@mellanox.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit fe86d714168f1567989c309f73a3550022686301)

Signed-off-by: Amir Vadai <avadai@redhat.com>