ext4: fix compile error when using BUFFER_TRACE
Message-id: <20190517091449.6738-63-lczerner@redhat.com>
Patchwork-id: 256585
O-Subject: [RHEL8.1 fs PATCH 62/89] ext4: fix compile error when using BUFFER_TRACE
Bugzilla: 1698815
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>
RH-Acked-by: Bill O'Donnell <billodo@redhat.com>

From: "zhangyi (F)" <yi.zhang@huawei.com>

BZ 1698815
https://bugzilla.redhat.com/show_bug.cgi?id=1698815

BREW 21544584
https://brewweb.devel.redhat.com/taskinfo?taskID=21544584

commit ddccb6dbe780d68133191477571cb7c69e17bb8c

Fix compile error below when using BUFFER_TRACE.

fs/ext4/inode.c: In function ‘ext4_expand_extra_isize’:
fs/ext4/inode.c:5979:19: error: request for member ‘bh’ in something not a structure or union
  BUFFER_TRACE(iloc.bh, "get_write_access");

Fixes: c03b45b853f58 ("ext4, project: expand inode extra size if possible")
Signed-off-by: zhangyi (F) <yi.zhang@huawei.com>
Signed-off-by: Theodore Ts'o <tytso@mit.edu>
Reviewed-by: Jan Kara <jack@suse.cz>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>