robe: Fix compiles due to declarations using perf_probe_point
Patchwork-id: 129242
O-Subject: [PATCH RHEL6 BZ1291071 164/315] perf probe: Fix compiles due to declarations using perf_probe_point
Bugzilla: 1291071
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1291071
https://bugzilla.redhat.com/show_bug.cgi?id=1291071

upstream
========
commit 6d4a48968bfb5c67002f253fbaeb5acd41d7897a
Author: David Ahern <david.ahern@oracle.com>
Date: Wed Mar 11 10:36:20 2015 -0400

description
===========
perf fails to build with gcc "(GCC) 4.4.7 20120313 (Red Hat
4.4.7-4.0.9)" (a.k.a., RHEL6 / CentOS 6 / OL 6):

  cc1: warnings being treated as errors
  util/probe-event.c: In function 'get_alternative_line_range':
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for 'pp.file')
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for 'result.function')

Fix by bringing in initializers to declaration.

Signed-off-by: Aristeu Rozanski <aris@redhat.com>