x86/speculation: Cast ~SPEC_CTRL_STIBP atomic value to int
Message-id: <20190524150236.14634-4-longman@redhat.com>
Patchwork-id: 260767
O-Subject: [RHEL8.1 PATCH 03/31] x86/speculation: Cast ~SPEC_CTRL_STIBP atomic value to int
Bugzilla: 1713695 1690360 1690351 1690338
CVE: CVE-2018-12126 CVE-2018-12127 CVE-2018-12130 CVE-2019-11091
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Josh Poimboeuf <jpoimboe@redhat.com>

From: Josh Poimboeuf <jpoimboe@redhat.com>

Bugzilla: 1690338 1690351 1690360 1713695
CVE: CVE-2018-12126 CVE-2018-12130 CVE-2018-12127 CVE-2019-11091
Upstream status: RHEL only

Prepare for an upcoming patch, in which the SPEC_CTRL_STIBP macro is
going to be converted to unsigned long, by way of the BIT() macro.

This fixes the following warning:

arch/x86/kernel/spec_ctrl.c: In function 'atomic_update_stibp_pcp':
arch/x86/kernel/spec_ctrl.c:228:14: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '18446744073709551613' to '-3' [-Werror=overflow]
   atomic_and(~SPEC_CTRL_STIBP, pval);

Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>