toshiba-acpi: make one-bit bitfields unsigned
Patchwork-id: 103172
O-Subject: [RHEL6.7 PATCH 16/21] toshiba_acpi: make one-bit bitfields unsigned
Bugzilla: 1146711
RH-Acked-by: Aristeu S. Rozanski F. <arozansk@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1146711
Upstream: since v3.4
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=8550748
Tested by me on a Toshiba Tecra W50-A

commit 592b746c55b63770da25148ea3b56ed463a596b2
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Sun Jan 15 14:28:20 2012 +0300

    toshiba_acpi: make one-bit bitfields unsigned

    This doesn't change how the code works, but it silences a Sparse
    complaint:
    drivers/platform/x86/toshiba_acpi.c:121:37: error: dubious one-bit signed bitfield

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Matthew Garrett <mjg@redhat.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>