dm-cache: avoid 64 bit division on 32 bit
Patchwork-id: 78226
O-Subject: [RHEL6.6 PATCH 042/110] dm cache: avoid 64 bit division on 32 bit
Bugzilla: 1038227
RH-Acked-by: Joe Thornber <thornber@redhat.com>
RH-Acked-by: Heinz Mauelshagen <heinzm@redhat.com>

BZ: 1038227

Upstream commit 414dd67d50a6b9a11af23bbb68e8fae13d726c8b
Author: Joe Thornber <ejt@redhat.com>
Date:   Wed Mar 20 17:21:25 2013 +0000

    dm cache: avoid 64 bit division on 32 bit

    Squash various 32bit link errors.

      >> on i386:
      >> drivers/built-in.o: In function `is_discarded_oblock':
      >> dm-cache-target.c:(.text+0x1ea28e): undefined reference to `__udivdi3'
      ...

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Joe Thornber <ejt@redhat.com>
    Signed-off-by: Alasdair G Kergon <agk@redhat.com>