perf probe: Use %td for pointer arithmetic result
Patchwork-id: 36499
O-Subject: [PATCH RHEL6.2 BZ691343 047/142] perf probe: Use %td for pointer arithmetic result
Bugzilla: 691343
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 691343
https://bugzilla.redhat.com/show_bug.cgi?id=691343

upstream status
---------------
commit 823c7164a92a6347d46bb64aaae728b6d08f3bb8
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Mon Jan 31 19:45:38 2011 -0200

description
-----------
%td is for ptrdiff_t, avoiding this warning on 32-bit:

cc1: warnings being treated as errors
builtin-probe.c: In function ‘opt_set_filter’:
builtin-probe.c:176:4: error: format ‘%ld’ expects type ‘long int’, but
argument 3 has type ‘int’

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>