Fix warning in include/trace/events/kmem.h: mm_kswapd_ran()
Patchwork-id: 26171
O-Subject: [RHEL6 PATCH BZ 603733 47/59] Fix warning in
	include/trace/events/kmem.h: mm_kswapd_ran()
Bugzilla: 603733
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Fixes

In file included from include/linux/kmemtrace.h:12,
                 from kernel/trace/kmemtrace.c:15:
include/trace/events/kmem.h:621: error: 'struct pglist_data' declared inside parameter list
include/trace/events/kmem.h:621: error: its scope is only this definition or declaration, which is probably not what you want
include/trace/events/kmem.h:621: error: 'struct pglist_data' declared inside parameter list
include/trace/events/kmem.h:621: error: 'struct pglist_data' declared inside parameter list

(found during move to 2.6.32-33.el6)

Code is not upstream.

RHEL6 only.

Resolves BZ 603733.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>