RDMA: Fix building with CONFIG_MMU=n
Message-id: <96786438583d463a59365db3e9a567c7cd534dd5.1555364289.git.jtoppins@redhat.com>
Patchwork-id: 250038
O-Subject: [PATCH RDMAv4.20 RHEL-8.1 v2 064/139] RDMA: Fix building with CONFIG_MMU=n
Bugzilla: 1685307
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The zap_vma_ptes() is declared but not defined on NOMMU kernels, causing a
link error for the newly added uverbs code:

drivers/infiniband/core/uverbs_main.o: In function `uverbs_user_mmap_disassociate':
uverbs_main.c:(.text+0x114c): undefined reference to `zap_vma_ptes'
drivers/infiniband/core/uverbs_main.o: In function `rdma_umap_open':
uverbs_main.c:(.text+0x53c): undefined reference to `zap_vma_ptes'

Since all user access for all of our drivers depend on remapping pages to
user space disable USER_ACCESS when there is no mmu.

Fixes: 5f9794dc94f5 ("RDMA/ucontext: Add a core API for mmaping driver IO memory")
Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 914e5d7d4697fb9815fa237a4d42bfb952bf48d6)
Bugzilla: 1685307
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20935439
Tested: standard RDMA test suite along with partner testing
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>