tools: lib: traceevent: Handle INVALID_ARG_TYPE errno in pevent_strerror
Patchwork-id: 101918
O-Subject: [PATCH RHEL6.7 BZ1172076 159/313] tools lib traceevent: Handle INVALID_ARG_TYPE errno in pevent_strerror
Bugzilla: 1172076
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1172076
https://bugzilla.redhat.com/show_bug.cgi?id=1172076

upstream
========
commit 7a905611644c015e68a955f263fd0a4b7b20879d
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Fri Nov 9 15:50:33 2012 -0300

description
===========
gcc on f14 32-bit rightly complains:

   tools/lib/traceevent/event-parse.c:5097:2: error: enumeration value PEVENT_ERRNO__INVALID_ARG_TYPE not handled in switch

The entry for it is in the error strings array pevent_error_str[]:

        _PE(INVALID_ARG_TYPE,   "invalid argument type")

It was just not being handled on the pevent_strerror switch, fix it.

Signed-off-by: Rafael Aquini <aquini@redhat.com>