mpls: Implement handler for strict data checking on dumps
Message-id: <dcd5b3dbaba914677cf569de13adb88c831976a0.1558525681.git.poros@redhat.com>
Patchwork-id: 259380
O-Subject: [RHEL8.1 net PATCH 41/48] net/mpls: Implement handler for strict data checking on dumps
Bugzilla: 1700306
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1700306

Upstream commit(s):
commit d8a66aa25405e4e3015e4e4e856ef716585d59df
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Oct 9 11:10:43 2018 -0700

    net/mpls: Implement handler for strict data checking on dumps

    Without CONFIG_INET enabled compiles fail with:

    net/mpls/af_mpls.o: In function `mpls_dump_routes':
    af_mpls.c:(.text+0xed0): undefined reference to `ip_valid_fib_dump_req'

    The preference is for MPLS to use the same handler as ipv4 and ipv6
    to allow consistency when doing a dump for AF_UNSPEC which walks
    all address families invoking the route dump handler. If INET is
    disabled then fallback to an MPLS version which can be tighter on
    the data checks.

    Fixes: e8ba330ac0c5 ("rtnetlink: Update fib dumps for strict data checking")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>