mlx5: Add MLX5_ARRAY_SET64 to fix BUILD_BUG_ON
Message-id: <1487828466-9959-246-git-send-email-ddutile@redhat.com>
Patchwork-id: 167283
O-Subject: [PATCH RHEL-7.4 245/348] net/mlx5: Add MLX5_ARRAY_SET64 to fix BUILD_BUG_ON
Bugzilla: 1385330 1417285
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417285
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385330

commit b8a4ddb2e8f44f872fb93bbda2d541b27079fd2b
Author: Tom Herbert <tom@herbertland.com>
Date:   Wed Oct 12 04:57:10 2016 +0300

    net/mlx5: Add MLX5_ARRAY_SET64 to fix BUILD_BUG_ON

    I am hitting this in mlx5:

    drivers/net/ethernet/mellanox/mlx5/core/pagealloc.c: In function
    reclaim_pages_cmd.clone.0:
    drivers/net/ethernet/mellanox/mlx5/core/pagealloc.c:346: error: call
    to __compiletime_assert_346 declared with attribute error:
    BUILD_BUG_ON failed: __mlx5_bit_off(manage_pages_out, pas[i]) % 64
    drivers/net/ethernet/mellanox/mlx5/core/pagealloc.c: In function give_pages:
    drivers/net/ethernet/mellanox/mlx5/core/pagealloc.c:291: error: call
    to __compiletime_assert_291 declared with attribute error:
    BUILD_BUG_ON failed: __mlx5_bit_off(manage_pages_in, pas[i]) % 64

    Problem is that this is doing a BUILD_BUG_ON on a non-constant
    expression because of trying to take offset of pas[i] in the
    structure.

    Fix is to create MLX5_ARRAY_SET64 that takes an additional argument
    that is the field index to separate between BUILD_BUG_ON on the array
    constant field and the indexed field to assign the value to.
    There are two callers of MLX5_SET64 that are trying to get a variable
    offset, change those to call MLX5_ARRAY_SET64 passing 'pas' and 'i'
    as the arguments to use in the offset check and the indexed value
    assignment.

    Fixes: a533ed5e179cd ("net/mlx5: Pages management commands via mlx5 ifc")
    Signed-off-by: Tom Herbert <tom@herbertland.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>