netxen: Sync with upstream kernel bug fixes
Patchwork-id: 23641
O-Subject: [RHEL6.0 PATCH 1/2] Sync with upstream kernel bug fixes
Bugzilla: 516840
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

commit 8f9b3f69944ab7eacb9273b4723087c42b5f4046
Author: Amit Kumar Salecha <amit@unm84.unmin.com>
Date:   Wed Dec 2 15:46:19 2009 +0000

    netxen: fix failure cases for fw hang recovery

    Handle few corner cases in firmware hang detection and recovery:

    o Don't mark device state as READY, till handshake with
      firmware is done.
    o During probe, if start_firmware fails, restore reference
      count.
    o Don't increment refernce count, if start_firmware fails
      during firmware reset.
    o Clear __NX_RESETTING bit, incase of fatal error or tempeature
      reaches critical limit so that pci remove() doesn't poll on
      this bit.

    Signed-off-by: Amit Kumar Salecha <amit.salecha@qlogic.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit f58dbd7320e148b25cc0088ef37f524c99c6790f
Author: Narender Kumar <narender.kumar@qlogic.com>
Date:   Wed Dec 2 15:46:18 2009 +0000

    netxen : fix debug tools access for NX2031

    Driver maps only some part of the MMIO bar 0 in case of
    NX2031. This is sufficient for tx and rx by the driver.
    When debug tools need to access resources in
    unmapped regions, driver needs to map these on the fly
    in order to complete read/write request.

    Signed-off-by: Narender Kumar <narender.kumar@qlogic.com>
    Signed-off-by: Dhananjay Phadke <dhananjay.phadke@qlogic.com>
    Signed-off-by: Amit Kumar Salecha <amit.salecha@qlogic.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit eb6d02133cf5451fece3a37ccccf2ce7c09a09c1
Author: Amit Kumar Salecha <amit.salecha@qlogic.com>
Date:   Thu Nov 19 15:08:12 2009 +0000

    netxen: remove PCI IDs of CNA device

    Remove PCI vendor and device IDs for QLE8240 and QLE8242
    CNA devices. CNA devices will have separate driver.

    Signed-off-by: Amit Kumar Salecha <amit.salecha@qlogic.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit c70948105d4f057b90d4a587246565782e51ed35
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Sat Oct 24 16:04:03 2009 +0000

    netxen: update version to 4.0.65

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 7e8e5d9718744b817bfea6f020586d7035cc89f4
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Sat Oct 24 16:04:02 2009 +0000

    netxen: module firmware hints

    Add MODULE_FIRMWARE hints for various firmware file types,
    required by different chip revisions.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit c25c0b9b33f681972e0b2abc96b9debdd1ef32a5
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Wed Oct 28 04:11:04 2009 -0700

    netxen: update module info

    Update module info with QLogic signature.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit f0e08fac06596a760f074c08521550d93b96336e
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Sat Oct 24 16:04:00 2009 +0000

    netxen: add PCI IDs for new chip

    Add PCI vendor and device IDs for QLE8240 and QLE8242
    CNA devices.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit a9ac07deeb4b880aea3eaccf7ec913ac902aeef9
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Sat Oct 24 16:03:59 2009 +0000

    netxen: refactor indirect register access

    Refactor code to calculate and set indirect access
    window for control registers in 2MB address space
    (NX3031 or newer). Use void __iomem * data type for
    absolute pci addresses.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit f50330f90b9aa42b7058650ce66b85f1b443ab11
Author: Amit Kumar Salecha <amit@netxen.com>
Date:   Sat Oct 24 16:03:58 2009 +0000

    netxen: support for new firmware file format

    Add support for extracting firmware from a unified
    file format which embeds firmware images for all chip
    revisions. Fallback to orginal file formats if new
    image is not found.

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 0531d7b85177cda05f574ddf0aa4b25050159101
Author: Randy Dunlap <randy.dunlap@oracle.com>
Date:   Mon Oct 26 12:09:45 2009 +0000

    netxen: fix builds for SYSFS=n or MODULES=n

    When CONFIG_MODULES=n:
    drivers/net/netxen/netxen_nic_main.c:2751: error: dereferencing pointer to incomplete type
    drivers/net/netxen/netxen_nic_main.c:2764: error: dereferencing pointer to incomplete type

    Also needs addition of <linux/sysfs.h> for sysfs function prototypes or
    stubs when CONFIG_SYSFS=n.

    Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
    Acked-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 7194660da7a6d119fa469bd11b58e7367a5cbdf4
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Fri Oct 16 15:50:12 2009 +0000

    netxen; update version to 4.0.62

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit caa2dd53bc2f9c44938f2f261ebe15e2f26cc51e
Author: Narender Kumar <narender.kumar@qlogic.com>
Date:   Fri Oct 16 15:50:11 2009 +0000

    netxen: sysfs control for auto firmware recovery

    Firmware hang detection and recovery (reset) need to
    be disabled for diagnostic tools, which can run
    some disruptive tests.

    This adds a driver level control to turn off this
    feature by diag tools.

    Signed-off-by: Narender Kumar <narender.kumar@qlogic.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 7cecdca133ea9791adce21819b9e9eed79045f23
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Fri Oct 16 15:50:10 2009 +0000

    netxen: fix error codes in for tools access

    Use -EIO or -EINVAL as error codes, these can get passed up
    to applications (tools).

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 6abb4b83eac25d91f6de834e97b2ea38e979575b
Author: Amit Kumar Salecha <amit@netxen.com>
Date:   Fri Oct 16 15:50:09 2009 +0000

    netxen: onchip memory access change

    Add support for different windowing scheme for on chip
    memory in future chip revisions. This is required by
    diagnostic tools.

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 0be367bd5d10634c0836f57a684432fee935d929
Author: Amit Kumar Salecha <amit@qlogic.com>
Date:   Fri Oct 16 15:50:08 2009 +0000

    netxen: reset sequence changes

    Future revisions need different chip reset sequence
    and firmware initialization.

    Also clean up some never used debug code.

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit fb1f6a4378fe211d8c1397311d26e747e5ec61c5
Author: Amit Kumar Salecha <amit@qlogic.com>
Date:   Fri Oct 16 15:50:07 2009 +0000

    netxen: 128 memory controller support

    Future revisions of the chip have 128 bit memory
    transactions. Require drivers to implement rmw
    in case of sub-128 bit accesses by driver. This
    is mostly used by diagnostic tools.

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 0a2aa440603f27ad40bcc14806f4d87aabbd8a0f
Author: Amit Kumar Salecha <amit@qlogic.com>
Date:   Fri Oct 16 15:50:06 2009 +0000

    netxen: defines for next revision

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 70f9cf8951e5253cfef821f8dcb92f6fc3af50c6
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Tue Oct 13 05:31:45 2009 +0000

    netxen: add sysfs entries for diag tools

    Add sysfs entries to enable register and memory access
    for diagnostic tools.

    Signed-off-by: Narender Kumar <narender.kumar@qlogic.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit f03b0ebd8e7132bd9adb41348070813feb280300
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Tue Oct 13 05:31:44 2009 +0000

    netxen: separate register and memory access lock

    Since register and onboard memory access has separate
    window registers, they need not be kept under same lock.

    Also, memory is always accessed from process context
    (mostly for firmware init and diagnostic tools).

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 907fa1201c76f426a13bdff5be2747fb62c2353f
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Tue Oct 13 05:31:43 2009 +0000

    netxen: annotate register windowing code

    Use common variables crb_win, ocm_win for all revisions of chip.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 47abe35610cbbfb3cc92847efdf588a8be1f5ebc
Author: Dhananjay Phadke <dhananjay@netxen.com>
Date:   Tue Oct 13 05:31:42 2009 +0000

    netxen: add access to on chip memory for tools

    Add access to on chip memory, this is used by
    debug and diagnostic tools only.

    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 1f5e055db369a5d1c74174571585a4ec2e6c40fb
Author: Amit Kumar Salecha <amit@netxen.com>
Date:   Tue Oct 13 05:31:41 2009 +0000

    netxen: remove sub 64-bit mem accesses

    Sub 64-bit / unaligned access to oncard memory was only used
    by old diagnostic tools, causes some intermittent issues when
    memory controller agent is used.  The new access method was
    added by commit ea6828b8aa3a8ebae8d7740f32f212ba1d2f0742
    ("netxen: improve pci memory access").  Firmware init anyway
    uses 8-byte strides.

    This also fixes address/offset calculation for NX2031 context
    memory (SIU). For NX3031, SIU uses same register offsets
    as packet memory (MIU).

    Signed-off-by: Amit Kumar Salecha <amit@netxen.com>
    Signed-off-by: Dhananjay Phadke <dhananjay@netxen.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 5a4d631154de41bb43eefb03d2124224c23c1fa4
Author: Ajit Khaparde <ajitkhaparde@gmail.com>
Date:   Wed Oct 7 02:45:34 2009 +0000

    netxen: Use the instance of net_device_stats from net_device.

    Since net_device has an instance of net_device_stats,
    we can remove the instance of this from the private adapter structure.

    Signed-off-by: Ajit Khaparde <ajitk@serverengines.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>