perf trace: Add getrandom beautifier related defines for older systems
Message-id: <1474556776-20705-44-git-send-email-jolsa@redhat.com>
Patchwork-id: 158111
O-Subject: [PATCH RHEL7.3 BZ1373817 043/252] perf trace: Add getrandom beautifier related defines for older systems
Bugzilla: 1373817
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1373817
https://bugzilla.redhat.com/show_bug.cgi?id=1373817

upstream
========
commit a355a61e43484ac02553b34b5f84ee84ca765fd6
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Apr 13 11:55:18 2016 -0300

description
===========
Were the detached tarball (make perf-tar-src-pkg) build was failing because
those definitions aren't available in the system headers.

On RHEL7, for instance:

  builtin-trace.c: In function syscall_arg__scnprintf_getrandom_flags:
  builtin-trace.c:1113:14: error: GRND_RANDOM undeclared (first use in this function)
    P_FLAG(RANDOM);
                ^
  builtin-trace.c:1114:14: error: GRND_NONBLOCK undeclared (first use in this function)
    P_FLAG(NONBLOCK);
              ^

Signed-off-by: Rafael Aquini <aquini@redhat.com>