tests: Fix compile failure on do_sort_something
Patchwork-id: 80760
O-Subject: [PATCH RHEL6.6 BZ1101039 142/233] perf tests: Fix compile failure on do_sort_something
Bugzilla: 1101039
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

[perf] tests: Fix compile failure on do_sort_something

Message-id: <1401193895-15711-143-git-send-email-jolsa@redhat.com>
Patchwork-id: 80760
O-Subject: [PATCH RHEL6.6 BZ1101039 142/233] perf tests: Fix compile failure on do_sort_something
Bugzilla: 1101039

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1101039
https://bugzilla.redhat.com/show_bug.cgi?id=1101039

upstream
========
commit 309b5185047c5309bbc576025f6c5e257edd9f69
Author: David Ahern <dsahern@gmail.com>
Date: Tue Aug 13 22:32:12 2013 -0600

description
===========
Commit b55ae0a9 added code-reading.c which fails to compile on Fedora 16
with compiler version:
$ gcc --version
gcc (GCC) 4.6.3 20120306 (Red Hat 4.6.3-2)

Failure message is:

tests/code-reading.c: In function 'do_sort_something':
tests/code-reading.c:305:13: error: stack protector not protecting local variables: variable length buffer [-Werror=stack-protector]
cc1: all warnings being treated as errors
make: *** [/tmp/junk/tests/code-reading.o] Error 1
make: *** Waiting for unfinished jobs....

v2: as Adrian noticed changed sizeof to ARRAY_SIZE
Signed-off-by: Rafael Aquini <aquini@redhat.com>