i915: fix build for CONFIG_BUG=n
Patchwork-id: 108037
O-Subject: [RHEL6 drm 43/45] drm/i915: fix build for CONFIG_BUG=n
Bugzilla: 1200563
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Upstream: 3.19-rc5
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1200563

commit 2f3408c7ef471dea10b8c89932f581c9c2eaf6ef

Author:     Jani Nikula <jani.nikula@intel.com>
AuthorDate: Mon Jan 12 15:45:31 2015 +0200
Commit:     Daniel Vetter <daniel.vetter@ffwll.ch>
CommitDate: Mon Jan 12 23:43:09 2015 +0100

    drm/i915: fix build for CONFIG_BUG=n

    If CONFIG_BUG=n __WARN_printf won't be defined leading to the below
    build failure. The double underscores should have told us to steer clear
    of it anyway.

    drivers/gpu/drm/i915/intel_display.c: In function assert_pll:
    drivers/gpu/drm/i915/intel_display.c:1027:2: error: implicit declaration
    of function __WARN_printf [-Werror=implicit-function-declaration]
      I915_STATE_WARN(cur_state != state,

    Use WARN(1, ...) instead. It handles CONFIG_BUG=n gracefully and, with
    the constant condition, a sane compiler should reduce it to
    __WARN_printf.

    This is a regression introduced by

    commit e2c719b75c8c186deb86570d8466df9e9eff919b
    Author: Rob Clark <robdclark@gmail.com>
    Date:   Mon Dec 15 13:56:32 2014 -0500

        drm/i915: tame the chattermouth (v2)

    Reported-by: Jim Davis <jim.epost@gmail.com>
    Reference: http://mid.gmane.org/CA+r1ZhgHTi7bS2irhtuSUs9aO=Br1dumN8=oAOeaMJDZ_ZhwBw@mail.gmail.com
    Cc: Rob Clark <robdclark@gmail.com>
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>