perf/python: Properly link with libtraceevent
Patchwork-id: 58086
O-Subject: [PATCH RHEL6.5 BZ927866 256/264] perf python: Properly link with libtraceevent
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Arnaldo Carvalho de Melo <acme@infradead.org>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit 45bff41a9a6f22af28e4ba22f83c87f619e573a8
Author: Arnaldo Carvalho de Melo <acme@infradead.org>
Date:   Thu Oct 18 11:38:35 2012 -0300

description
===========
Namhyung Kim reported that the build fails with:

  GEN python/perf.so
  gcc: error: python_ext_build/tmp//../../libtraceevent.a: No such file or directory
  error: command 'gcc' failed with exit status 1
  cp: cannot stat `python_ext_build/lib/perf.so': No such file or directory
  make: *** [python/perf.so] Error 1

We need to propagate the TE_PATH variable to the setup.py file.

[ Fixed superfluous variable build error. ]