fix build with localmodconfig
Patchwork-id: 79992
O-Subject: [RHEL6.6 PATCH] fix build with localmodconfig
Bugzilla: 1098559
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1098559

Trying to do a quick build of a RHEL6 kernel for developer testing with
only a minimal set of modules fails:

    $ cp configs/kernel-2.6.32-x86_64.config .config
    $ make localmodconfig
    [...]
    $ make -j12
    [...]
    ERROR: "list_sort" [fs/gfs2/gfs2.ko] undefined!
    ERROR: "list_sort" [drivers/gpu/drm/drm.ko] undefined!
    make[1]: *** [__modpost] Error 1

list_sort is implemented in lib/list_sort.c, but its building is
conditional on CONFIG_LIST_SORT. As seen from the error, not all users
have the necessary 'select LIST_SORT' dependency expressed in Kconfig
files.

This bug does not affect official builds, because our configurations
always have ubifs enabled (which in turn pulls in list_sort by a Kconfig
dependency). However it is annoying for me as a developer when trying to
git bisect bugs.

Upstream resolved this by building list_sort unconditionally and
removing CONFIG_LIST_SORT entirely.

Upstream commit:
commit b8fa05719ba4349be80ce929237249b57886a203
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Mar 7 09:54:44 2010 -0800

    Revert "lib: build list_sort() only if needed"

    This reverts commit a069c266ae5fdfbf5b4aecf2c672413aa33b2504.

    It turns ou that not only was it missing a case (XFS) that needed it,
    but perhaps more importantly, people sometimes want to enable new
    modules that they hadn't had enabled before, and if such a module uses
    list_sort(), it can't easily be inserted any more.

    So rather than add a "select LIST_SORT" to the XFS case, just leave it
    compiled in.  It's not all _that_ big, after all, and the inconvenience
    isn't worth it.

    Requested-by: Alexey Dobriyan <adobriyan@gmail.com>
    Cc: Christoph Hellwig <hch@infradead.org>
    Cc: Don Mullis <don.mullis@gmail.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Dave Chinner <david@fromorbit.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Conflicts:
	drivers/gpu/drm/Kconfig
	lib/Kconfig
	lib/Makefile

No redhat/configs/config-* changes are necessary.

Brew build:
https://brewweb.devel.redhat.com/taskinfo?taskID=7465945

Testing:
I booted the Brew build. I compared the file lists of the RPMs to those
of an unpatched official build to make sure no modules were lost or
added. And I did a successful local build with localmodconfig.

Signed-off-by: Rafael Aquini <aquini@redhat.com>