IB/ipath: Add missing <linux/stat.h> in ipath_chip_init.c
Patchwork-id: 45246
O-Subject: [Patch RHEL6 079/216] IB/ipath: Add missing <linux/stat.h> in
	ipath_chip_init.c
Bugzilla: 738491 739139 749059 755741
RH-Acked-by: John Feeney <jfeeney@redhat.com>

From: Randy Dunlap <rdunlap@xenotime.net>

Fix build errors:

    drivers/infiniband/hw/ipath/ipath_init_chip.c:54:1: error: 'S_IRUGO' undeclared here (not in a function)
    drivers/infiniband/hw/ipath/ipath_init_chip.c:54:1: error: bit-field '<anonymous>' width not an integer constant
    drivers/infiniband/hw/ipath/ipath_init_chip.c:67:1: error: 'S_IWUSR' undeclared here (not in a function)
    drivers/infiniband/hw/ipath/ipath_init_chip.c:67:1: error: bit-field '<anonymous>' width not an integer constant

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit 3e60a77ea218d1915bdc9127f88ab866fd2ac643)

Conflicts:

	drivers/infiniband/hw/ipath/ipath_init_chip.c

Signed-off-by: Doug Ledford <dledford@redhat.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>