ping: fix build failure
Patchwork-id: 45404
O-Subject: [patch rhel6 04/11] net: ping: fix build failure
Bugzilla: 787705
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ787705

upstream commit f56e03e8dc149bf0ac2888d6843584f48c8700fc
Author: Vasiliy Kulikov <segoon@openwall.com>
Date:   Tue May 17 00:16:56 2011 +0000

    net: ping: fix build failure

    If CONFIG_PROC_SYSCTL=n the building process fails:

        ping.c:(.text+0x52af3): undefined reference to `inet_get_ping_group_range_net'

    Moved inet_get_ping_group_range_net() to ping.c.

Signed-off-by: Jiri Pirko <jpirko@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>