rcu: make SRCU usable in modules
Patchwork-id: 104295
O-Subject: [RHEL6 drm 12/55] rcu: make SRCU usable in modules
Bugzilla: 1170246
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Ben Skeggs <bskeggs@redhat.com>

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1170246
Upstream: since v2.6.35

commit d14aada8e20bdf81ffd43f433b123972cf575b32

Author:     Paul E. McKenney <paulmck@linux.vnet.ibm.com>
AuthorDate: Mon Apr 19 22:24:22 2010 -0700
Commit:     Rob Clark <rclark@redhat.com>
CommitDate: Tue Jan 20 14:06:52 2015 -0500

    rcu: make SRCU usable in modules

    Add a #include for mutex.h to allow SRCU to be more easily used in
    kernel modules.

    Signed-off-by: Lai Jiangshan <laijs@cn.fujitsu.com>
    Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>

Note that this is required to fix an mmu-notifier build error on ppc64:

  In file included from include/linux/mmu_notifier.h:7,
                   from mm/mmu_notifier.c:13:
  include/linux/srcu.h:37: error: field 'mutex' has incomplete type
  make[1]: *** [mm/mmu_notifier.o] Error 1

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>