gre6: add Kconfig dependency for NET_IPGRE_DEMUX
Message-id: <1484909521-13705-1-git-send-email-jkbs@redhat.com>
Patchwork-id: 163012
O-Subject: [RHEL7.4 net 33/35] gre6: add Kconfig dependency for NET_IPGRE_DEMUX
Bugzilla: 1369158
RH-Acked-by: Lance Richardson <lrichard@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1369158
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12396960
Tested: with LNST tunnel test suite

commit 8bf42e9e51cce73874252e5b8fb938bb09bf0ce4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 3 17:19:57 2016 +0200

    gre6: add Kconfig dependency for NET_IPGRE_DEMUX

    The ipv6 gre implementation was cleaned up to share more code
    with the ipv4 version, but it can be enabled even when NET_IPGRE_DEMUX
    is disabled, resulting in a link error:

    net/built-in.o: In function `gre_rcv':
    :(.text+0x17f5d0): undefined reference to `gre_parse_header'
    ERROR: "gre_parse_header" [net/ipv6/ip6_gre.ko] undefined!

    This adds a Kconfig dependency to prevent that now invalid
    configuration.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 308edfdf1563 ("gre6: Cleanup GREv6 receive path, call common GRE functions")
    Acked-by: Tom Herbert <tom@herbertland.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jakub Sitnicki <jkbs@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>