spec: Add missing Provides for kabi whitelists package
Patchwork-id: 66178
O-Subject: [RHEL6.5 PATCH BLOCKER] [redhat] Add missing Provides for kabi whitelists package
Bugzilla: 1004382
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1004382

When the kabi-whitelist package was integrated into the kernel
as a sub package for RHEL-6.5, we thought the Obsoletes line would
take care of the old kabi-whitelist package during an update.

Unfortunately, it didn't quite work for kabi-yum-plugins.  During a
rel-eng test of installing all rpms for RHEL-6.5, it was noticed that
kabi-yum-plugins was failing because of the missing kabi-whitelists
package.  The reason why was the name change from kabi-whitelists to
kernel-abi-whitelists.

My first solution was to update kabi-yum-plugins to look for the new
package name, 'kernel-abi-whitelists'.  But doing the management dance
of writing the errata and getting the component approved was going to be
a difficult task.

Luckily Kyle knows more about rpms than I do and suggested adding a
Provides line in the kernel.spec file.

That did the trick as shown below and keeps the change simple for
management too.

Tested using the old package and my new package:

=============
[root@intel-sugarbay-dh-02 ~]# yum install kabi-yum-plugins
kernel-abi-whitelists

Loaded plugins: product-id, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use
subscription-manager to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package kabi-yum-plugins.noarch 0:1.0-2.el6 will be installed
--> Processing Dependency: kabi-whitelists for package:
kabi-yum-plugins-1.0-2.el6.noarch
Package kabi-whitelists is obsoleted by kernel-abi-whitelists, but obsoleting
package does not provide for requirements
---> Package kernel-abi-whitelists.noarch 0:2.6.32-416.el6 will be installed
--> Finished Dependency Resolution
Error: Package: kabi-yum-plugins-1.0-2.el6.noarch (beaker-Workstation)
           Requires: kabi-whitelists
           Available: kabi-whitelists-20130129-1.el6.noarch
(beaker-Workstation)
               kabi-whitelists = 20130129-1.el6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[root@intel-sugarbay-dh-02 ~]# yum install kabi-yum-plugins
kernel-abi-whitelists-2.6.32-414.el6.test.noarch.rpm

Loaded plugins: product-id, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use
subscription-manager to register.
Setting up Install Process
Examining kernel-abi-whitelists-2.6.32-414.el6.test.noarch.rpm:
kernel-abi-whitelists-2.6.32-414.el6.test.noarch
Marking kernel-abi-whitelists-2.6.32-414.el6.test.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package kabi-yum-plugins.noarch 0:1.0-2.el6 will be installed
---> Package kernel-abi-whitelists.noarch 0:2.6.32-414.el6.test will be
installed
--> Finished Dependency Resolution

Dependencies Resolved

Installing:
 kabi-yum-plugins                            noarch
1.0-2.el6                                    beaker-Workstation
6.3 k
 kernel-abi-whitelists                       noarch
2.6.32-414.el6.test
/kernel-abi-whitelists-2.6.32-414.el6.test.noarch                       629 k

Install       2 Package(s)

Total size: 635 k
Total download size: 6.3 k
Installed size: 637 k
Is this ok [y/N]: n
Exiting on user Command
==================

Obviously this is RHEL-only.

Suggested-by: Kyle McMartin <kmcmartin@redhat.com>
Signed-off-by: Don Zickus <dzickus@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>