pass a struct path to vfs_statfs
Patchwork-id: 37517
O-Subject: [PATCH RHEL6 2/3 V2] pass a struct path to vfs_statfs
Bugzilla: 689223
RH-Acked-by: Jeff Layton <jlayton@redhat.com>

Bug 711987 - [RHEL-6] statvfs tries to stat unrelated mountpoints

This modifies exported vfs_statvfs(), but it's not on the KABI list.

Backport of this commit:

commit ebabe9a9001af0af56c0c2780ca1576246e7a74b
Author: Christoph Hellwig <hch@lst.de>
Date:   Wed Jul 7 18:53:11 2010 +0200

    pass a struct path to vfs_statfs

    We'll need the path to implement the flags field for statvfs support.
    We do have it available in all callers except:

     - ecryptfs_statfs.  This one doesn't actually need vfs_statfs but just
       needs to do a caller to the lower filesystem statfs method.
     - sys_ustat.  Add a non-exported statfs_by_dentry helper for it which
       doesn't won't be able to fill out the flags field later on.

    In addition rename the helpers for statfs vs fstatfs to do_*statfs instead
    of the misleading vfs prefix.

    Signed-off-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

and:

commit 62b88dc1912c7d105f768e0e64756f8bd83936db
Author: David Howells <dhowells@redhat.com>
Date:   Thu Aug 26 17:44:35 2010 +0100

    Alpha: Fix a missing comma in sys_osf_statfs()

    Fix a comma that got accidentally deleted from sys_osf_statfs() leading to the
    following warning:

      arch/alpha/kernel/osf_sys.c: In function 'SYSC_osf_statfs':
      arch/alpha/kernel/osf_sys.c:255: error: syntax error before 'buffer'

    Signed-off-by: David Howells <dhowells@redhat.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>