drm/i915/selftests: Remove unused dmabuf->kmap routines, fix the build
Message-id: <20190530013147.11438-10-lyude@redhat.com>
Patchwork-id: 261195
O-Subject: [RHEL8 drm 009/117] drm/i915/selftests: Remove unused dmabuf->kmap routines, fix the build
Bugzilla: 1707312 1688524 1685552 1685427 1665631 1665088 1664615 1664609 1664189 1664177 1664175 1664104 1662017 1660302 1643842 1640840 1639990 1639436 1637606 1633845 1633843 1633842 1504286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Ben Skeggs <bskeggs@redhat.com>
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Bugzilla: 1665631,1639436,1633843,1665088,1660302,1504286,1664609,1633842,1707312,1664189,1639990,1633845,1664175,1664615,1685552,1662017,1640840,1688524,1664104,1685427,1637606,1643842,1664177
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21914589
Upstream: since v4.19

commit f55786faa156370374c358d186eabf2f6e32e93f
Author:     Chris Wilson <chris@chris-wilson.co.uk>
AuthorDate: Wed Jun 20 17:21:52 2018 +0100
Commit:     Chris Wilson <chris@chris-wilson.co.uk>
CommitDate: Wed Jun 20 17:48:24 2018 +0100

    drm/i915/selftests: Remove unused dmabuf->kmap routines, fix the build

    Fix i915's CI build after the removal of the dmabuf->kmap interface that
    left the mock routines intact.

    In file included from drivers/gpu/drm/i915/i915_gem_dmabuf.c:335:0:
    drivers/gpu/drm/i915/selftests/mock_dmabuf.c:104:13: error: ‘mock_dmabuf_kunmap_atomic’ defined but not used [-Werror=unused-function]
     static void mock_dmabuf_kunmap_atomic(struct dma_buf *dma_buf, unsigned long page_num, void *addr)
    drivers/gpu/drm/i915/selftests/mock_dmabuf.c:97:14: error: ‘mock_dmabuf_kmap_atomic’ defined but not used [-Werror=unused-function]
     static void *mock_dmabuf_kmap_atomic(struct dma_buf *dma_buf, unsigned long page_num)

    Fixes: f664a5269542 ("dma-buf: remove kmap_atomic interface")
    Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
    Cc: Christian König <christian.koenig@amd.com>
    Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
    Cc: Sumit Semwal <sumit.semwal@linaro.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20180620162152.1158-1-chris@chris-wilson.co.uk
    Reviewed-by: Christian König <christian.koenig@amd.com>

Signed-off-by: Lyude Paul <lyude@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>