powerpc: Move `path` variable inside DEBUG_PROM
Message-id: <20190723040144.381-8-drosario@redhat.com>
Patchwork-id: 267075
O-Subject: [RHEL-8.1 BZ1731400 PATCH 07/10] powerpc: Move `path` variable inside DEBUG_PROM
Bugzilla: 1731400
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1731400

DESCRIPTION:
------------
Add gcc attribute unused for two variables. Fix warnings treated as errors
with W=1:

  arch/powerpc/kernel/prom_init.c:1388:8: error: variable ‘path’ set but not used [-Werror=unused-but-set-variable]

Suggested-by: Christophe Leroy <christophe.leroy@c-s.fr>
Signed-off-by: Mathieu Malaterre <malat@debian.org>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

UPSTREAM STATUS:
----------------
commit eab00a208eb63d863b6cc0a03f68b4424ef5add8

https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=eab00a208eb63d863b6cc0a03f68b4424ef5add8

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>