trace: Add config option checking to the definitions of mce handlers
Patchwork-id: 62593
O-Subject: [RHEL6.5 PATCH v2 6/7] x86/tracing: Add config option checking to the definitions of mce handlers
Bugzilla: 738712
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=738712

Manually created to fit RHEL6 based on following upstream commit.

 Commit: 33e5ff634f07dec26b7ed1fd7f9e32978fe1f2b2
 Author: Seiji Aguchi <seiji.aguchi@hds.com>
 Date: Sat, 22 Jun 2013 07:33:30 -0400

 In case CONFIG_X86_MCE_THRESHOLD and CONFIG_X86_THERMAL_VECTOR
 are disabled, kernel build fails as follows.

    arch/x86/built-in.o: In function `trace_threshold_interrupt':
    (.entry.text+0x122b): undefined reference to `smp_trace_threshold_interrupt'
    arch/x86/built-in.o: In function `trace_thermal_interrupt':
    (.entry.text+0x132b): undefined reference to `smp_trace_thermal_interrupt'

 In this case, trace_threshold_interrupt/trace_thermal_interrupt
 are not needed to define.

 So, add config option checking to their definitions in entry_64.S.

 Signed-off-by: Seiji Aguchi <seiji.aguchi@hds.com>
 Cc: rostedt@goodmis.org
 Link: http://lkml.kernel.org/r/51C58B8A.2080808@hds.com
 Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Seiji Aguchi <saguchi@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>