RDMA/iw_cxgb4: Fix the unchecked ep dereference
Message-id: <20190424065302.26000-15-avynipad@redhat.com>
Patchwork-id: 250786
O-Subject: [RHEL8.1 BZ 1664673 14/29] RDMA/iw_cxgb4: Fix the unchecked ep dereference
Bugzilla: 1664673
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1664673

commit 3352976c892301fd576a2e9ff0ac7337b2e2ca48
Author: Raju Rangoju <rajur@chelsio.com>
Date:   Fri Jan 11 20:27:18 2019 +0530

    RDMA/iw_cxgb4: Fix the unchecked ep dereference

    The patch 944661dd97f4: "RDMA/iw_cxgb4: atomically lookup ep and get a
    reference" from May 6, 2016, leads to the following Smatch complaint:

        drivers/infiniband/hw/cxgb4/cm.c:2953 terminate()
        error: we previously assumed 'ep' could be null (see line 2945)

    Fixes: 944661dd97f4 ("RDMA/iw_cxgb4: atomically lookup ep and get a reference")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Raju Rangoju <rajur@chelsio.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: Kamal Heib <kheib@redhat.com>
Cc: Venkatesh Pottem <vpottem@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>