perf: include missing pthread.h header
Patchwork-id: 57941
O-Subject: [PATCH RHEL6.5 BZ927866 116/264] perf tools: include missing pthread.h header
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Irina Tirdea <irina.tirdea@intel.com>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit 27683dc5cc9286ace82b6c900ab794428ed5e487
Author: Irina Tirdea <irina.tirdea@intel.com>
Date:   Sat Sep 8 03:43:19 2012 +0300

description
===========
pthread variables are used in some files without explicitely including
pthread.h. This leads to compile errors on Android. e.g.: in annotate.h,
error: unknown type name 'pthread_mutex_t'

Including pthread.h explicitely in files that use it to have all definitions
included.