tools: Be consistent on the type of map->symbols[] interator
Message-id: <20170502224138.4325-2-jolsa@redhat.com>
Patchwork-id: 177604
O-Subject: [PATCH RHEL7.4 BZ1432658 1/2] perf tools: Be consistent on the type of map->symbols[] interator
Bugzilla: 1140522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1432658
https://bugzilla.redhat.com/show_bug.cgi?id=1432658

upstream
========
commit a0b2f5af4c99d3da7ce9bc2b3b4641c8ffd22615
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Tue Feb 14 16:19:56 2017 -0300

description
===========
In a few cases we were using 'enum map_type' and that triggered this
warning when using clang:

  util/session.c:1923:16: error: comparison of constant 2 with expression of type 'enum map_type' is always true
      [-Werror,-Wtautological-constant-out-of-range-compare]
        for (i = 0; i < MAP__NR_TYPES; ++i) {

Signed-off-by: Rafael Aquini <aquini@redhat.com>