evlist: Fix 32-bit build error
Patchwork-id: 99648
O-Subject: [PATCH RHEL6.7 BZ1159929 203/320] perf evlist: Fix 32-bit build error
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 2af68ef50c6afc1632edc984e9c834545d90f597
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Oct 18 15:29:07 2013 +0300

description
===========
util/evlist.c: In function 'perf_evlist__mmap':
util/evlist.c:772:2: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' [-Werror=format]
cc1: all warnings being treated as errors

Signed-off-by: Rafael Aquini <aquini@redhat.com>