hists browser: Add missing stdarg.h include
Patchwork-id: 43567
O-Subject: =?UTF-8?q?=5BPATCH=20RHEL6=2E3=20BZ784888=2052/97=5D=20perf=20hists=20browser=3A=20Add=20missing=20stdarg=2Eh=20include?=
Bugzilla: 784888
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 784888
https://bugzilla.redhat.com/show_bug.cgi?id=784888

upstream status
===============
commit 7bc7298d3f63e55591477752eb809ab17031ec19
Author: Mike Galbraith <efault@gmx.de>
Date:   Mon Oct 17 09:14:58 2011 -0200

description
===========
    CC util/ui/browsers/annotate.o
In file included from util/ui/browsers/annotate.c:2:0:
util/ui/browsers/../helpline.h:9:42: error: expected declaration
specifiers or ... before va_list
    CC util/ui/browsers/hists.o
make: *** [util/ui/browsers/annotate.o] Error 1
make: *** Waiting for unfinished jobs....

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>