s390/mem_detect: add missing include
Message-id: <20190404105230.28446-53-prudo@redhat.com>
Patchwork-id: 248832
O-Subject: [RHEL8.1 PATCH RESEND 52/52] [s390] s390/mem_detect: add missing include
Bugzilla: 1695615
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>
RH-Acked-by: David Hildenbrand <david@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

Bugzilla: 1695615
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20916163
Tested: by IBM

commit c72251ad879056d096d39db21c08cb52e481eb2d
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Tue Oct 9 12:23:43 2018 +0200

    s390/mem_detect: add missing include

    Fix this allnoconfig build breakage:

    arch/s390/boot/mem_detect.c: In function 'tprot':
    arch/s390/boot/mem_detect.c:122:12: error: 'EFAULT' undeclared (first use in this function)

    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

Signed-off-by: Philipp Rudo <prudo@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>