sched: act_simple: validate the control action inside init()
Message-id: <20190610212005.12299-144-ivecera@redhat.com>
Patchwork-id: 264130
O-Subject: [RHEL-8.1 net PATCH 143/194] net/sched: act_simple: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 4b006b0c139e486773335f4c23b4d82348cfeb04
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:10 2019 +0100

    net/sched: act_simple: validate the control action inside init()

    the following script:

     # tc qdisc add dev crash0 clsact
     # tc filter add dev crash0 egress matchall \
     > action simple sdata hello pass index 90
     # tc actions replace action simple \
     > sdata world goto chain 42 index 90 cookie c1a0c1a0
     # tc action show action simple

    had the following output:

     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0: Simple <world>
              index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
     #PF error: [normal kernel read fault]
     PGD 800000006a6fb067 P4D 800000006a6fb067 PUD 6aed6067 PMD 0
     Oops: 0000 [#1] SMP PTI
     CPU: 2 PID: 3241 Comm: kworker/2:0 Not tainted 5.0.0-rc4.gotochain_crash+ #536
     Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
     Workqueue: ipv6_addrconf addrconf_dad_work
     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffffbe6781763ad0 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff9e59bdb80e00 RCX: 0000000000000000
     RDX: 0000000000000000 RSI: ffff9e59b4716738 RDI: ffff9e59ab12d140
     RBP: ffffbe6781763b70 R08: 0000000000000234 R09: 0000000000aaaaaa
     R10: 0000000000000000 R11: ffff9e59b247cd50 R12: ffff9e59b112f100
     R13: ffff9e59b112f108 R14: 0000000000000001 R15: ffff9e59ab12d0c0
     FS:  0000000000000000(0000) GS:ffff9e59b4700000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 000000006af92004 CR4: 00000000001606e0
     Call Trace:
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ndisc_next_option+0x50/0x50
      ? ___neigh_create+0x4d5/0x680
      ? ip6_finish_output2+0x1b5/0x590
      ip6_finish_output2+0x1b5/0x590
      ? ip6_output+0x68/0x110
      ip6_output+0x68/0x110
      ? nf_hook.constprop.28+0x79/0xc0
      ndisc_send_skb+0x248/0x2e0
      ndisc_send_ns+0xf8/0x200
      ? addrconf_dad_work+0x389/0x4b0
      addrconf_dad_work+0x389/0x4b0
      ? __switch_to_asm+0x34/0x70
      ? process_one_work+0x195/0x380
      ? addrconf_dad_completed+0x370/0x370
      process_one_work+0x195/0x380
      worker_thread+0x30/0x390
      ? process_one_work+0x380/0x380
      kthread+0x113/0x130
      ? kthread_park+0x90/0x90
      ret_from_fork+0x35/0x40
     Modules linked in: act_simple veth ip6table_filter ip6_tables iptable_filter binfmt_misc crct10dif_pclmul crc32_pclmul ghash_clmulni_intel ext4 snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hwdep mbcache snd_hda_core jbd2 snd_seq snd_seq_device snd_pcm aesni_intel crypto_simd cryptd snd_timer glue_helper snd joydev virtio_balloon pcspkr soundcore i2c_piix4 nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs ata_generic pata_acpi qxl drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops virtio_net ttm net_failover virtio_console virtio_blk failover drm crc32c_intel serio_raw floppy ata_piix libata virtio_pci virtio_ring virtio dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_simple_init() proved to fix the
    above issue. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>