tools: Fix bench/numa.c for 32-bit build
Patchwork-id: 99621
O-Subject: [PATCH RHEL6.7 BZ1159929 205/320] perf tools: Fix bench/numa.c for 32-bit build
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 2100f778d44b9c25bd13d38c24a999e2caf1ae3d
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Oct 18 15:29:09 2013 +0300

description
===========
bench/numa.c: In function 'worker_thread':
bench/numa.c:1123:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
bench/numa.c:1171:6: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'u64' [-Werror=format]
cc1: all warnings being treated as errors

Signed-off-by: Rafael Aquini <aquini@redhat.com>