qat - fix adf_ctl_drv.c:undefined reference to adf_init_pf_wq
Message-id: <20170209163141.30030-22-nhorman@redhat.com>
Patchwork-id: 165529
O-Subject: [RHEL7.4 PATCH 21/42] crypto: qat - fix adf_ctl_drv.c:undefined reference to adf_init_pf_wq
Bugzilla: 1382849
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Fix undefined reference issue reported by kbuild test robot.

Cc: <stable@vger.kernel.org>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 6dc5df71ee5c8b44607928bfe27be50314dcf848)

 Conflicts:
	drivers/crypto/qat/qat_common/adf_common_drv.h

BZ: 1382849
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12462473
Testing: Tested by intel
Signed-off-by: Rafael Aquini <aquini@redhat.com>