Unset CONFIG_DEBUG_FORCE_WEAK_PER_CPU on x86/x86_64 platforms
Patchwork-id: 37202
O-Subject: [RHEL6.2 Xen PATCH V2 15/17] Unset CONFIG_DEBUG_FORCE_WEAK_PER_CPU on
	x86/x86_64 platforms
Bugzilla: 716498
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>

BZ#716498
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=3459909

rhel only patch.

When CONFIG_DEBUG_FORCE_WEAK_PER_CPU set, build fails with:
arch/x86/xen/mmu.c:149: error: __pcpu_scope_xen_cr3 causes a section type conflict
arch/x86/xen/mmu.c:150: error: __pcpu_scope_xen_current_cr3 causes a section type conflict
arch/x86/xen/mmu.c:149: error: __pcpu_unique_xen_cr3 causes a section type conflict
arch/x86/xen/mmu.c:150: error: __pcpu_unique_xen_current_cr3 causes a section type conflict

Kernel default in upstream CONFIG_DEBUG_FORCE_WEAK_PER_CPU
is not set for x86/x86_64, but fedora config overrides it to
CONFIG_DEBUG_FORCE_WEAK_PER_CPU=y for non debug build.

Upstream commit 7c756e6e19 that introduced DEBUG_FORCE_WEAK_PER_CPU
says that it is intended for use on alpha and s390 hw. So undefine
them for x86/x86_64 in -rhel specific configs to override fedora
settings.

Signed-off-by: Igor Mammedov <imammedo@redhat.com>