ALSA: ASoC: max98373: usleep_range() needs include/delay.h
Message-id: <15580872947136052-620-patchset-jkysela@redhat.com>
Patchwork-id: 257125
O-Subject: [RHEL 8.1 PATCH 0619/2119] ALSA: ASoC: max98373: usleep_range() needs include/delay.h
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Commit ca917f9fe1a0fab added use of usleep_range() but not
the corresponding "include <linux/delay.h>". The result is
with Chrome OS won't build because warnings are forced
to be errors:
mnt/host/source/src/third_party/kernel/v4.4/sound/soc/codecs/max98373.c:734:2: error: implicit declaration of function 'usleep_range' [-Werror,-Wimplicit-function-declaration]
        usleep_range(10000, 11000);
        ^

Including delay.h "fixes" this.

Signed-off-by: Grant Grundler <grundler@chromium.org>
Reviewed-by: Benson Leung <bleung@chromium.org>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 3004136b90bedc9e254ff659adb7a60299e9495e)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>