stat: Fail softly on unsupported events
Patchwork-id: 38947
O-Subject: [PATCH RHEL6.2 BZ725522 35/67] perf stat: Fail softly on unsupported
	events
Bugzilla: 725522
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 725522
https://bugzilla.redhat.com/show_bug.cgi?id=725522

upstream status
---------------
commit 370faf1dd0461ad811852c8abbbcd3d73b1e4fc4
Author: Ingo Molnar <mingo@elte.hu>
Date:   Fri Apr 29 16:11:03 2011 +0200

description
-----------
David Ahern reported this perf stat failure:

> # /tmp/build-perf/perf stat -- sleep 1
>   Error: stalled-cycles-frontend event is not supported.
>   Fatal: Not all events could be opened.
>
> This is a Dell R410 with an E5620 processor.

Fail in a softer fashion on unknown/unsupported events.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>