perf: Do not use _FORTIFY_SOURCE when DEBUG=1 is specified
Patchwork-id: 49978
O-Subject: [PATCH RHEL6.4 BZ846702 162/198] perf tools: Do not use _FORTIFY_SOURCE when DEBUG=1 is specified
Bugzilla: 846702
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 846702
https://bugzilla.redhat.com/show_bug.cgi?id=846702

upstream status
===============
commit a83eb3ea97efbc891b2f67e91329638cd4e21622
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Thu May 24 14:48:39 2012 -0300

description
===========
As:

make DEBUG=1 -C tools/perf

disables optimizations and _FORTIFY_SOURCE in recent distros requires
optimizations to be enabled, seen on a Fedora 17 system:

[acme@Fedora17 linux]$ make DEBUG=1 O=/home/acme/git/build/perf/ -C
tools/perf install
In file included from /usr/include/sys/types.h:26:0,
                 from /usr/include/libelf.h:53,
                 from /usr/include/gelf.h:53,
                 from /usr/include/elfutils/libdw.h:53,
                 from <stdin>:2:
/usr/include/features.h:314:4: error: #warning _FORTIFY_SOURCE requires
compiling with optimization (-O) [-Werror=cpp