lo: Do not allow VLAN on loopback
Patchwork-id: 39501
O-Subject: [patch rhel5] net: lo: Do not allow VLAN on loopback
Bugzilla: 703709
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>

BZ703709

https://brewweb.devel.redhat.com/taskinfo?taskID=3533374

upstream commit 0553c891fabd287726b41076cfd03fe7e5ab596f
Author: Krishna Kumar <krkumar2@in.ibm.com>
Date:   Thu Apr 14 06:07:04 2011 +0000

    ip6_pol_route panic: Do not allow VLAN on loopback

    Several tests in the ipv6 routing code check IFF_LOOPBACK, and
    allowing stacking such as VLAN'ing on top of loopback results in a
    netdevice which reports IFF_LOOPBACK but really isn't the loopback
    device.

    Instead of spamming the ipv6 routing code with even more special tests,
    simply disallow VLAN over loopback.

    The result of this patch is:

    # modprobe 8021q
    # vconfig add lo 43
    ERROR: trying to add VLAN #43 to IF -:lo:-  error: Operation not supported

Signed-off-by: Jiri Pirko <jpirko@redhat.com>
Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>