perf list: Fix --raw-dump option
Patchwork-id: 127451
O-Subject: [PATCH RHEL6 BZ1265262 146/210] perf list: Fix --raw-dump option
Bugzilla: 1265262
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1265262
https://bugzilla.redhat.com/show_bug.cgi?id=1265262

upstream
========
commit b3505208804f3b59150cd77719f01c8b0023a865
Author: Taesoo Kim <tsgatesv@gmail.com>
Date: Tue Dec 30 22:36:55 2014 -0500

description
===========
Currently, 'perf list --raw-dump' requires extra arguments
(e.g., hw) to invoke, which breaks bash/zsh completion
(perf-completion.sh).

  $ perf list --raw-dump
    Error: unknown option `raw-dump'

     usage: perf list [hw|sw|cache|tracepoint|pmu|event_glob]

After,

  $ perf list --raw-dump
  cpu-cycles instructions cache-references cache-misses ...

Signed-off-by: Aristeu Rozanski <aris@redhat.com>