ALSA: ASoC: sdm845: add rt5663 codec select
Message-id: <15580872947136052-1042-patchset-jkysela@redhat.com>
Patchwork-id: 257575
O-Subject: [RHEL 8.1 PATCH 1041/2119] ALSA: ASoC: sdm845: add rt5663 codec select
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Calling into the codec driver adds a dependency on that being reachable
from the module:

ERROR: "rt5663_sel_asrc_clk_src" [sound/soc/qcom/snd-soc-sdm845.ko]
undefined!

Add the corresponding select statement, as it is done in the other user
(Intel).

Fixes: f7485875a687 ("ASoC: sdm845: Add configuration for headset codec")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit e9dc919043c56dccedce93fe402e6c94423a70b0)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>