perf: add NO_BACKTRACE for application self-debugging
Patchwork-id: 57969
O-Subject: [PATCH RHEL6.5 BZ927866 119/264] perf tools: add NO_BACKTRACE for application self-debugging
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Irina Tirdea <irina.tirdea@intel.com>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit c9f08bee50c71b06685ccff8110e56a7c05662b7
Author: Irina Tirdea <irina.tirdea@intel.com>
Date:   Sat Sep 8 03:43:23 2012 +0300

description
===========
perf has support for self-debugging by defining dump_stack function.
This function uses backtrace and backtrace_symbols functions defined as
GNU extensions.

In Android, bionic does not offer support for these functions and
compilation will fail with the following error:

target  C: libperf <= tools/perf/util/util.c
tools/perf/util/util.c:4:22: fatal error: execinfo.h: No such file or directory
compilation terminated.

Add a compile-time option (NO_BACKTRACE) to enable or disable
self-debugging functionality in perf. This can also help in debugging
since it offers the possibility to turn on/off printing the backtrace.