add WCNSS dependency for HCI driver
Message-id: <1488920286-50873-62-git-send-email-darcari@redhat.com>
Patchwork-id: 172657
O-Subject: [RHEL7.4 PATCH BZ 1415327 106/176] Bluetooth: add WCNSS dependency for HCI driver
Bugzilla: 1415327
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1415327

commit 3d4e2fb64111ffb5dc737daf25f5434bf39bee5f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Aug 29 14:36:18 2016 +0200

    Bluetooth: add WCNSS dependency for HCI driver

    The newly added bluetooth driver is based on the soc-specific support,
    but lacks the obvious compile-time dependency on that:

    drivers/bluetooth/btqcomsmd.o: In function `btqcomsmd_probe':
    btqcomsmd.c:(.text.btqcomsmd_probe+0x40): undefined reference to `qcom_wcnss_open_channel'
    btqcomsmd.c:(.text.btqcomsmd_probe+0x5c): undefined reference to `qcom_wcnss_open_channel'
    Makefile:969: recipe for target 'vmlinux' failed

    Fixes: 90c107dc8b2c ("Bluetooth: Introduce Qualcomm WCNSS SMD based HCI driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Cc: David Arcari <darcari@redhat.com>
Cc: Don Zickus <dzickus@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>