Explicitely include slab.h to rtsx
Patchwork-id: 78110
O-Subject: [RHEL6.6 PATCH 07/43] mfd: Explicitely include slab.h to rtsx
Bugzilla: 1024205
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This fixes the following build error on some architectures (parisc at least):

drivers/mfd/rtsx_pcr.c: In function 'rtsx_pci_init_chip':
drivers/mfd/rtsx_pcr.c:985:2: error: implicit declaration of function 'kcalloc'
[-Werror=implicit-function-declaration]
drivers/mfd/rtsx_pcr.c:985:13: warning: assignment makes pointer from integer
without a cast [enabled by default]

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
(cherry picked from commit aec17ea1ee78923f1287c18e9905c19e4dfd9c64)

BZ: 1024205
Brew:http://brewweb.devel.redhat.com/brew/taskinfo?taskID=7177291
Testing: Tested by Lenovo
Signed-off-by: Neil Horman <nhorman@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>