perf: Fix various casting issues for 32 bits
Patchwork-id: 48066
O-Subject: [PATCH RHEL6.4 BZ827474 088/122] perf tools: Fix various casting issues for 32 bits
Bugzilla: 827474
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 827474
https://bugzilla.redhat.com/show_bug.cgi?id=827474

upstream status
===============
commit 9fafd98f1bf14276f95b69f0186ad5675f1e1a18
Author: Jiri Olsa <jolsa@redhat.com>
Date:   Tue Mar 20 19:15:39 2012 +0100

description
===========
- util/parse-events.c(parse_events_add_breakpoint)
  need to use unsigned long instead of u64, otherwise
  we get following gcc error on 32 bits:
     error: cast from pointer to integer of different size

- util/header.c(print_event_desc)
  cannot retype to signed type, otherwise we get following
  gcc error on 32 bits:
     error: comparison between signed and unsigned integer expressions