perf probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name
Patchwork-id: 123767
O-Subject: [PATCH RHEL6 BZ1216217 255/341] perf probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name
Bugzilla: 1216217
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1216217
https://bugzilla.redhat.com/show_bug.cgi?id=1216217

upstream
========
commit 664fee3dc37939bb8010906913fa9dbc52abb587
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed Sep 17 08:41:01 2014 +0000

description
===========
Do not use dwfl_module_addrsym if dwarf_diename can find the symbol
name, since dwfl_module_addrsym can be failed on shared libraries.

Without this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Failed to find symbol at 0x11df1
  Failed to find the address of create_arg_op
    Error: Failed to show vars.
  ----
With this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Available variables at create_arg_op
          @<create_arg_op+0>
                  enum filter_op_type     btype
                  struct filter_arg*      arg
  ----

This bug was reported on linux-perf-users@vger.kernel.org.

Link: http://permalink.gmane.org/gmane.linux.kernel.perf.user/1691