perf tools: Cleanup trace-event-info 'tdata' leak
Message-id: <d4558c447c248269ea0e856fbe7bdc6407e34c3c.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261519
O-Subject: [RHEL8.1 BZ1709243 138/217] perf tools: Cleanup trace-event-info 'tdata' leak
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit faedbf3fd19f2511a39397f76359e4cc6ee93072
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:11 2018 -0400

description
===========
Free tracing_data structure in tracing_data_get() error paths.

Fixes the following coverity complaint:

  Error: RESOURCE_LEAK (CWE-772):
  leaked_storage: Variable "tdata" going out of scope leaks the storage

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>