cacheinfo: Enable L3 CID only on AMD
Patchwork-id: 36073
O-Subject: [RHEL6.2 PATCH BZ638748 01/18] x86,
	cacheinfo: Enable L3 CID only on AMD
Bugzilla: 638748
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla:
    https://bugzilla.redhat.com/show_bug.cgi?id=638748

Brew Build:
    https://brewweb.devel.redhat.com/taskinfo?taskID=3337162

Upstream Commit:
    commit cb19060abfdecac0d1eb2d2f0e7d6b7a3f8bc4f4
    Author: Borislav Petkov <borislav.petkov@amd.com>
    Date:   Thu Feb 18 19:37:14 2010 +0100

    x86, cacheinfo: Enable L3 CID only on AMD

    Final stage linking can fail with

     arch/x86/built-in.o: In function `store_cache_disable':
     intel_cacheinfo.c:(.text+0xc509): undefined reference to `amd_get_nb_id'
     arch/x86/built-in.o: In function `show_cache_disable':
     intel_cacheinfo.c:(.text+0xc7d3): undefined reference to `amd_get_nb_id'

    when CONFIG_CPU_SUP_AMD is not enabled because the amd_get_nb_id
    helper is defined in AMD-specific code but also used in generic code
    (intel_cacheinfo.c). Reorganize the L3 cache index disable code under
    CONFIG_CPU_SUP_AMD since it is AMD-only anyway.

    Signed-off-by: Borislav Petkov <borislav.petkov@amd.com>
    LKML-Reference: <20100218184210.GF20473@aftab>
    Signed-off-by: H. Peter Anvin <hpa@zytor.com>

Test Status:
    Tested on AMD Dinar systems with Family 10h (Magny-Cours)
    and Family 15h (Bulldozer) CPUs:
    * CPU topology information is correct
    * NUMA information is correct
    * GART is enabled and used
    * kdump is working
    * L3 Cache Index Disable is working
    * L3 Cache Partitioning is working on Family 15h CPUs

Signed-off-by: Frank Arnold <farnold@redhat.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>