ALSA: hda/ca0132 - make pci_iounmap() call conditional
Message-id: <15580872947136052-1052-patchset-jkysela@redhat.com>
Patchwork-id: 257441
O-Subject: [RHEL 8.1 PATCH 1051/2119] ALSA: hda/ca0132 - make pci_iounmap() call conditional
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

When building without CONFIG_PCI, we can (depending on the architecture)
get a link failure:

ERROR: "pci_iounmap" [sound/pci/hda/snd-hda-codec-ca0132.ko] undefined!

Adding a compile-time check for PCI gets it to work correctly on
32-bit ARM.

Fixes: d99501b8575d ("ALSA: hda/ca0132 - Call pci_iounmap() instead of iounmap()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 1e73359a24fad529b0794515b46cbfff99e5fbe6)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>