tools: Fix test_on_exit for 32-bit build
Patchwork-id: 99647
O-Subject: [PATCH RHEL6.7 BZ1159929 204/320] perf tools: Fix test_on_exit for 32-bit build
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 9402802a416c96b48b2bd9331c070ba2d7550b36
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Oct 18 15:29:08 2013 +0300

description
===========
builtin-record.c:42:12: error: static declaration of 'on_exit' follows non-static declaration
In file included from util/util.h:51:0,
                 from builtin.h:4,
                 from builtin-record.c:8:
/usr/include/stdlib.h:536:12: note: previous declaration of 'on_exit' was here

Signed-off-by: Rafael Aquini <aquini@redhat.com>