perf tools: Allow use of an exclusive option more than once
Patchwork-id: 127483
O-Subject: [PATCH RHEL6 BZ1265262 178/210] perf tools: Allow use of an exclusive option more than once
Bugzilla: 1265262
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1265262
https://bugzilla.redhat.com/show_bug.cgi?id=1265262

upstream
========
commit 5594b557aacaafbba7ad8e5ed29005df883bfe3a
Author: Namhyung Kim <namhyung@kernel.org>
Date: Sat Jan 10 19:33:45 2015 +0900

description
===========
The exclusive options are to prohibit use of conflicting options at the
same time.  But it had a side effect that it also limits a such option
can be used at most once.  Currently the only user of the flag is perf
probe and it allows to use such options more than once, but when one
tries to use it, perf will fail like below:

  $ sudo perf probe -x /lib/libc-2.20.so --add malloc --add free
    Error: option `add' cannot be used with add
  ...

Signed-off-by: Aristeu Rozanski <aris@redhat.com>