tools: Fix old GCC build error in 'get_srcline'
Patchwork-id: 99609
O-Subject: [PATCH RHEL6.7 BZ1159929 171/320] perf tools: Fix old GCC build error in 'get_srcline'
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit a949fffb84df6f9be136198a00f796a9dc696bd0
Author: David Ahern <dsahern@gmail.com>
Date: Wed Oct 9 21:51:31 2013 -0600

description
===========
trace-event-parse.c:parse_proc_kallsyms()

    Old GCC (4.4.2) does not see through the code flow of get_srcline() and
gets confused about the status of 'file' and 'line':

    CC       /tmp/build/perf/util/srcline.o
  cc1: warnings being treated as errors
  util/srcline.c: In function get_srcline:
  util/srcline.c:226: error: file may be used uninitialized in this function
  util/srcline.c:227: error: line may be used uninitialized in this function
  make[1]: *** [/tmp/build/perf/util/srcline.o] Error 1
  make: *** [install] Error 2
  make: Leaving directory `/home/acme/git/linux/tools/perf'
  [acme@fedora12 linux]$

Help out GCC by initializing 'file' and 'line'.

Signed-off-by: Rafael Aquini <aquini@redhat.com>