perf tools: Fix compile error on x86_64 Ubuntu
Patchwork-id: 44281
O-Subject: [PATCH RHEL6.3 BZ788156 78/79] perf tools: Fix compile error on
	x86_64 Ubuntu
Bugzilla: 788156
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 788156
https://bugzilla.redhat.com/show_bug.cgi?id=788156

upstream status
===============
commit 172d1b0b73256551f100fc00c69e356d047103f5
Author: Namhyung Kim <namhyung@gmail.com>
Date:   Mon Jan 9 00:10:30 2012 +0900

description
===========
The ctype.h include is not needed here and it breaks build on some systems (at
least 64bit Ubuntu 10.04) like below. Just get rid of it.

    CC util/trace-event-info.o
cc1: warnings being treated as errors
util/trace-event-info.c: In function record_file:
util/trace-event-info.c:192: error: implicit declaration of function pwrite
util/trace-event-info.c:192: error: nested extern declaration of pwrite
make: *** [util/trace-event-info.o] Error 1

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>