mdio_bus: fix devm_mdiobus_alloc_size export
Message-id: <20170202180938.8804-29-ivecera@redhat.com>
Patchwork-id: 164837
O-Subject: [RHEL7.4 net PATCH 28/48] mdio_bus: fix devm_mdiobus_alloc_size export
Bugzilla: 1382040
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1382040

Upstream commit(s):
commit 93dccc59165ad1b4db94528dfdf88bff92c09cef
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 8 16:46:52 2014 +0200

    mdio_bus: fix devm_mdiobus_alloc_size export

    commit 6d48f44b7b2 "mdio_bus: implement devm_mdiobus_alloc/devm_mdiobus_free"
    introduced a new function devm_mdiobus_alloc_size() but added an export
    for a different function devm_mdiobus_alloc(), which was obviously
    a simple mistake that leads to  build error whenever this function is
    used from a loadable module:

    ERROR: "devm_mdiobus_alloc_size" [drivers/net/ethernet/ti/davinci_mdio.ko] undefined!

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Grygorii Strashko <grygorii.strashko@ti.com>
    Cc: Florian Fainelli <f.fainelli@gmail.com>
    Cc: Sergei Shtylyov <sergei.shtylyov@cogentembedded.com>
    Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
    Cc: David S. Miller <davem@davemloft.net>
    Cc: netdev@vger.kernel.org
    Acked-by: Lad, Prabhakar <prabhakar.csengg@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>