busy_poll: fix a compile error when CONFIG_NET_LL_RX_POLL is not set
Patchwork-id: 78450
O-Subject: [patch rhel6 net 23/27] net: fix a compile error when CONFIG_NET_LL_RX_POLL is not set
Bugzilla: 1000460
RH-Acked-by: Vlad Yasevich <vyasevic@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ1000460
https://brewweb.devel.redhat.com/taskinfo?taskID=7229916

upstream commit dfcefb0be1231982784df2152213103ad33c1cfd
Author: Cong Wang <amwang@redhat.com>
Date:   Thu Aug 1 11:10:24 2013 +0800

    net: fix a compile error when CONFIG_NET_LL_RX_POLL is not set

    When CONFIG_NET_LL_RX_POLL is not set, I got:

    net/socket.c: In function 'sock_poll':
    net/socket.c:1165:4: error: implicit declaration of function 'sk_busy_loop' [-Werror=implicit-function-declaration]

    Fix this by adding a nop when !CONFIG_NET_LL_RX_POLL.

Signed-off-by: Jiri Pirko <jpirko@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>