fix implicit usage of gfp.h in host/xhci-hub.c
Patchwork-id: 44047
O-Subject: [RHEL6 PATCH v2 51/70] usb: fix implicit usage of gfp.h in
	host/xhci-hub.c
Bugzilla: 738877
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=738877

commit 4bcbcc96e16fd44eaf9791cb369da757dae1656c
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Mon Jul 18 14:42:00 2011 -0400

    usb: fix implicit usage of gfp.h in host/xhci-hub.c

    To fix this build error on ARM:

    drivers/usb/host/xhci-hub.c: In function 'xhci_stop_device':
    drivers/usb/host/xhci-hub.c:261: error: 'GFP_NOIO' undeclared (first use in this function)
    make[4]: *** [drivers/usb/host/xhci-hub.o] Error 1

    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>