netfilter: ipset: add dependency on CONFIG_NETFILTER_NETLINK
Patchwork-id: 37374
O-Subject: [RHEL6.2 PATCH 22/41] netfilter: ipset: add dependency on CONFIG_NETFILTER_NETLINK
Bugzilla: 599054
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

Backport of:
commit c16e19c11730199c1df686b160c9c972ad28baf8
Author: Patrick McHardy <kaber@trash.net>
Date:   Thu Feb 10 10:13:07 2011 +0100

    netfilter: ipset: add dependency on CONFIG_NETFILTER_NETLINK

    When SYSCTL and PROC_FS and NETFILTER_NETLINK are not enabled:

    net/built-in.o: In function `try_to_load_type':
    ip_set_core.c:(.text+0x3ab49): undefined reference to `nfnl_unlock'
    ip_set_core.c:(.text+0x3ab4e): undefined reference to `nfnl_lock'
    ...

    Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
    Acked-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Patrick McHardy <kaber@trash.net>

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>