ALSA: ASoC: nau8810: fix the issue of 64 bits division
Message-id: <15580872947136052-1753-patchset-jkysela@redhat.com>
Patchwork-id: 258466
O-Subject: [RHEL 8.1 PATCH 1752/2119] ALSA: ASoC: nau8810: fix the issue of 64 bits division
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Do division with div_u64 for the PLL calculation.
These errors are fixed and list as follows:
1."__udivdi3" [sound/soc/codecs/snd-soc-nau8810.ko] undefined!
2."__aeabi_uldivmod" [sound/soc/codecs/snd-soc-nau8810.ko] undefined!
3. nau8810.c:(.text.nau8810_calc_pll+0xd8): undefined reference to
`__udivdi3'

Signed-off-by: John Hsu <KCHSU0@nuvoton.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 3a9ce0f1b2961f6c3ad2a49dcf85449784c18bb5)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>