bridge: only provide proxy ARP when CONFIG_INET is enabled
Message-id: <20170127151821.20722-35-ivecera@redhat.com>
Patchwork-id: 163441
O-Subject: [RHEL7.4 net PATCH 034/119] bridge: only provide proxy ARP when CONFIG_INET is enabled
Bugzilla: 1352289
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

BZ#1352289

Upstream commit(s):
commit d92cfdbbeaefb467de4fac98679fa6c33461d250
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 13 15:10:27 2015 +0100

    bridge: only provide proxy ARP when CONFIG_INET is enabled

    When IPV4 support is disabled, we cannot call arp_send from
    the bridge code, which would result in a kernel link error:

    net/built-in.o: In function `br_handle_frame_finish':
    :(.text+0x59914): undefined reference to `arp_send'
    :(.text+0x59a50): undefined reference to `arp_tbl'

    This makes the newly added proxy ARP support in the bridge
    code depend on the CONFIG_INET symbol and lets the compiler
    optimize the code out to avoid the link error.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 958501163ddd ("bridge: Add support for IEEE 802.11 Proxy ARP")
    Cc: Kyeyoon Park <kyeyoonp@codeaurora.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>