sched: Export sched_setscheduler_nocheck
Message-id: <20170303184251.1933-22-rclark@redhat.com>
Patchwork-id: 170026
O-Subject: [RHEL7 drm 21/32] sched: Export sched_setscheduler_nocheck
Bugzilla: 1406119
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Lyude Paul <lyude@redhat.com>

Upstream: since v4.4
RHBZ: 1406119

commit 84778472e1b6a27a8931712c40e8cf31143c8f6c

Author:     Davidlohr Bueso <dave@stgolabs.net>
AuthorDate: Wed Sep 2 01:28:44 2015 -0700
Commit:     Paul E. McKenney <paulmck@linux.vnet.ibm.com>
CommitDate: Tue Oct 6 11:07:54 2015 -0700

    sched: Export sched_setscheduler_nocheck

    The new locktorture rtmutex_lock tests exercise priority boosting, which
    means that they need to set some tasks to real-time priority.  To do this,
    they use sched_setscheduler_nocheck().  However, this is not exported to
    modules, which results in the following error when building locktorture
    as a module:

    ERROR: "sched_setscheduler_nocheck" [kernel/locking/locktorture.ko] undefined!

    This commit therefore adds an EXPORT_SYMBOL_GPL() to allow this function
    to be invoked from locktorture when built as a module.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Davidlohr Bueso <dave@stgolabs.net>
    Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
    Acked-by: Ingo Molnar <mingo@kernel.org>
    Reviewed-by: Josh Triplett <josh@joshtriplett.org>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>