x86/boot: Fix randconfig build error due to MEMORY_HOTREMOVE
Message-id: <20190724030321.7638-21-bhe@redhat.com>
Patchwork-id: 267146
O-Subject: [RHEL8.1 PATCH v2 20/27] x86/boot: Fix randconfig build error due to MEMORY_HOTREMOVE
Bugzilla: 1564822
RH-Acked-by: Kairui Song <kasong@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1564822
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22757594
Upstream: Merged in linus's tree.
Test: Passed on my kvm guest.

This is back ported from upstream directly, no conflict.

commit 82df8261c6a9523511d83ac367c7d64375ebabf4
Author: Borislav Petkov <bp@suse.de>
Date:   Tue Feb 5 14:04:01 2019 +0100

    x86/boot: Fix randconfig build error due to MEMORY_HOTREMOVE

    When building randconfigs, one of the failures is:

      ld: arch/x86/boot/compressed/kaslr.o: in function `choose_random_location':
      kaslr.c:(.text+0xbf7): undefined reference to `count_immovable_mem_regions'
      ld: kaslr.c:(.text+0xcbe): undefined reference to `immovable_mem'
      make[2]: *** [arch/x86/boot/compressed/vmlinux] Error 1

    because CONFIG_ACPI is not enabled in this particular .config but
    CONFIG_MEMORY_HOTREMOVE is and count_immovable_mem_regions() is
    unresolvable because it is defined in compressed/acpi.c which is the
    compilation unit that depends on CONFIG_ACPI.

    Add CONFIG_ACPI to the explicit dependencies for MEMORY_HOTREMOVE.

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Chao Fan <fanc.fnst@cn.fujitsu.com>
    Cc: x86@kernel.org
    Link: https://lkml.kernel.org/r/20190205131033.9564-1-bp@alien8.de

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>