time: Fix stupid KERN_WARN compile issue
Patchwork-id: 48656
O-Subject: [RHEL6.4 PATCH BZ 836748 44/67] time: Fix stupid KERN_WARN compile issue
Bugzilla: 836748
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit cbaa51524b3224813814607177a00c350ee35d12
Author: John Stultz <john.stultz@linaro.org>
Date:   Wed Jul 20 15:42:55 2011 -0700

    time: Fix stupid KERN_WARN compile issue

    Terribly embarassing. Don't know how I committed this, but its
    KERN_WARNING not KERN_WARN.

    This fixes the following compile error:
    kernel/time/timekeeping.c: In function ‘__timekeeping_inject_sleeptime’:
    kernel/time/timekeeping.c:608: error: ‘KERN_WARN’ undeclared (first use in this function)
    kernel/time/timekeeping.c:608: error: (Each undeclared identifier is reported only once
    kernel/time/timekeeping.c:608: error: for each function it appears in.)
    kernel/time/timekeeping.c:608: error: expected ‘)’ before string constant
    make[2]: *** [kernel/time/timekeeping.o] Error 1

    Reported-by: Ingo Molnar <mingo@elte.hu>
    Signed-off-by: John Stultz <john.stultz@linaro.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>