dm-cache: avoid conflicting remove_mapping() in mq policy
Patchwork-id: 78245
O-Subject: [RHEL6.6 PATCH 060/110] dm cache: avoid conflicting remove_mapping() in mq policy
Bugzilla: 1038227
RH-Acked-by: Joe Thornber <thornber@redhat.com>
RH-Acked-by: Heinz Mauelshagen <heinzm@redhat.com>

BZ: 1038227

Upstream commit b936bf8b785f0fbe083d203049e4da1c56ec788f
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Fri Jul 26 09:57:31 2013 +0200

    dm cache: avoid conflicting remove_mapping() in mq policy

    On sparc32, which includes <linux/swap.h> from <asm/pgtable_32.h>:

    drivers/md/dm-cache-policy-mq.c:962:13: error: conflicting types for 'remove_mapping'
    include/linux/swap.h:285:12: note: previous declaration of 'remove_mapping' was here

    As mq_remove_mapping() already exists, and the local remove_mapping() is
    used only once, inline it manually to avoid the conflict.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>
    Signed-off-by: Alasdair Kergon <agk@redhat.com>
    Acked-by: Joe Thornber <ejt@redhat.com>