autofs4: fix false positive compile error
Patchwork-id: 84791
O-Subject: [REPOST RHEL-6.6 PATCH 4/4] autofs4 - fix false positive compile error
Bugzilla: 858164
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Ian Kent <raven@themaw.net>

Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=858164
Upstream commit: none yet, sent upstream.

On strict build environments we can see:

fs/autofs4/inode.c: In function 'autofs4_fill_super':
fs/autofs4/inode.c:312: error: 'pgrp' may be used uninitialized in this
function
make[2]: *** [fs/autofs4/inode.o] Error 1
make[1]: *** [fs/autofs4] Error 2
make: *** [fs] Error 2
make: *** Waiting for unfinished jobs....

This is due to the use of pgrp_set being used to indicate pgrp has
has been set rather than initializing pgrp itself.

Signed-off-by: Ian Kent <raven@themaw.net>
Signed-off-by: Rafael Aquini <aquini@redhat.com>