make it possible to verify fcoe with sparse
Patchwork-id: 31050
O-Subject: [RHEL6.1 PATCH 01/55] [SCSI] fcoe: make it possible to verify fcoe
	with sparse
Bugzilla: 633915 663561
RH-Acked-by: Rob Evers <revers@redhat.com>
RH-Acked-by: Tomas Henzl <thenzl@redhat.com>

From: Mike Christie <mchristi@redhat.com>

This is for bz 663561.

commit d058fd31c7f44960b00566bda39c85377f461a7b

From: Bart Van Assche <bvanassche@acm.org>

[SCSI] fcoe: make it possible to verify fcoe with sparse

    Analyzing fcoe with sparse currently fails. This is because struct
    fcoe_rcv_info contains two enum members that have been declared with
    __attribute__((packed)). Apparently gcc honors this attribute while
sparse
    ignores it. The result is that sizeof(struct fcoe_rcv_info)
    == sizeof(struct sk_buff::cb) == 48 on a 64-bit system according to
gcc, but
    not according to sparse. The patch below modifies the definition of
    struct fcoe_rcv_info such that gcc and sparse interpret this
structure
    definition in the same way. The current sparse output is as follows:

    $ cd linux-2.6.34
    $ make C=2 M=drivers/scsi/fcoe modules
     CHECK   drivers/scsi/fcoe/fcoe.c

    include/scsi/fc_frame.h:81:9: error: invalid bitfield width, -1.
     CC [M]  drivers/scsi/fcoe/fcoe.o
     CHECK   drivers/scsi/fcoe/libfcoe.c

    include/scsi/fc_frame.h:81:9: error: invalid bitfield width, -1.
    drivers/scsi/fcoe/libfcoe.c:56:37: error: invalid initializer

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>