tools: Fix _FORTIFY_SOURCE builds
Patchwork-id: 79093
O-Subject: [PATCH RHEL6.6 BZ1070896 17/89] tools lib lk: Fix _FORTIFY_SOURCE builds
Bugzilla: 1070896
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1070896
https://bugzilla.redhat.com/show_bug.cgi?id=1070896

upstream
========
commit b28b130719af6e7f56e0bbdac38ba703a36ba5d5
Author: Borislav Petkov <bp@suse.de>
Date: Sun Mar 3 20:25:33 2013 +0100

description
===========
Jiri Olsa triggers the following build error:

    SUBDIR ../lib/lk/
    CC debugfs.o
In file included from /usr/include/errno.h:29:0,
                 from debugfs.c:1:
/usr/include/features.h:314:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]

This is because enabling buffer overflow checks through _FORTIFY_SOURCE
require compiler optimizations to be enabled too. However, those are
not. Enable them by simply copying the perf optimization level. It can
be expanded later if we want to support debug builds, etc.

Signed-off-by: Rafael Aquini <aquini@redhat.com>