ib/mlx4: avoid a -Wmaybe-uninitialize warning
Message-id: <1487828466-9959-273-git-send-email-ddutile@redhat.com>
Patchwork-id: 167307
O-Subject: [PATCH RHEL-7.4 272/348] IB/mlx4: avoid a -Wmaybe-uninitialize warning
Bugzilla: 1385329 1417285
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417285
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385329

commit a4256bc9ec36159e84d710c7c44aaa244a6380a8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 25 18:16:20 2016 +0200

    IB/mlx4: avoid a -Wmaybe-uninitialize warning

    There is an old warning about mlx4_SW2HW_EQ_wrapper on x86:

    ethernet/mellanox/mlx4/resource_tracker.c: In function mlx4_SW2HW_EQ_wrapper:
    ethernet/mellanox/mlx4/resource_tracker.c:3071:10: error: eq may be used uninitialized in this function [-Werror=maybe-uninitialized]

    The problem here is that gcc won't track the state of the variable
    across a spin_unlock. Moving the assignment out of the lock is
    safe here and avoids the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Yishai Hadas <yishaih@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>