phy: export fixed_phy_register()
Message-id: <20170202180938.8804-37-ivecera@redhat.com>
Patchwork-id: 164847
O-Subject: [RHEL7.4 net PATCH 36/48] net: phy: export fixed_phy_register()
Bugzilla: 1382040
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1382040

Upstream commit(s):
commit 37e9a6904520b525b542ecd67201164d06fdb95a
Author: Mark Salter <msalter@redhat.com>
Date:   Thu Dec 11 23:03:26 2014 -0500

    net: phy: export fixed_phy_register()

    When building the bcmgenet driver as module, I get:

    ERROR: "fixed_phy_register" [drivers/net/ethernet/broadcom/genet/genet.ko] undefined!

    commit b0ba512e225d72 ("net: bcmgenet: enable driver to work without device
    tree") which added a call to fixed_phy_register. But fixed_phy_register
    needs to be exported if used from a module.

    Signed-off-by: Mark Salter <msalter@redhat.com>
    Acked-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>