bpf: fix a compilation error when CONFIG_BPF_SYSCALL is not defined
Message-id: <20190604085256.3304-338-yauheni.kaliuta@redhat.com>
Patchwork-id: 262328
O-Subject: [RHEL8.1 PATCH v2 338/627] bpf: fix a compilation error when CONFIG_BPF_SYSCALL is not defined
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit f6161a8f3036caa45f225486be39783e99e0fa29
Author: Yonghong Song <yhs@fb.com>
Date:   Tue Nov 20 14:08:20 2018 -0800

    bpf: fix a compilation error when CONFIG_BPF_SYSCALL is not defined

    Kernel test robot (lkp@intel.com) reports a compilation error at
      https://www.spinics.net/lists/netdev/msg534913.html
    introduced by commit 838e96904ff3 ("bpf: Introduce bpf_func_info").

    If CONFIG_BPF is defined and CONFIG_BPF_SYSCALL is not defined,
    the following error will appear:
      kernel/bpf/core.c:414: undefined reference to `btf_type_by_id'
      kernel/bpf/core.c:415: undefined reference to `btf_name_by_offset'

    When CONFIG_BPF_SYSCALL is not defined,
    let us define stub inline functions for btf_type_by_id()
    and btf_name_by_offset() in include/linux/btf.h.
    This way, the compilation failure can be avoided.

    Fixes: 838e96904ff3 ("bpf: Introduce bpf_func_info")
    Reported-by: kbuild test robot <lkp@intel.com>
    Cc: Martin KaFai Lau <kafai@fb.com>
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>