fix strange message 'error: "Success" setting key "vm.compact_memory" ' while setting sysctl parameter
Patchwork-id: 126501
O-Subject: [RHEL6.8 PATCH] Fix strange message 'error: "Success" setting key "vm.compact_memory" ' while setting sysctl parameter
Bugzilla: 1278842
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

While executing "sysctl -w vm.compact_memory=1", the system gives the following messages:

    error: "Success" setting key "vm.compact_memory"

But "echo '1' > /proc/sys/vm/compact_memory"  executes without error

BZ: 1278842

Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10082937

Tested: by me.

The attached upstream backport fixed this weird message:

 commit 7964c06d66c76507d8b6b662bffea770c29ef0ce
 Author: Jason Liu <r64343@freescale.com>
 Date:   Fri Jan 11 14:31:47 2013 -0800

    mm: compaction: fix echo 1 > compact_memory return error issue

    when run the folloing command under shell, it will return error

      sh/$ echo 1 > /proc/sys/vm/compact_memory
      sh/$ sh: write error: Bad address

    After strace, I found the following log:

      ...
      write(1, "1\n", 2)               = 3
      write(1, "", 4294967295)         = -1 EFAULT (Bad address)
      write(2, "echo: write error: Bad address\n", 31echo: write error: Bad address
      ) = 31

    This tells system return 3(COMPACT_COMPLETE) after write data to
    compact_memory.

    The fix is to make the system just return 0 instead 3(COMPACT_COMPLETE)
    from sysctl_compaction_handler after compaction_nodes finished.

    Signed-off-by: Jason Liu <r64343@freescale.com>
    Suggested-by: David Rientjes <rientjes@google.com>
    Acked-by: Mel Gorman <mgorman@suse.de>
    Cc: Rik van Riel <riel@redhat.com>
    Cc: Minchan Kim <minchan@kernel.org>
    Cc: KAMEZAWA Hiroyuki <kamezawa.hiroyu@jp.fujitsu.com>
    Acked-by: David Rientjes <rientjes@google.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Aristeu Rozanski <aris@redhat.com>