alsa/hda/usb/core: hda: do not export static functions
Patchwork-id: 106397
O-Subject: [RHEL 6.7 PATCH 848/846] {ALSA/HDA/USB/core} hda: do not export static functions
Bugzilla: 1069236
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This fixes PPC build:

sound/pci/hda/hda_controller.c:1230: error: __ksymtab_azx_get_response
causes a section type conflict
sound/pci/hda/hda_controller.c:1230: error: __ksymtab_azx_get_response
causes a section type conflict
sound/pci/hda/hda_controller.c:1216: error: __ksymtab_azx_send_cmd
causes a section type conflict
sound/pci/hda/hda_controller.c:1216: error: __ksymtab_azx_send_cmd
causes a section type conflict
sound/pci/hda/hda_controller.c:936: error: __ksymtab_azx_free_cmd_io
causes a section type conflict
sound/pci/hda/hda_controller.c:936: error: __ksymtab_azx_free_cmd_io
causes a section type conflict
sound/pci/hda/hda_controller.c:926: error: __ksymtab_azx_init_cmd_io
causes a section type conflict
sound/pci/hda/hda_controller.c:926: error: __ksymtab_azx_init_cmd_io
causes a section type conflict
sound/pci/hda/hda_controller.c:861: error: __ksymtab_azx_alloc_cmd_io
causes a section type conflict
sound/pci/hda/hda_controller.c:861: error: __ksymtab_azx_alloc_cmd_io
causes a section type conflict

rhbz#1069236
Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>