perf: Fix strict alias issue for find_first_bit
Patchwork-id: 77898
O-Subject: [PATCH RHEL7.0 BZ1070238 02/16] perf tools: Fix strict alias issue for find_first_bit
Bugzilla: 1070238
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>

Bugzilla: 1070238
https://bugzilla.redhat.com/show_bug.cgi?id=1070238

upstream
========
commit b39c2a57a00a841f057a75b41df4c26173288b66
Author: Jiri Olsa <jolsa@redhat.com>
Date:   Wed Feb 26 18:14:26 2014 +0100

in Ingo's tip/perf/urgent

description
===========
When compiling perf tool code with gcc 4.4.7 I'm getting
following error:

    CC       util/session.o
  cc1: warnings being treated as errors
  util/session.c: In function 'perf_session_deliver_event':
  tools/perf/util/include/linux/bitops.h:109: error: dereferencing pointer 'p' does break strict-aliasing rules
  tools/perf/util/include/linux/bitops.h:101: error: dereferencing pointer 'p' does break strict-aliasing rules
  util/session.c:697: note: initialized from here
  tools/perf/util/include/linux/bitops.h:101: note: initialized from here
  make[1]: *** [util/session.o] Error 1
  make: *** [util/session.o] Error 2

The aliased types here are u64 and unsigned long pointers, which is safe
for the find_first_bit processing.

This error shows up for me only for gcc 4.4 on 32bit x86, even for
-Wstrict-aliasing=3, while newer gcc are quiet and scream here for
-Wstrict-aliasing={2,1}. Looks like newer gcc changed the rules for
strict alias warnings.

The gcc documentation offers workaround for valid aliasing by using
__may_alias__ attribute:

  http://gcc.gnu.org/onlinedocs/gcc-4.4.0/gcc/Type-Attributes.html

Using this workaround for the find_first_bit function.

Signed-off-by: Rafael Aquini <aquini@redhat.com>