bridge: mdb: avoid uninitialized variable warning
Message-id: <1465924603-6119-475-git-send-email-ivecera@redhat.com>
Patchwork-id: 152577
O-Subject: [RHEL7.3 net PATCH 474/570] bridge: mdb: avoid uninitialized variable warning
Bugzilla: 1275772 1297841 1331748
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Lance Richardson <lrichard@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ#1297841

Upstream commit(s):
commit 56bb7fd994f4cc163de08006bf68d959027a9f36
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Feb 10 16:09:02 2016 +0100

    bridge: mdb: avoid uninitialized variable warning

    A recent change to the mdb code confused the compiler to the point
    where it did not realize that the port-group returned from
    br_mdb_add_group() is always valid when the function returns a nonzero
    return value, so we get a spurious warning:

    net/bridge/br_mdb.c: In function 'br_mdb_add':
    net/bridge/br_mdb.c:542:4: error: 'pg' may be used uninitialized in this function [-Werror=maybe-uninitialized]
        __br_mdb_notify(dev, entry, RTM_NEWMDB, pg);

    Slightly rearranging the code in br_mdb_add_group() makes the problem
    go away, as gcc is clever enough to see that both functions check
    for 'ret != 0'.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 9e8430f8d60d ("bridge: mdb: Passing the port-group pointer to br_mdb module")
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>