bnx2x: include irq.h for irqreturn_t definitions
Patchwork-id: 81491
O-Subject: [RHEL6.6 PATCH 102/116] net: bnx2x: include irq.h for irqreturn_t definitions
Bugzilla: 1054563 1054273
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Nikolay Aleksandrov <nikolay@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1054273
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1054563

Upstream commit:
commit df1efc2d3037334f4a868aca9ae329d67058bbfd
Author: Josh Boyer <jwboyer@fedoraproject.org>
Date:   Wed Apr 2 11:21:58 2014 -0400

    net: bnx2x: include irq.h for irqreturn_t definitions

    The bnx2x driver fails to build on ARM with:

    In file included from drivers/net/ethernet/broadcom/bnx2x/bnx2x_link.c:28:0:
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_cmn.h:243:1: error: unknown type name 'irqreturn_t'
     irqreturn_t bnx2x_msix_sp_int(int irq, void *dev_instance);
     ^
    drivers/net/ethernet/broadcom/bnx2x/bnx2x_cmn.h:251:1: error: unknown type name 'irqreturn_t'
     irqreturn_t bnx2x_interrupt(int irq, void *dev_instance);
     ^

    Nothing in bnx2x_link.c or bnx2x_cmn.h is explicitly including the irq
    definitions, so we add an include of linux/irq.h to pick them up.

    Signed-off-by: Josh Boyer <jwboyer@fedoraproject.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>