scsi: qla4xxx driver depends on NET
Patchwork-id: 43681
O-Subject: [RHEL 6.3 PATCH 3/28] scsi: qla4xxx driver depends on NET
Bugzilla: 722297
RH-Acked-by: Mike Christie <mchristi@redhat.com>

Bugzilla
--------

Bug 722297 (https://bugzilla.redhat.com/show_bug.cgi?id=722297)

Upstream Status
---------------

scsi-misc-2.6 commit id d7a210f3d356371677cf553ce6241b620e389844

Description
-----------

From: Randy Dunlap <rdunlap@xenotime.net>

Subject: [PATCH 03/28] scsi: qla4xxx driver depends on NET

When CONFIG_NET is disabled, SCSI_QLA_ISCSI selects SCSI_ISCSI_ATTRS,
which uses network interfaces, so the build fails with multiple errors:

  warning: (ISCSI_TCP && SCSI_CXGB3_ISCSI && SCSI_CXGB4_ISCSI && SCSI_QLA_ISCSI && INFINIBAND_ISER) selects SCSI_ISCSI_ATTRS which has unmet direct dependencies (SCSI && NET)

  ERROR: "skb_trim" [drivers/scsi/scsi_transport_iscsi.ko] undefined!
  ERROR: "netlink_kernel_create" [drivers/scsi/scsi_transport_iscsi.ko] undefined!
  ERROR: "netlink_kernel_release" [drivers/scsi/scsi_transport_iscsi.ko] undefined!
  ...

so make SCSI_QLA_ISCSI also depend on NET to prevent the build errors.

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Cc:	Ravi Anand <ravi.anand@qlogic.com>
Cc:	Vikas Chaudhary <vikas.chaudhary@qlogic.com>
Cc:	iscsi-driver@qlogic.com
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>