qed: Fix static checker warning
Message-id: <20190520064507.24882-44-mchopra@redhat.com>
Patchwork-id: 258981
O-Subject: [PATCH v2 RHEL8.1 043/109] qed: Fix static checker warning
Bugzilla: 1663274
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>

From: Rahul Verma <Rahul.Verma@cavium.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1663274
Upstream: linux.git

commit 68203a67a7024c5d0b8e545d3d370b1fec971551
Author: Rahul Verma <Rahul.Verma@cavium.com>
Date:   Tue Oct 23 08:04:24 2018 -0700

    qed: Fix static checker warning

            Static Checker Warnings:
            drivers/net/ethernet/qlogic/qed/qed_main.c:1510 qed_fill_link_capability()
            error: uninitialized symbol 'tcvr_state'.
            drivers/net/ethernet/qlogic/qed/qed_mcp.c:1951 qed_mcp_trans_speed_mask()
            error: uninitialized symbol 'transceiver_state'.
            drivers/net/ethernet/qlogic/qed/qed_mcp.c:1951 qed_mcp_trans_speed_mask()
            error: uninitialized symbol 'transceiver_type'.

            Symbols tcvr_state, transceiver_state and transceiver_type
            are initialized with respective default state.

    Fixes: c56a8be7e7aa ("qed: Add supported link and advertise link to display in ethtool.")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Rahul Verma <Rahul.Verma@cavium.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>