media: cx231xx: fix RC_CORE dependency
Message-id: <20190611235342.16340-30-torez@redhat.com>
Patchwork-id: 265236
O-Subject: [RHEL8.1 PATCH BZ1697664 v2 29/67] media: cx231xx: fix RC_CORE dependency
Bugzilla: 1697664
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1697664
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22109005
Testing: on Dell Whitehaven Precision 7730, HP ZBook 15 G3/80D5 and
         ThinkCentre M910z All-in-One

commit 9fab166a3e8f9e071de3418d27ffd03cdba2e9df
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri May 25 11:25:10 2018 -0400

    media: cx231xx: fix RC_CORE dependency

    With CONFIG_RC_CORE=m and VIDEO_CX231XX=y, we get a link failure:

    drivers/media/usb/cx231xx/cx231xx-input.o: In function `cx231xx_ir_init':
    cx231xx-input.c:(.text+0xd4): undefined reference to `rc_allocate_device'

    This narrows down the dependency so that only valid configurations
    are allowed.

    Fixes: 84545d2a1436 ("media: cx231xx: Remove RC_CORE dependency")

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>