acpica: macosx: Fix wrong sem_destroy definition
Message-id: <1487787876-10121-100-git-send-email-prarit@redhat.com>
Patchwork-id: 166863
O-Subject: [RHEL7.4 PATCH BZ 1425180 099/101] ACPICA: MacOSX: Fix wrong sem_destroy definition
Bugzilla: 1425180
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Al Stone <ahs3@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1425180

commit b97acdf1b0cd493a8abff703f0674b471bf105b1
Author: Lv Zheng <zetalog@gmail.com>
Date:   Tue Oct 18 03:03:01 2016 +0800

    ACPICA: MacOSX: Fix wrong sem_destroy definition

    ACPICA commit bbcb58f7875381d5c7f3d614bad3bc628a3f5cc6

    The following build errors can be seen for MacOSX builds:
    .../osunixxf.c:882:9: error: 'sem_close' is deprecated [-Werror,-Wdeprecated-declarations]
    .../acmacosx.h:122:29: note: expanded from macro 'sem_destroy'
    #define sem_destroy         sem_close

    sem_destroy() issue is caused by the wrong order of the following lines:
      #define #sem_destroy        sem_close
      #include <semaphore.h>
    This patch fixes it by removing the buggy re-definitiion. Lv Zheng.

    Linux is not affected by this change.

    Link: https://github.com/acpica/acpica/commit/bbcb58f7
    Signed-off-by: Lv Zheng <lv.zheng@intel.com>
    Signed-off-by: Bob Moore <robert.moore@intel.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>