nfs: fix anonymous member initializer build failure with older compilers
Message-id: <20170310150235.10315-81-steved@redhat.com>
Patchwork-id: 173199
O-Subject: [RHEL7.4 fs PATCH 080/167] nfs: fix anonymous member initializer build failure with older compilers
Bugzilla: 1349668
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>

From: Linus Torvalds <torvalds@linux-foundation.org>

Older versions of gcc don't understand named initializers inside a
anonymous structure or union member.  It can be worked around by adding
the bracin gin the initializer for the anonymous member.

Without this, gcc 4.4.4 will fail the build with

    CC      fs/nfs/nfs4state.o
  fs/nfs/nfs4state.c:69: error: unknown field data specified in initializer
  fs/nfs/nfs4state.c:69: warning: missing braces around initializer
  fs/nfs/nfs4state.c:69: warning: (near initialization for zero_stateid.<anonymous>.data)
  make[2]: *** [fs/nfs/nfs4state.o] Error 1

introduced in commit 93b717fd81bf ("NFSv4: Label stateids with the type")

Reported-and-tested-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
Cc: Anna Schumaker <Anna.Schumaker@netapp.com>
Cc: Trond Myklebust <trond.myklebust@primarydata.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit e0714ec4f9efe7b86828b0dcc077fd8f5d8e5e91)
Bugzilla: 1349668
Signed-off-by: Rafael Aquini <aquini@redhat.com>