trace: Improve the error messages
Patchwork-id: 99634
O-Subject: [PATCH RHEL6.7 BZ1159929 168/320] perf trace: Improve the error messages
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 87f918685a452be514d060a09eeb4e0c91422e86
Author: Ramkumar Ramachandra <artagnon@gmail.com>
Date: Fri Oct 4 10:47:31 2013 +0530

RHEL6
=====
Using syscalls:sys_enter, syscalls:sys_enter tracepoints instead
of upstream raw_syscall interface (not in RHEL6 yet).

description
===========
Currently, execution of 'perf trace' reports the following cryptic
message to the user:

$ perf trace
Couldn't read the raw_syscalls tracepoints information!

Typically this happens because the user does not have permissions to
read the debugfs filesystem. Also handle the case when the kernel was
not compiled with debugfs support or when it isn't mounted.

Now, the tool prints detailed error messages:

$ perf trace
Error:  Unable to find debugfs
Hint:   Was your kernel was compiled with debugfs support?
Hint:   Is the debugfs filesystem mounted?
Hint:   Try 'sudo mount -t debugfs nodev /sys/kernel/debug'

$ perf trace
Error:  No permissions to read /sys/kernel/debug//tracing/events/raw_syscalls
Hint:   Try 'sudo mount -o remount,mode=755 /sys/kernel/debug/'

[ Added ready to use commands to fix the issues as extra hints, use the
  current debugfs mount point when reporting permission error, use
  strerror_r instead of the deprecated sys_errlist, as reported by David Ahern ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>