fix compile error in commoncap.c
Patchwork-id: 47207
O-Subject: [PATCH RHEL6.3 2/2] security: fix compile error in commoncap.c
Bugzilla: 806726
CVE: CVE-2012-2123
RH-Acked-by: Petr Matousek <pmatouse@redhat.com>

From: Jonghwan Choi <jhbird.choi@samsung.com>

Bugzilla: 806726
Upstream Commit: 51b79bee627d526199b2f6a6bef8ee0c0739b6d1

Upstream log message:

Add missing "personality.h"
security/commoncap.c: In function 'cap_bprm_set_creds':
security/commoncap.c:510: error: 'PER_CLEAR_ON_SETID' undeclared (first use in this function)
security/commoncap.c:510: error: (Each undeclared identifier is reported only once
security/commoncap.c:510: error: for each function it appears in.)

Signed-off-by: Jonghwan Choi <jhbird.choi@samsung.com>
Acked-by: Serge Hallyn <serge.hallyn@canonical.com>
Signed-off-by: James Morris <james.l.morris@oracle.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>