openvswitch: fix linking without CONFIG_NF_CONNTRACK_LABELS
Message-id: <20190418125229.29158.40096.stgit@wsfd-netdev-buildsys.ntdv.lab.eng.bos.redhat.com>
Patchwork-id: 250491
O-Subject: [RHEL8.1 net PATCH 07/14] openvswitch: fix linking without CONFIG_NF_CONNTRACK_LABELS
Bugzilla: 1700468
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1700468
Upstream Status: Backport net.git commit a277d51
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21185973
Tested: Ran manual tests with OVS, including PVP, further ran kernel and OVS LNST.
  https://beaker.engineering.redhat.com/jobs/3479859
  https://beaker.engineering.redhat.com/jobs/3481362

Backport of upstream commit:

commit a277d516de5f498c91d91189717ef7e01102ad27
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 2 16:36:55 2018 +0100

    openvswitch: fix linking without CONFIG_NF_CONNTRACK_LABELS

    When CONFIG_CC_OPTIMIZE_FOR_DEBUGGING is enabled, the compiler
    fails to optimize out a dead code path, which leads to a link failure:

    net/openvswitch/conntrack.o: In function `ovs_ct_set_labels':
    conntrack.c:(.text+0x2e60): undefined reference to `nf_connlabels_replace'

    In this configuration, we can take a shortcut, and completely
    remove the contrack label code. This may also help the regular
    optimization.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>