bna: Replace large udelay() with mdelay()
Patchwork-id: 131259
O-Subject: [RHEL6.8 PATCH 07/46] bna: Replace large udelay() with mdelay()
Bugzilla: 1258535
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ: #1258535

Upstream commit(s):
commit bc48bc806442114ea44f61d6b18e02c2bd6236fd
Author: Ben Hutchings <ben@decadent.org.uk>
Date:   Sun Mar 9 04:03:22 2014 +0000

    bna: Replace large udelay() with mdelay()

    udelay() does not work on some architectures for values above
    2000, in particular on ARM:

    ERROR: "__bad_udelay" [drivers/net/ethernet/brocade/bna/bna.ko] undefined!

    Reported-by: Vagrant Cascadian <vagrant@debian.org>
    Signed-off-by: Ben Hutchings <ben@decadent.org.uk>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>