__force_order doesn't need to be an actual variable
Message-id: <1487170014-11002-95-git-send-email-bhe@redhat.com>
Patchwork-id: 166280
O-Subject: [RHEL7.4 PATCH v2 094/105] x86: __force_order doesn't need to be an actual variable
Bugzilla: 1290840
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Xunlei Pang <xpang@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This is back ported from upstream directly. Otherwise below building
error will happen.

arch/x86/boot/compressed/pagetable.c:26:15: error: non-static declaration of __force_order follows static declaration
 unsigned long __force_order;
               ^
In file included from ./arch/x86/include/asm/processor.h:23:0,
                 from ./arch/x86/include/asm/thread_info.h:22,
                 from include/linux/thread_info.h:54,
                 from ./arch/x86/include/asm/elf.h:7,
                 from include/linux/elf.h:4,
                 from arch/x86/boot/compressed/misc.h:16,
                 from arch/x86/boot/compressed/pagetable.c:18:
./arch/x86/include/asm/special_insns.h:21:22: note: previous declaration of __force_order was here
 static unsigned long __force_order;

commit 1d10f6ee602ec5a4bd0c1606ba5f38277da432e1
Author: Jan Beulich <JBeulich@suse.com>
Date:   Wed May 29 13:29:12 2013 +0100

    x86: __force_order doesn't need to be an actual variable

    It being static causes over a dozen instances to be scattered
    across the kernel image, with non of them ever being referenced
    in any way. Making the variable extern without ever defining it
    works as well - all we need is to have the compiler think the
    variable is being accessed.

    Signed-off-by: Jan Beulich <jbeulich@suse.com>
    Link: http://lkml.kernel.org/r/51A610B802000078000D99A0@nat28.tlf.novell.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>