enic: include irq.h for irqreturn_t definitions
Patchwork-id: 81954
O-Subject: [RHEL6.6 PATCH 15/19] net: enic: include irq.h for irqreturn_t definitions
Bugzilla: 1024064
RH-Acked-by: Nikolay Aleksandrov <nikolay@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Josh Boyer <jwboyer@gmail.com>

The enic driver fails to build on ARM with:

In file included from drivers/net/ethernet/cisco/enic/enic_res.c:40:0:
drivers/net/ethernet/cisco/enic/enic.h:48:2: error: expected specifier-qualifier-list before 'irqreturn_t'
  irqreturn_t (*isr)(int, void *);
  ^

Nothing in the driver is explicitly including the irq definitions, so we add
an include of linux/irq.h to pick them up.

Signed-off-by: Josh Boyer <jwboyer@fedoraproject.org>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit fef1f07cbf3d9b6f79beac8575554476c02c7f54)

Signed-off-by: Rafael Aquini <aquini@redhat.com>