perf evlist: Remove extraneous 'was' on error message
Patchwork-id: 127464
O-Subject: [PATCH RHEL6 BZ1265262 160/210] perf evlist: Remove extraneous 'was' on error message
Bugzilla: 1265262
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1265262
https://bugzilla.redhat.com/show_bug.cgi?id=1265262

upstream
========
commit 267b677eec06de178558337f0074e30ec3d11d9b
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Jan 19 11:54:06 2015 -0300

description
===========
  [acme@mica ~]$ trace -p 3330
  Error:  Unable to find debugfs
  Hint:   Was your kernel was compiled with debugfs support?
                          ^^^
                          ^^^
  Hint:   Is the debugfs filesystem mounted?
  Hint:   Try 'sudo mount -t debugfs nodev /sys/kernel/debug'

Fix it.

Signed-off-by: Aristeu Rozanski <aris@redhat.com>