perf annotate: Fix a build error
Patchwork-id: 49845
O-Subject: [PATCH RHEL6.4 BZ846702 061/198] perf annotate: Fix a build error
Bugzilla: 846702
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 846702
https://bugzilla.redhat.com/show_bug.cgi?id=846702

upstream status
===============
commit a31b7cc083b1d3d15bd475729fc4471685ebc5f6
Author: Namhyung Kim <namhyung@gmail.com>
Date:   Wed Apr 11 17:04:59 2012 -0300

description
===========
    CC util/annotate.o
util/annotate.c: In function symbol__annotate:
util/annotate.c:87:16: error: parsed_line may be used uninitialized in this function [-Werror=maybe-uninitialized]
util/annotate.c:211:22: note: parsed_line was declared here
cc1: all warnings being treated as errors
make: *** [util/annotate.o] Error 1
make: *** Waiting for unfinished jobs....