build: Include noarch in 'rh-rpms' based builds
Patchwork-id: 35750
O-Subject: [RHEL6 PATCH] RedHat Infrastructure: Include noarch in 'rh-rpms'
	based builds
Bugzilla:
RH-Acked-by: Jarod Wilson <jwilson@redhat.com>
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Johannes Weiner <jweiner@redhat.com>

Bugzilla: N/A (patch related to internal git tree content)
Brew build: https://brewweb.devel.redhat.com/taskinfo?taskID=3297659
Upstream commit: N/A (patch related to internal git tree content)

Generating RPMs via 'make [-C redhat] rh-rpms' only builds the
architecture dependent components.  Attempting to install such a kernel
package onto a target system may encounter an error due to an
unsatisfied dependency on the kernel-firmware package:
  # rpm -ihv kernel-2.6.32-141.el6.rhbz698162.x86_64.rpm
  error: Failed dependencies:
  kernel-firmware >= 2.6.32-141.el6.rhbz698162 is needed by
  kernel-2.6.32-141.el6.rhbz698162.x86_64

While one may be able to work around this dependency by installing
with the '--nodeps' option, doing such runs the risk of devices, such
as networking, no longer functioning due to not having thier appropriate
firmware files accessable (or updated versions thereof).

This patch adds an additional '--target' specifier to the Makefile's
'rh-rpms' target to include building the 'noarch' packages -
the kernel-firmware package resides within noarch - also.

Testing results: building via 'make rh-rpms' on an x86_64 system
with this patch generated the additional 'noarch' targets
kernel-doc-2.6.32-141.el6.noarch.rpm, and
kernel-firmware-2.6.32-141.el6.noarch.rpm.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>