libbpf: Fix compile error in libbpf_attach_type_by_name
Message-id: <20190604085256.3304-261-yauheni.kaliuta@redhat.com>
Patchwork-id: 262257
O-Subject: [RHEL8.1 PATCH v2 261/627] libbpf: Fix compile error in libbpf_attach_type_by_name
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 3615353218744bb60f55170c620ce4dce1a008c7
Author: Andrey Ignatov <rdna@fb.com>
Date:   Wed Oct 31 12:57:18 2018 -0700

    libbpf: Fix compile error in libbpf_attach_type_by_name

    Arnaldo Carvalho de Melo reported build error in libbpf when clang
    version 3.8.1-24 (tags/RELEASE_381/final) is used:

    libbpf.c:2201:36: error: comparison of constant -22 with expression of
    type 'const enum bpf_attach_type' is always false
    [-Werror,-Wtautological-constant-out-of-range-compare]
                    if (section_names[i].attach_type == -EINVAL)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~
    1 error generated.

    Fix the error by keeping "is_attachable" property of a program in a
    separate struct field instead of trying to use attach_type itself.

    Fixes: 956b620fcf0b ("libbpf: Introduce libbpf_attach_type_by_name")
    Reported-by: Arnaldo Carvalho de Melo <acme@kernel.org>
    Signed-off-by: Andrey Ignatov <rdna@fb.com>
    Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>