perf top: Fix uninitialized 'counter' variable
Patchwork-id: 36567
O-Subject: [PATCH RHEL6.2 BZ691343 124/142] perf top: Fix uninitialized 'counter' variable
Bugzilla: 691343
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 691343
https://bugzilla.redhat.com/show_bug.cgi?id=691343

upstream status
---------------
commit ce2d17ca7f85dcade62cd608601a0d52ccdaf0e6
Author: Akihiro Nagai <akihiro.nagai.hw@hitachi.com>
Date:   Wed Mar 23 16:29:39 2011 +0900

description
-----------
builtin-top.c has an uninitialized variable.
gcc(version 4.5.1) warns about it and it results in build failure:

 builtin-top.c: In function 'display_thread':
 builtin-top.c:518:9: error: 'counter' may be used uninitialized

This situation can indeed trigger, if the getline() call in
prompt_integer() fails.

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>