bpf: fix build error in libbpf with EXTRA_CFLAGS="-Wp, -D_FORTIFY_SOURCE=2 -O2"
Message-id: <20190510101556.20954-24-ivecera@redhat.com>
Patchwork-id: 254782
O-Subject: [RHEL8.1 PATCH 23/26] bpf: fix build error in libbpf with EXTRA_CFLAGS="-Wp, -D_FORTIFY_SOURCE=2 -O2"
Bugzilla: 1708560
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1708560

Upstream commit(s):
commit 1ce6a9fc154935d9db771173ecde03fa9b42df4a
Author: Thomas Richter <tmricht@linux.ibm.com>
Date:   Mon Jul 30 10:53:23 2018 +0200

    bpf: fix build error in libbpf with EXTRA_CFLAGS="-Wp, -D_FORTIFY_SOURCE=2 -O2"

    Commit 531b014e7a2f ("tools: bpf: make use of reallocarray") causes
    a compiler error when building the perf tool in the linux-next tree.
    Compile file tools/lib/bpf/libbpf.c on a FEDORA 28 installation with
    gcc compiler version: gcc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)
    shows this error message:

      [root@p23lp27] # make V=1 EXTRA_CFLAGS="-Wp,-D_FORTIFY_SOURCE=2 -O2"
      [...]
      make -f /home6/tmricht/linux-next/tools/build/Makefile.build
            dir=./util/scripting-engines obj=libperf
      libbpf.c: In function ‘bpf_object__elf_collect’:
      libbpf.c:811:15: error: ignoring return value of ‘strerror_r’,
                    declared with attribute warn_unused_result [-Werror=unused-result]
           strerror_r(-err, errmsg, sizeof(errmsg));
                     ^
      cc1: all warnings being treated as errors
      mv: cannot stat './.libbpf.o.tmp': No such file or directory
      /home6/tmricht/linux-next/tools/build/Makefile.build:96: recipe for target 'libbpf.o' failed

    Replace all occurrences of strerror() by calls to strerror_r(). To
    keep the compiler quiet also use the return value from strerror_r()
    otherwise a 'variable set but not use' warning which is treated as
    error terminates the compile.

    Fixes: 531b014e7a2f ("tools: bpf: make use of reallocarray")
    Suggested-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Suggested-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: Thomas Richter <tmricht@linux.ibm.com>
    Reviewed-by: Hendrik Brueckner <brueckner@linux.ibm.com>
    Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>