uio-hv-generic: store physical addresses instead of virtual
Message-id: <20170302102314.7978-6-vkuznets@redhat.com>
Patchwork-id: 169198
O-Subject: [RHEL7.4 KERNEL PATCH 5/8] uio-hv-generic: store physical addresses instead of virtual
Bugzilla: 1396534
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Cathy Avery <cavery@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

commit 190cc65e912de7e8f7ebddcecfbf55a610281a8c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Dec 9 12:44:40 2016 +0100

    uio-hv-generic: store physical addresses instead of virtual

    gcc warns about the newly added driver when phys_addr_t is wider than
    a pointer:

    drivers/uio/uio_hv_generic.c: In function 'hv_uio_mmap':
    drivers/uio/uio_hv_generic.c:71:17: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
        virt_to_phys((void *)info->mem[mi].addr) >> PAGE_SHIFT,
    drivers/uio/uio_hv_generic.c: In function 'hv_uio_probe':
    drivers/uio/uio_hv_generic.c:140:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
       = (phys_addr_t)dev->channel->ringbuffer_pages;
    drivers/uio/uio_hv_generic.c:147:3: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
       (phys_addr_t)vmbus_connection.int_page;
    drivers/uio/uio_hv_generic.c:153:3: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
       (phys_addr_t)vmbus_connection.monitor_pages[1];

    I can't see why we store a virtual address in a phys_addr_t here,
    as the only user of that variable converts it into a physical
    address anyway, so this moves the conversion to where it logically
    fits according to the types.

    Fixes: 95096f2fbd10 ("uio-hv-generic: new userspace i/o driver for VMBus")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Stephen Hemminger <sthemmin@microsoft.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>