build: Fix feature-libunwind-debug-frame handling
Patchwork-id: 99735
O-Subject: [PATCH RHEL6.7 BZ1159929 303/320] tools/perf/build: Fix feature-libunwind-debug-frame handling
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit e310718d0e83aeb9969264dc577c45db16d9104d
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Nov 14 08:25:24 2013 +0100

RHEL6
=====
The config/feature-checks/test-all.c was already missing
in RHEL6 code, due to upstream Merge conflict fixies during
time this feature was introduced.

description
===========
Set feature-libunwind-debug-frame. We don't want it in
CORE_FEATURE_TESTS because it's not the generic case, but we
need to set it in the !feature-libunwind case.

Also, because x86 distributions typically don't have
dwarf_find_debug_frame() unwinding method:

  test-libunwind-debug-frame.c:(.text+0x31): undefined reference to `_Ux86_64_dwarf_find_debug_frame'

Restrict this new API to ARM for the time being.

With this patch test-all.c works again, so repeat perf builds
are  fast again:

  comet:~/tip> perf stat --null --repeat 5 make -C tools/perf/
  [...]

       0,452899660 seconds time elapsed                                          ( +-  0,11% )

While with before it was:

  comet:~/tip> perf stat --null --repeat 5 make -C tools/perf/
  [...]

       1,674001829 seconds time elapsed                                          ( +-  0,16% )

[ Includes fix to config/feature-checks/Makefile from Will Deacon. ]

Signed-off-by: Rafael Aquini <aquini@redhat.com>