perf: Fix a compiling error in trace-event-perl.c for 32 bits machine
Patchwork-id: 57981
O-Subject: [PATCH RHEL6.5 BZ927866 163/264] perf tools: Fix a compiling error in trace-event-perl.c for 32 bits machine
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Feng Tang <feng.tang@intel.com>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit b1ab1bd1921536c2a97adb888effeff4370a3246
Author: Feng Tang <feng.tang@intel.com>
Date:   Thu Sep 20 08:30:21 2012 -0300

description
===========
On my x86_32 mahcine, there is a compile error:

        CC util/scripting-engines/trace-event-perl.o
        cc1: warnings being treated as errors
        util/scripting-engines/trace-event-perl.c: In function
	perl_process_tracepoint:
        util/scripting-engines/trace-event-perl.c:285: error: format
	expects type 'int', but argument 2 has type '__u64'
        make: *** [util/scripting-engines/trace-event-perl.o] Error 1

Fix it by using the "%PRIu64" for __u64.

v2: use PRIu64 as suggested by Arnaldo.