Fix warnings in drivers/pcmcia/socket_sysfs.c
Patchwork-id: 26169
O-Subject: [RHEL6 PATCH BZ 603733 45/59] Fix warnings in
	drivers/pcmcia/socket_sysfs.c
Bugzilla: 603733
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>

Fixes

drivers/pcmcia/socket_sysfs.c:368: error: initialization from incompatible pointer type
drivers/pcmcia/socket_sysfs.c:369: error: initialization from incompatible pointer type

(found during move to 2.6.32-33.el6)

rhel6 commit fa732287593cc76d7bb91d05b86b1dba666190f1 introduced a file pointer
to the read and write function pointers in the bin_attribute structure.  This
"broke" the compile.

RHEL6 only.

Resolves BZ 603733.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>