bridge: fix a conflict in if_bridge.h with glibc headers
Patchwork-id: 64776
O-Subject: [RHEL6 Patch net] bridge: fix a conflict in if_bridge.h with glibc headers
Bugzilla: 981325
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=981325
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=6100164

The inclusion of <linux/in6.h> breaks the build of NetworkManager:

In file included from /usr/include/linux/if_bridge.h:17,
                 from nm-system.c:47:
/usr/include/linux/in6.h:31: error: redefinition of 'struct in6_addr'
/usr/include/linux/in6.h:48: error: redefinition of 'struct sockaddr_in6'
/usr/include/linux/in6.h:56: error: redefinition of 'struct ipv6_mreq'

this is due to the glibc header <netinet/in.h> also defines
these structs, therefore conflict with the kernel definitions.

The real solution should be teaching glibc header to be aware
of kernel definitions, however this requires changes in both glibc
and kernel. For short term, a quick fix is just adding
__KERNEL__ to prevent user-space seeing it, since at least no one
complains this before.

Upstream should use the long term solution, therefore doesn't need this.
(Carlos already had a patch for this.)

Verified by myself, user-space can't see this #include after this patch.

Signed-off-by: Cong Wang <amwang@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>