tools: Fix build against newer glibc
Patchwork-id: 42258
O-Subject: [PATCH RHEL6.3 BZ752353 49/65] perf tools: Fix build against newer
	glibc
Bugzilla: 752353
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 752353
https://bugzilla.redhat.com/show_bug.cgi?id=752353

upstream status
===============
commit 195bcbf5078d74c8e00d68f04eb8695196fb31e8
Author: Josh Boyer <jwboyer@redhat.com>
Date:   Thu Aug 18 07:37:21 2011 -0400

description
===========
Upstream glibc commit 295e904 added a definition for __attribute_const__
to cdefs.h.  This causes the following error when building perf:

util/include/linux/compiler.h:8:0: error: "__attribute_const__"
redefined [-Werror] /usr/include/sys/cdefs.h:226:0: note: this is the
location of the previous definition

Wrap __attribute_const__ in #ifndef as we do for __always_inline.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>