kvm: ppc: do not compile in vfio.o unconditionally
Message-id: <1481299762-7424-7-git-send-email-thuth@redhat.com>
Patchwork-id: 161269
O-Subject: [RHEL7.4 kvm PATCH 6/7] KVM: PPC: do not compile in vfio.o unconditionally
Bugzilla: 1399880
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1399880
Upstream Status: commit 0af574be32cddf8d0c2fbb194dcc635e73a83f1e

commit 0af574be32cddf8d0c2fbb194dcc635e73a83f1e
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Mon Mar 21 15:05:17 2016 +0100

    KVM: PPC: do not compile in vfio.o unconditionally

    Build on 32-bit PPC fails with the following error:

     int kvm_vfio_ops_init(void)
          ^
     In file included from arch/powerpc/kvm/../../../virt/kvm/vfio.c:21:0:
     arch/powerpc/kvm/../../../virt/kvm/vfio.h:8:90: note: previous definition of kvm_vfio_op
     arch/powerpc/kvm/../../../virt/kvm/vfio.c:292:6: error: redefinition of kvm_vfio_ops_exi
     void kvm_vfio_ops_exit(void)
                 ^
     In file included from arch/powerpc/kvm/../../../virt/kvm/vfio.c:21:0:
     arch/powerpc/kvm/../../../virt/kvm/vfio.h:12:91: note: previous definition of kvm_vfio_o
     scripts/Makefile.build:258: recipe for target arch/powerpc/kvm/../../../virt/kvm/vfio.o f
     make[3]: *** [arch/powerpc/kvm/../../../virt/kvm/vfio.o] Error 1

    Check whether CONFIG_KVM_VFIO is set before including vfio.o
    in the build.

    Reported-by: Pranith Kumar <bobby.prani@gmail.com>
    Tested-by: Pranith Kumar <bobby.prani@gmail.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>