Improve filesystem freezing handling
Patchwork-id: 52419
O-Subject: [RHEL6.4 PATCH 17/34] fs: Improve filesystem freezing handling
Bugzilla: 768304
RH-Acked-by: Dave Chinner <dchinner@redhat.com>

Resolves: BZ 768304 - Deadlock occurs under a race with "flush" kthread and ioctl() to thaw ext3, ext4, and xfs filesystems.

This is a backport of the following upstream commit:

commit 5accdf82ba25cacefd6c1867f1704beb4d244cdd
Author: Jan Kara <jack@suse.cz>
Date:   Tue Jun 12 16:20:34 2012 +0200

    fs: Improve filesystem freezing handling

    vfs_check_frozen() tests are racy since the filesystem can be frozen just after
    the test is performed. Thus in write paths we can end up marking some pages or
    inodes dirty even though the file system is already frozen. This creates
    problems with flusher thread hanging on frozen filesystem.

    Another problem is that exclusion between ->page_mkwrite() and filesystem
    freezing has been handled by setting page dirty and then verifying s_frozen.
    This guaranteed that either the freezing code sees the faulted page, writes it,
    and writeprotects it again or we see s_frozen set and bail out of page fault.
    This works to protect from page being marked writeable while filesystem
    freezing is running but has an unpleasant artefact of leaving dirty (although
    unmodified and writeprotected) pages on frozen filesystem resulting in similar
    problems with flusher thread as the first problem.

    This patch aims at providing exclusion between write paths and filesystem
    freezing. We implement a writer-freeze read-write semaphore in the superblock.
    Actually, there are three such semaphores because of lock ranking reasons - one
    for page fault handlers (->page_mkwrite), one for all other writers, and one of
    internal filesystem purposes (used e.g. to track running transactions).  Write
    paths which should block freezing (e.g. directory operations, ->aio_write(),
    ->page_mkwrite) hold reader side of the semaphore. Code freezing the filesystem
    takes the writer side.

    Only that we don't really want to bounce cachelines of the semaphores between
    CPUs for each write happening. So we implement the reader side of the semaphore
    as a per-cpu counter and the writer side is implemented using s_writers.frozen
    superblock field.

    [AV: microoptimize sb_start_write(); we want it fast in normal case]

    BugLink: https://bugs.launchpad.net/bugs/897421
    Tested-by: Kamal Mostafa <kamal@canonical.com>
    Tested-by: Peter M. Petrakis <peter.petrakis@canonical.com>
    Tested-by: Dann Frazier <dann.frazier@canonical.com>
    Tested-by: Massimo Morana <massimo.morana@canonical.com>
    Signed-off-by: Jan Kara <jack@suse.cz>
    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

Note: Also adds GENKSYMS tricks for kmem.h header, which fixes this failure due
to the new includes in fs.h:

cc1: warnings being treated as errors
In file included from include/linux/kmemtrace.h:12,
                 from include/linux/slab_def.h:17,
                 from include/linux/slab.h:166,
                 from include/linux/percpu.h:5,
                 from include/linux/percpu_counter.h:13,
                 from include/linux/fs.h:413,
                 from kernel/events/core.c:12:
include/trace/events/kmem.h:528: error: ‘struct address_space’ declared inside parameter list
include/trace/events/kmem.h:528: error: its scope is only this definition or declaration, which is probably not what you want
include/trace/events/kmem.h:528: error: ‘struct address_space’ declared inside parameter list
include/trace/events/kmem.h:528: error: ‘struct address_space’ declared inside parameter list

We have unique RHEL6 headers which lead to this and need the workaround.

Signed-off-by: Jarod Wilson <jarod@redhat.com>