net/mlx5_en: Add missing check for memory allocation failure
Patchwork-id: 131968
O-Subject: [RHEL6.8 PATCH V2 014/117] net/mlx5_en: Add missing check for memory allocation failure
Bugzilla: 1246031
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Amir Vadai <amirv@mellanox.com>

The patch afb736e9330a: "net/mlx5: Ethernet resource handling files"
from May 28, 2015, leads to the following static checker warning:

drivers/net/ethernet/mellanox/mlx5/core/en_flow_table.c:726 mlx5e_create_main_flow_table()
error: potential null dereference 'g'.  (kcalloc returns null)

Fixes: afb736e9330a ("net/mlx5: Ethernet resource handling files")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Amir Vadai <amirv@mellanox.com>
Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5e24851ec502334986c2ac775beb4b7184a0b6c5)
Signed-off-by: Kamal Heib <kheib@redhat.com>

Signed-off-by: Aristeu Rozanski <aris@redhat.com>