list_nulls: fix missing header
Message-id: <20170314164348.17024-2-ivecera@redhat.com>
Patchwork-id: 174222
O-Subject: [RHEL7.4 net PATCH 01/23] list_nulls: fix missing header
Bugzilla: 1382040
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1382040

Upstream commit(s):
commit a3449ded128d037e6b2bd7a59b0741de56506066
Author: Ying Xue <ying.xue@windriver.com>
Date:   Sun Jan 4 15:24:35 2015 +0800

    list_nulls: fix missing header

    Fixup below build error:

    include/linux/list_nulls.h: In function 'hlist_nulls_del':
    include/linux/list_nulls.h:84:13: error: 'LIST_POISON2' undeclared (first use in this function)

    Signed-off-by: Ying Xue <ying.xue@windriver.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>