Add iommu_init to x86_init_ops, fix build
Patchwork-id: 107563
O-Subject: [PATCH RHEL6 12/27] x86: Add iommu_init to x86_init_ops, fix build
Bugzilla: 1198380
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

From: Ingo Molnar <mingo@elte.hu>

Most of the time x86_init.h is included in pci-dma.c - but not always,
leading to this rare build failure:

arch/x86/kernel/pci-dma.c:296: error: 'x86_init' undeclared (first use in this function)

So include asm/x86_init.h explicitly.

Cc: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>
Cc: chrisw@sous-sol.org
Cc: dwmw2@infradead.org
Cc: joerg.roedel@amd.com
Cc: muli@il.ibm.com
LKML-Reference: <1257849980-22640-2-git-send-email-fujita.tomonori@lab.ntt.co.jp>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
(cherry picked from commit b4941a9a606f0131559cc040b64e8437ac7b32c5)
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>