percpu: should use is_vmalloc_addr()
Patchwork-id: 64792
O-Subject: [RHEL6.5 PATCH v3 16/19] NOMMU: percpu should use is_vmalloc_addr().
Bugzilla: 878312
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Dave Anderson <anderson@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Resolves: bz878312
https://bugzilla.redhat.com/show_bug.cgi?id=878312

This is a backport of upstream commit.

commit eac522ef438f8ea173569fd0469371bc5d317947
Author: David Howells <dhowells@redhat.com>
Date:   Mon Mar 28 12:53:29 2011 +0100

    NOMMU: percpu should use is_vmalloc_addr().

    per_cpu_ptr_to_phys() uses VMALLOC_START and VMALLOC_END to determine if an
    address is in the vmalloc() region or not.  This is incorrect on NOMMU as
    there is no real vmalloc() capability (vmalloc() is emulated by kmalloc()).

    The correct way to do this is to use is_vmalloc_addr().  This encapsulates the
    vmalloc() region test in MMU mode and just returns 0 in NOMMU mode.

    On FRV in NOMMU mode, the percpu compilation fails without this patch:

    mm/percpu.c: In function 'per_cpu_ptr_to_phys':
    mm/percpu.c:1011: error: 'VMALLOC_START' undeclared (first use in this function)
    mm/percpu.c:1011: error: (Each undeclared identifier is reported only once
    mm/percpu.c:1011: error: for each function it appears in.)
    mm/percpu.c:1012: error: 'VMALLOC_END' undeclared (first use in this function)
    mm/percpu.c:1018: warning: control reaches end of non-void function

    Signed-off-by: David Howells <dhowells@redhat.com>

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>