btrfs: avoid uninitialized variable warning
Message-id: <20170307000403.5752-151-billodo@redhat.com>
Patchwork-id: 171276
O-Subject: [RHEL7.4 PATCH BZ 1399590 150/485] btrfs: avoid uninitialized variable warning
Bugzilla: 1399590
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

Bugzilla: 1399590
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=12695624
Tested: Locally with fstests

Backport of the following upstream commit:

    commit f827ba9a641b481f01d1bdc0771a7afc3776cc0b
    Author: Arnd Bergmann <arnd@arndb.de>
    Date:   Mon Feb 22 22:53:20 2016 +0100

    btrfs: avoid uninitialized variable warning

    With CONFIG_SMP and CONFIG_PREEMPT both disabled, gcc decides
    to partially inline the get_state_failrec() function but cannot
    figure out that means the failrec pointer is always valid
    if the function returns success, which causes a harmless
    warning:

    fs/btrfs/extent_io.c: In function 'clean_io_failure':
    fs/btrfs/extent_io.c:2131:4: error: 'failrec' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    This marks get_state_failrec() and set_state_failrec() both
    as 'noinline', which avoids the warning in all cases for me,
    and seems less ugly than adding a fake initialization.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 47dc196ae719 ("btrfs: use proper type for failrec in extent_state")
    Signed-off-by: David Sterba <dsterba@suse.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>