perf top: Fix TUI compilation
Patchwork-id: 36489
O-Subject: [PATCH RHEL6.2 BZ691343 053/142] perf top: Fix TUI compilation
Bugzilla: 691343
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 691343
https://bugzilla.redhat.com/show_bug.cgi?id=691343

upstream status
---------------
commit cdb0861c85c03fe80f4da033aab69df949579dc6
Author: Yinghai Lu <yinghai@kernel.org>
Date:   Tue Feb 1 10:51:23 2011 -0800

description
-----------
> +	slsmg_write_nstring(width >= syme->map->dso->long_name_len ?
> +				syme->map->dso->long_name :
> +				syme->map->dso->short_name, width);

need update macro for that calling

util/ui/browsers/top.c: In function ‘perf_top_browser__write’:
util/ui/browsers/top.c:60:2: error: cast to pointer from integer of different size
util/ui/browsers/top.c:60:2: error: comparison between pointer and integer
util/ui/browsers/top.c:60:2: error: passing argument 1 of ‘SLsmg_write_nstring’ discards qualifiers from pointer target type
/usr/include/slang.h:1728:16: note: expected ‘char *’ but argument is of type ‘const char *’
make: *** [util/ui/browsers/top.o] Error 1

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>