acpica: macosx: Fix anonymous semaphore implementation
Message-id: <1487787876-10121-99-git-send-email-prarit@redhat.com>
Patchwork-id: 166842
O-Subject: [RHEL7.4 PATCH BZ 1425180 098/101] ACPICA: MacOSX: Fix anonymous semaphore implementation
Bugzilla: 1425180
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Al Stone <ahs3@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1425180

commit 6c9fd7eda78d0a153f9f57c44dc8761adc2cd501
Author: Lv Zheng <zetalog@gmail.com>
Date:   Tue Oct 18 03:02:40 2016 +0800

    ACPICA: MacOSX: Fix anonymous semaphore implementation

    ACPICA commit 01eb9a58f4cf6300a0feb838a02bc4b1895c76e8
    ACPICA commit de5b9c0ef1ccb264cbe57c88f6dd3fbf8229f907

    The following build errors can be seen for MacOSX builds:
    .../osunixxf.c:829:42: error: 'tmpnam' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Werror,-Wdeprecated-declarations]

    Using of temporal file name functions can easily result in bus errors on
    MacOSX. This patch implements anonymous semaphore using an automatic
    increasing number. Lv Zheng.

    Linux is not affected by this change.

    Link: https://github.com/acpica/acpica/commit/01eb9a58
    Link: https://github.com/acpica/acpica/commit/de5b9c0e
    Signed-off-by: Lv Zheng <lv.zheng@intel.com>
    Signed-off-by: Bob Moore <robert.moore@intel.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>