perf data: Fix building in 32 bit platform with libbabeltrace
Message-id: <1482322582-7586-133-git-send-email-jolsa@redhat.com>
Patchwork-id: 161867
O-Subject: [PATCH RHEL7.4 BZ1405101 132/197] perf data: Fix building in 32 bit platform with libbabeltrace
Bugzilla: 1405101
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1405101
https://bugzilla.redhat.com/show_bug.cgi?id=1405101

upstream
========
commit f2c8852e6e990fcab0d9e68de9d86e5fbea0b5dc
Author: Wang Nan <wangnan0@huawei.com>
Date: Wed Sep 28 03:58:46 2016 +0000

description
===========
On ARM32 building it report following error when we build with
libbabeltrace:

  util/data-convert-bt.c: In function 'add_bpf_output_values':
  util/data-convert-bt.c:440:3: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Werror=format]
  cc1: all warnings being treated as errors

Fix it by changing %lu to %zu.

Fixes: 6122d57e9f7c ("perf data: Support converting data from bpf_perf_event_output()")
Signed-off-by: Rafael Aquini <aquini@redhat.com>