tpm_tis: Add missing ifdef CONFIG_ACPI for pnp_acpi_device
Patchwork-id: 129693
O-Subject: [RHEL6.8 PATCH BZ1254015 114/118] tpm/tpm_tis: Add missing ifdef CONFIG_ACPI for pnp_acpi_device
Bugzilla: 1254015
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10222730
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1254015

	commit 961be7ef6963806cb978ccd6acf6bf84b0c63346
	Author: Peter Huewe <peterhuewe@gmx.de>
	Date:   Thu Jan 22 00:42:50 2015 +0100

	tpm/tpm_tis: Add missing ifdef CONFIG_ACPI for pnp_acpi_device

	This fixes a build failure if CONFIG_PNP is set but CONFIG_ACPI is not:
	drivers/char/tpm/tpm_tis.c: In function ?tpm_tis_pnp_init?:
	drivers/char/tpm/tpm_tis.c:912:45: error: invalid type argument of
	?->? (have ?int?)
	   acpi_dev_handle = pnp_acpi_device(pnp_dev)->handle;

	If CONFIG_PNPACPI is not set pnp_acpi_device is defined as 0 and thus
	accesing the handle is not possible.

	Fixes: 0dc553652102 ("tpm: fix raciness of PPI interface lookup")
	Reported-by: Jim Davis <jim.epost@gmail.com>
	Signed-off-by: Peter Huewe <peterhuewe@gmx.de>
	Signed-off-by: James Morris <james.l.morris@oracle.com>

Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>