rtsx: Explicitely include slab.h in rtsx_pci_sdmmc.c
Patchwork-id: 78103
O-Subject: [RHEL6.6 PATCH 10/43] mmc: rtsx: Explicitely include slab.h in rtsx_pci_sdmmc.c
Bugzilla: 1024205
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This fixes the following build error on some architectures (parisc at least):

drivers/mmc/host/rtsx_pci_sdmmc.c: In function 'sd_normal_rw':
drivers/mmc/host/rtsx_pci_sdmmc.c:448:2: error: implicit
declaration of function 'kzalloc'
[-Werror=implicit-function-declaration]
drivers/mmc/host/rtsx_pci_sdmmc.c:448:6: warning: assignment
makes pointer from integer without a cast [enabled by default]
drivers/mmc/host/rtsx_pci_sdmmc.c:472:2: error: implicit
declaration of function 'kfree'
[-Werror=implicit-function-declaration]

Signed-off-by: Wei WANG <wei_wang@realsil.com.cn>
Acked-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
(cherry picked from commit 433e075c7f3b45c946c539ceeddc641c61adef5e)

BZ: 1024205
Brew:http://brewweb.devel.redhat.com/brew/taskinfo?taskID=7177291
Testing: Tested by Lenovo
Signed-off-by: Neil Horman <nhorman@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>