ghash-intel: ghash-clmulni-intel_glue needs err.h
Patchwork-id: 59798
O-Subject: [RHEL6 PATCH 10/51] crypto: ghash-intel - ghash-clmulni-intel_glue needs err.h
Bugzilla: 786972
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=786972

commit 52f6c5ad430e41736133acac179607b224eaaa11
Author: Randy Dunlap <randy.dunlap@oracle.com>
Date:   Wed Dec 15 17:58:57 2010 +0800

    crypto: ghash-intel - ghash-clmulni-intel_glue needs err.h

    Add missing header file:

    arch/x86/crypto/ghash-clmulni-intel_glue.c:256: error: implicit declaration of function 'IS_ERR'
    arch/x86/crypto/ghash-clmulni-intel_glue.c:257: error: implicit declaration of function 'PTR_ERR'

    Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Jarod Wilson <jarod@redhat.com>