mpt2sas: fix undefined reference to `__udivdi3' compilation errors
Patchwork-id: 104401
O-Subject: [RHEL6.7 e-stor PATCH 40/54] mpt2sas: fix undefined reference to `__udivdi3' compilation errors
Bugzilla: 1059155
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rob Evers <revers@redhat.com>

This patch will fix the below compilation errors on i386 ARCH

drivers/built-in.o: In function `_scsih_qcmd':
mpt2sas_scsih.c:(.text+0x1e7b56): undefined reference to `__udivdi3'
mpt2sas_scsih.c:(.text+0x1e7b8a): undefined reference to `__umoddi3'

Used sector_div() API to fix above compilation errors.

Signed-off-by: Sreekanth Reddy <Sreekanth.Reddy@avagotech.com>
Reviewed-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit f78f694c34ae6fdc29f5e80abb2dbb894f961772)

Signed-off-by: Rafael Aquini <aquini@redhat.com>