Store return Value of xchg() to supress compiler warning
Patchwork-id: 36220
O-Subject: [RHEL6.2 PATCH 09/30] Store return Value of xchg() to supress
	compiler warning
Bugzilla: 707755
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

BZ:707755

RHEL6 does not compile and gives warning if return value of xchg() is not
stored somewhere. Hence store it in a varaiable even though I don't need
to make use of it.

cc1: warnings being treated as errors
block/blk-throttle.c: In function ‘throtl_process_limit_change’:
block/blk-throttle.c:744: error: value computed is not used
block/blk-throttle.c: In function ‘throtl_update_blkio_group_common’:
block/blk-throttle.c:908: error: value computed is not used
block/blk-throttle.c:909: error: value computed is not used
make[1]: *** [block/blk-throttle.o] Error 1

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>