bpf: Fix dev pointer dereference from sk_skb
Message-id: <20190604085256.3304-302-yauheni.kaliuta@redhat.com>
Patchwork-id: 262294
O-Subject: [RHEL8.1 PATCH v2 302/627] bpf: Fix dev pointer dereference from sk_skb
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 67e89ac32828a29adc74e5c9bd59bd70943466f0
Author: Joe Stringer <joe@wand.net.nz>
Date:   Fri Oct 12 14:50:53 2018 -0700

    bpf: Fix dev pointer dereference from sk_skb

    Dan Carpenter reports:

    The patch 6acc9b432e67: "bpf: Add helper to retrieve socket in BPF"
    from Oct 2, 2018, leads to the following Smatch complaint:

        net/core/filter.c:4893 bpf_sk_lookup()
        error: we previously assumed 'skb->dev' could be null (see line 4885)

    Fix this issue by checking skb->dev before using it.

    Signed-off-by: Joe Stringer <joe@wand.net.nz>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>