perf svghelper: Fix unchecked usage of strncpy()
Message-id: <2ccca50bd456554722f5c01981f1559b7edd4690.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 264967
O-Subject: [RHEL8.1 BZ1715507 101/234] perf svghelper: Fix unchecked usage of strncpy()
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 2f5302533f306d5ee87bd375aef9ca35b91762cb
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Dec 6 11:29:48 2018 -0300

description
===========
The strncpy() function may leave the destination string buffer
unterminated, better use strlcpy() that we have a __weak fallback
implementation for systems without it.

In this specific case this would only happen if fgets() was buggy, as
its man page states that it should read one less byte than the size of
the destination buffer, so that it can put the nul byte at the end of
it, so it would never copy 255 non-nul chars, as fgets reads into the
orig buffer at most 254 non-nul chars and terminates it. But lets just
switch to strlcpy to keep the original intent and silence the gcc 8.2
warning.

This fixes this warning on an Alpine Linux Edge system with gcc 8.2:

  In function 'cpu_model',
      inlined from 'svg_cpu_box' at util/svghelper.c:378:2:
  util/svghelper.c:337:5: error: 'strncpy' output may be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]
       strncpy(cpu_m, &buf[13], 255);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: f48d55ce7871 ("perf: Add a SVG helper library file")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>