RDMA: Fix dependencies for rdma_user_mmap_io
Message-id: <20190429085929.13584-12-ahleihel@redhat.com>
Patchwork-id: 251771
O-Subject: [RHEL8.1 BZ 1691228 11/33] RDMA: Fix dependencies for rdma_user_mmap_io
Bugzilla: 1691233 1691228
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691233
Bugzilla: http://bugzilla.redhat.com/1691228
Upstream: v4.20-rc1

commit 46bdf777685677c1cc6b3da9220aace9da690731
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 26 21:36:52 2018 +0200

    RDMA: Fix dependencies for rdma_user_mmap_io

    The mlx4 driver produces a link error when it is configured
    as built-in while CONFIG_INFINIBAND_USER_ACCESS is set to =m:

    drivers/infiniband/hw/mlx4/main.o: In function `mlx4_ib_mmap':
    main.c:(.text+0x1af4): undefined reference to `rdma_user_mmap_io'

    The same function is called from mlx5, which already has a
    dependency to ensure we can call it, and from hns, which
    appears to suffer from the same problem.

    This adds the same dependency that mlx5 uses to the other two.

    Fixes: 6745d356ab39 ("RDMA/hns: Use rdma_user_mmap_io")
    Fixes: c282da4109e4 ("RDMA/mlx4: Use rdma_user_mmap_io")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>