x86/mce: Fix -Wmissing-prototypes warnings
Message-id: <20190423130801.43842-14-darcari@redhat.com>
Patchwork-id: 250616
O-Subject: [RHEL8.1 BZ 1698959 13/18] x86/mce: Fix -Wmissing-prototypes warnings
Bugzilla: 1698959
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Bhupesh Sharma <bhsharma@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1698959

commit 68b5e4326e4b8ac9080835005d8254fed0fb3c56
Author: Borislav Petkov <bp@suse.de>
Date:   Fri Nov 9 23:13:13 2018 +0100

    x86/mce: Fix -Wmissing-prototypes warnings

    Add the proper includes and make smca_get_name() static.

    Fix an actual bug too which the warning triggered:

      arch/x86/kernel/cpu/mcheck/therm_throt.c:395:39: error: conflicting \
      types for ‘smp_thermal_interrupt’
       asmlinkage __visible void __irq_entry smp_thermal_interrupt(struct pt_regs *r)
                                             ^~~~~~~~~~~~~~~~~~~~~
      In file included from arch/x86/kernel/cpu/mcheck/therm_throt.c:29:
      ./arch/x86/include/asm/traps.h:107:17: note: previous declaration of \
              ‘smp_thermal_interrupt’ was here
       asmlinkage void smp_thermal_interrupt(void);

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Yi Wang <wang.yi59@zte.com.cn>
    Cc: Michael Matz <matz@suse.de>
    Cc: x86@kernel.org
    Link: https://lkml.kernel.org/r/alpine.DEB.2.21.1811081633160.1549@nanos.tec.linutronix.de

Cc: Prarit Bhargava <prarit@redhat.com>
Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>