geneve: Initialize addr6 with memset
Message-id: <bb4f2b404c1838794128705f7c7776feed1c82d7.1559860349.git.sbrivio@redhat.com>
Patchwork-id: 263046
O-Subject: [RHEL8.1 net 6/6] geneve: Initialize addr6 with memset
Bugzilla: 1652222
RH-Acked-by: Guillaume Nault <gnault@redhat.com>
RH-Acked-by: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1652222
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22053074
Tested: with reproducer at https://bugzilla.redhat.com/show_bug.cgi?id=1511372#c7
	and net/pmtu.sh upstream selftest

commit 8a962c4aa1e6c0836985a5843f44d74fe3cced12
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Fri Nov 16 18:36:27 2018 -0700

    geneve: Initialize addr6 with memset

    Clang warns:

    drivers/net/geneve.c:428:29: error: suggest braces around initialization
    of subobject [-Werror,-Wmissing-braces]
                    struct in6_addr addr6 = { 0 };
                                              ^
                                              {}

    Rather than trying to appease the various compilers that support the
    kernel, use memset, which is unambiguous.

    Fixes: a07966447f39 ("geneve: ICMP error lookup handler")
    Suggested-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>