btrfs: Reset IO error counters before start of device replacing
Message-id: <20170307000403.5752-183-billodo@redhat.com>
Patchwork-id: 171361
O-Subject: [RHEL7.4 PATCH BZ 1399590 182/485] btrfs: Reset IO error counters before start of device replacing
Bugzilla: 1399590
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

Bugzilla: 1399590
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=12695624
Tested: Locally with fstests

Backport of the following upstream commit:

    commit 7ccefb98ce3e5c4493cd213cd03714b7149cf0cb
    Author: Yauhen Kharuzhy <yauhen.kharuzhy@zavadatar.com>
    Date:   Tue Mar 29 14:17:48 2016 -0700

    btrfs: Reset IO error counters before start of device replacing

    If device replace entry was found on disk at mounting and its num_write_errors
    stats counter has non-NULL value, then replace operation will never be
    finished and -EIO error will be reported by btrfs_scrub_dev() because
    this counter is never reset.

     # mount -o degraded /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
     # btrfs replace status /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
     Started on 25.Mar 07:28:00, canceled on 25.Mar 07:28:01 at 0.0%, 40 write errs, 0 uncorr. read errs
     # btrfs replace start -B 4 /dev/sdg /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
     ERROR: ioctl(DEV_REPLACE_START) failed on "/media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/": Input/output error, no error

    Reset num_write_errors and num_uncorrectable_read_errors counters in the
    dev_replace structure before start of replacing.

    Signed-off-by: Yauhen Kharuzhy <yauhen.kharuzhy@zavadatar.com>
    Reviewed-by: David Sterba <dsterba@suse.com>
    Signed-off-by: David Sterba <dsterba@suse.com>

Signed-off-by: Bill O'Donnell <billodo@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>