mlxsw: spectrum_router: avoid potential uninitialized data usage
Message-id: <20170411143300.8140-141-ivecera@redhat.com>
Patchwork-id: 176532
O-Subject: [RHEL7.4 PATCH v2 140/232] mlxsw: spectrum_router: avoid potential uninitialized data usage
Bugzilla: 1414400
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1414400

Upstream commit(s):
commit ab580705693d5af79663efa504a72248700766fc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Sep 30 18:17:10 2016 +0200

    mlxsw: spectrum_router: avoid potential uninitialized data usage

    If fi->fib_nhs is zero, the router interface pointer is uninitialized, as shown by
    this warning:

    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c: In function 'mlxsw_sp_router_fib_event':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:1674:21: error: 'r' may be used uninitialized in this function [-Werror=maybe-uninitialized]
    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:1643:23: note: 'r' was declared here

    This changes the loop so we handle the case the same way as finding no router
    interface pointer attached to one of the nexthops to ensure we always
    trap here instead of using uninitialized data.

    Fixes: b45f64d16d45 ("mlxsw: spectrum_router: Use FIB notifications instead of switchdev calls")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>