zram: fix build errors, depends on BLOCK
Patchwork-id: 30101
O-Subject: [RHEL6.1 PATCH 1/8] zram: fix build errors, depends on BLOCK
Bugzilla: 661293
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Vivek Goyal <vgoyal@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=661293

This is a backport of:

>From 8946a0864848fdbc6544b9e1e6cb81b7cb93026b Mon Sep 17 00:00:00 2001
From: Randy Dunlap <randy.dunlap@oracle.com>
Date: Wed, 23 Jun 2010 20:27:09 -0700
Subject: [PATCH] Staging: zram: fix build errors, depends on BLOCK

Fix 49 zram build errors in one swoop.  Examples:

drivers/staging/zram/zram_drv.c:225: error: dereferencing pointer to incomplete type
drivers/staging/zram/zram_drv.c:226: error: implicit declaration of function 'bio_for_each_segment'
drivers/staging/zram/zram_drv.c:226: error: expected ';' before '{' token
drivers/staging/zram/zram_drv.c:281: error: implicit declaration of function 'bio_endio'
drivers/staging/zram/zram_drv.c:285: error: implicit declaration of function 'bio_io_error'
drivers/staging/zram/zram_drv.c:545: error: implicit declaration of function 'set_capacity'
drivers/staging/zram/zram_drv.c:548: error: implicit declaration of function 'queue_flag_set_unlocked'
drivers/staging/zram/zram_drv.c:548: error: 'QUEUE_FLAG_NONROT' undeclared (first use in this function)
drivers/staging/zram/zram_drv.c:548: error: dereferencing pointer to incomplete type

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Nitin Gupta <ngupta@vflare.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Regards,
Jerome

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>