oprofile: fix init_sysfs() function stub
Patchwork-id: 30727
O-Subject: [RHEL 6.1 PATCH 28/55] oprofile, x86: fix init_sysfs() function stub
Bugzilla: 647750
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Robert Richter <robert.richter@amd.com>

commit 269f45c25028c75fe10e6d9be86e7202ab461fbc upstream.

The use of the return value of init_sysfs() with commit

 10f0412 oprofile, x86: fix init_sysfs error handling

discovered the following build error for !CONFIG_PM:

 .../linux/arch/x86/oprofile/nmi_int.c: In function op_nmi_init:
 .../linux/arch/x86/oprofile/nmi_int.c:784: error: expected expression before do
 make[2]: *** [arch/x86/oprofile/nmi_int.o] Error 1
 make[1]: *** [arch/x86/oprofile] Error 2

This patch fixes this.

Reported-by: Ingo Molnar <mingo@elte.hu>
Cc: stable@kernel.org
Signed-off-by: Robert Richter <robert.richter@amd.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>