keys: linux/key-type.h needs linux/errno.h
Patchwork-id: 127546
O-Subject: [RHEL6 PATCH 10/25] KEYS: linux/key-type.h needs linux/errno.h
Bugzilla: 1282745
RH-Acked-by: Steve Dickson <SteveD@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

linux/key-type.h needs to #include linux/errno.h as it refers to ENOKEY.
Without this, with sparc's allmodconfig in one of my test trees, the following
error occurs:

include/linux/key-type.h: In function 'key_negate_and_link':
include/linux/key-type.h:122:43: error: 'ENOKEY' undeclared (first use in this function)
include/linux/key-type.h:122:43: note: each undeclared identifier is reported only once for each fun

Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: David Howells <dhowells@redhat.com>
Signed-off-by: James Morris <james.l.morris@oracle.com>
Original-commit: 5935e6dcaaa8f666dd7f1169fa87d36752ebeb94
RH-Bugzilla: 1282745
Signed-off-by: Aristeu Rozanski <aris@redhat.com>