apei/ghes: 32-bit buildfix
Patchwork-id: 49486
O-Subject: [RHEL6.4 PATCH 11/14] APEI GHES: 32-bit buildfix
Bugzilla: 816496
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

Bugzilla: 816496  https://bugzilla.redhat.com/show_bug.cgi?id=816496
Upstream Status: commit 70cb6e1da00db6c9212e6fd69bd96fd41c797077

commit 70cb6e1da00db6c9212e6fd69bd96fd41c797077
Author: Len Brown <len.brown@intel.com>
Date:   Tue Aug 2 18:00:21 2011 -0400

APEI GHES: 32-bit buildfix

drivers/acpi/apei/ghes.c:542: warning: integer overflow in expression
drivers/acpi/apei/ghes.c:619: warning: integer overflow in expression

ghes.c:(.text+0x46289): undefined reference to `__udivdi3'
  in function ghes_estatus_cache_add().

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Len Brown <len.brown@intel.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>