Fix cross builds
Message-id: <20190402075204.9521-1-jolsa@redhat.com>
Patchwork-id: 248437
O-Subject: [PATCH RHEL8.1 BZ1694956] rpmspec: Fix cross builds
Bugzilla: 1694956
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Laura Abbott <labbott@redhat.com>

Bugzilla: 1694956
https://bugzilla.redhat.com/show_bug.cgi?id=1694956
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20753342
RHEL-only

Don Zickus and Major Hayden reported that cross compiling
is broken on rhel8 due to annocheck changes we took recently:

$ make rh-cross-s390x-rpms
...
+ make CROSS_COMPILE=s390x-linux-gnu- 'HOSTCFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=zEC12 -mtune=z13 -fasynchronous-unwind-tables -fstack-clash-protection' 'HOSTLDFLAGS=-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' -s ARCH=s390 oldnoconfig
cc1: error: bad value ('zEC12') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
cc1: error: bad value ('z13') for '-mtune=' switch
cc1: note: valid arguments to '-mtune=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 generic native
make[3]: *** [scripts/Makefile.host:90: scripts/basic/fixdep] Error 1
make[2]: *** [Makefile:457: scripts_basic] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.x7Wbzo (%build)

The reason is that we compile host helper applications with
cross compile flags, which fails.

Fedora had similar issue in past, we need to backport folowing code:
  https://marc.info/?l=fedora-extras-commits&m=153247934323688&w=2

Adjusting it to the rhel8 kernel.spec.

Cc: Herton R. Krzesinski <herton@redhat.com>
Cc: Don Zickus <dzickus@redhat.com>
Cc: Major Hayden <mhayden@redhat.com>
Signed-off-by: Jiri Olsa <jolsa@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>