ixgbe/ixgbevf: fix XFRM_ALGO dependency
Message-id: <20190509160321.7692-29-jkc@redhat.com>
Patchwork-id: 254216
O-Subject: [RHEL8.1 BZ 1659164 28/47] ixgbe/ixgbevf: fix XFRM_ALGO dependency
Bugzilla: 1659164
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1659164
Conflicts: ixgbe portion only

commit 48e01e001da31d5a40e31ed5f8cea83a18823cc1
Author: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
Date:   Thu Oct 18 15:39:43 2018 -0700

    ixgbe/ixgbevf: fix XFRM_ALGO dependency

    Based on the original work from Arnd Bergmann.

    When XFRM_ALGO is not enabled, the new ixgbe IPsec code produces a
    link error:

    drivers/net/ethernet/intel/ixgbe/ixgbe_ipsec.o: In function `ixgbe_ipsec_vf_add_sa':
    ixgbe_ipsec.c:(.text+0x1266): undefined reference to `xfrm_aead_get_byname'

    Simply selecting XFRM_ALGO from here causes circular dependencies, so
    to fix it, we probably want this slightly more complex solution that is
    similar to what other drivers with XFRM offload do:

    A separate Kconfig symbol now controls whether we include the IPsec
    offload code. To keep the old behavior, this is left as 'default y'. The
    dependency in XFRM_OFFLOAD still causes a circular dependency but is
    not actually needed because this symbol is not user visible, so removing
    that dependency on top makes it all work.

    CC: Arnd Bergmann <arnd@arndb.de>
    CC: Shannon Nelson <shannon.nelson@oracle.com>
    Fixes: eda0333ac293 ("ixgbe: add VF IPsec management")
    Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
    Tested-by: Andrew Bowers <andrewx.bowers@intel.com>

Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Cc: David Arcari <darcari@redhat.com>
Cc: Stefan Assmann <sassmann@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Cc: Jesper Dangaard Brouer <brouer@redhat.com>
Cc: Jiri Benc <jbenc@redhat.com>
Cc: Rashid Khan <rkhan@redhat.com>
Cc: Neil Horman <nhorman@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>