raid5: fix build error, sector_t usage
Patchwork-id: 39942
O-Subject: [Patch RHEL6.2 02/30] raid5: fix build error, sector_t usage
Bugzilla: 729696
RH-Acked-by: Jonathan E Brassow <jbrassow@redhat.com>

From: Randy Dunlap <randy.dunlap@oracle.com>

Change <sectors> from unsigned long long to sector_t.
This matches its source field.

  ERROR: "__udivdi3" [drivers/md/raid456.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit d76c8420c3cf8e468901b0bd58306637335c98ea)

Signed-off-by: Doug Ledford <dledford@redhat.com>
Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>