sched: Fix granularity of task_u/stime()
Patchwork-id: 35495
O-Subject: [RHEL6.1 PATCH] sched: Fix granularity of task_u/stime()
Bugzilla: 690998
RH-Acked-by: Oleg Nesterov <oleg@redhat.com>
RH-Acked-by: Amerigo Wang <amwang@redhat.com>
RH-Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=690998

This is straightforward backport of:

commit 761b1d26df542fd5eb348837351e4d2f3bc7bffe
Author: Hidetoshi Seto <seto.hidetoshi@jp.fujitsu.com>
Date:   Thu Nov 12 13:33:45 2009 +0900

    sched: Fix granularity of task_u/stime()

    Originally task_s/utime() were designed to return clock_t but
    later changed to return cputime_t by following commit:

      commit efe567fc8281661524ffa75477a7c4ca9b466c63
      Author: Christian Borntraeger <borntraeger@de.ibm.com>
      Date:   Thu Aug 23 15:18:02 2007 +0200

    It only changed the type of return value, but not the
    implementation. As the result the granularity of task_s/utime()
    is still that of clock_t, not that of cputime_t.

    So using task_s/utime() in __exit_signal() makes values
    accumulated to the signal struct to be rounded and coarse
    grained.

    This patch removes casts to clock_t in task_u/stime(), to keep
    granularity of cputime_t over the calculation.

    v2:
      Use div_u64() to avoid error "undefined reference to `__udivdi3`"
      on some 32bit systems.

    Signed-off-by: Hidetoshi Seto <seto.hidetoshi@jp.fujitsu.com>
    Acked-by: Peter Zijlstra <peterz@infradead.org>
    Cc: xiyou.wangcong@gmail.com
    Cc: Spencer Candland <spencer@bluehost.com>
    Cc: Oleg Nesterov <oleg@redhat.com>
    Cc: Stanislaw Gruszka <sgruszka@redhat.com>
    LKML-Reference: <4AFB9029.9000208@jp.fujitsu.com>
    Signed-off-by: Ingo Molnar <mingo@elte.hu>

Regards,
Jerome

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>