add extra free kbytes tunable
Patchwork-id: 40984
O-Subject: [RHEL 6.2 PATCH] mm: add extra free kbytes tunable
Bugzilla: 696395
RH-Acked-by: Satoru Moriya <smoriya@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Johannes Weiner <jweiner@redhat.com>

Fixes bug 696395

Upstream status: in -mm and -next

Why a tunable?  We cannot auto-discover that the size of our free
memory buffer is too small, because that would introduce the kind
of unacceptable latencies to userspace that this patch aims to
avoid.

commit a3b0f52a17a3073200b8b75a857da9cf31b662e7
Author: Rik van Riel <riel@redhat.com>
Date:   Wed Sep 28 10:50:21 2011 +1000

    mm: add extra free kbytes tunable

    Add a userspace visible knob to tell the VM to keep an extra amount of
    memory free, by increasing the gap between each zone's min and low
    watermarks.

    This is useful for realtime applications that call system calls and have a
    bound on the number of allocations that happen in any short time period.
    In this application, extra_free_kbytes would be left at an amount equal to
    or larger than than the maximum number of allocations that happen in any
    burst.

    It may also be useful to reduce the memory use of virtual machines
    (temporarily?), in a way that does not cause memory fragmentation like
    ballooning does.

    Signed-off-by: Rik van Riel<riel@redhat.com>
    Signed-off-by: Andrew Morton <>

commit 4d13e3c7c8b1c86f7a5fbd42197dfb22bf04dfaf
Author: Rik van Riel <riel@redhat.com>
Date:   Wed Sep 28 10:50:21 2011 +1000

    mm-add-extra-free-kbytes-tunable-update

    All the fixes suggested by Andrew Morton.   Not much of a changelog
    since the patch should probably be folded into
    mm-add-extra-free-kbytes-tunable.patch

    Thank you for pointing these out, Andrew.

    Signed-off-by: Rik van Riel <riel@redhat.com>
    Signed-off-by: Andrew Morton <>

commit a2944b51d1d270a35ad702490dffd6820e9d612b
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Wed Sep 28 10:50:22 2011 +1000

    mm-add-extra-free-kbytes-tunable-update-checkpatch-fixes

    ERROR: trailing whitespace
    #98: FILE: mm/page_alloc.c:5303:
    + * free_kbytes_sysctl_handler - just a wrapper around proc_dointvec() so $

    ERROR: trailing whitespace
    #103: FILE: mm/page_alloc.c:5307:
    +int free_kbytes_sysctl_handler(ctl_table *table, int write, $

    ERROR: need consistent spacing around '*' (ctx:WxV)
    #103: FILE: mm/page_alloc.c:5307:
    +int free_kbytes_sysctl_handler(ctl_table *table, int write,
                                              ^

    total: 3 errors, 0 warnings, 69 lines checked

    NOTE: whitespace errors detected, you may wish to use scripts/cleanpatch or
          scripts/cleanfile

    ./patches/mm-add-extra-free-kbytes-tunable-update.patch has style problems, please review.

    If any of these errors are false positives, please report
    them to the maintainer, see CHECKPATCH in MAINTAINERS.

    Please run checkpatch prior to sending patches

    Cc: Rik van Riel <riel@redhat.com>
    Signed-off-by: Andrew Morton <>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>