Fix warning in drivers/scsi/megaraid/megaraid_sas.c: process_fw_state_change_wq()
Patchwork-id: 26170
O-Subject: [RHEL6 PATCH BZ 603733 46/59] Fix warning in
	drivers/scsi/megaraid/megaraid_sas.c: process_fw_state_change_wq()
Bugzilla: 603733
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Larry Woodman <lwoodman@redhat.com>
RH-Acked-by: Rob Evers <revers@redhat.com>
RH-Acked-by: Tomas Henzl <thenzl@redhat.com>

Fixes

drivers/scsi/megaraid/megaraid_sas.c: In function 'process_fw_state_change_wq':
drivers/scsi/megaraid/megaraid_sas.c:2237: error: unused variable 'wait'

(found during move to 2.6.32-33.el6)

Not upstream.

RHEL6 only.

Resolves BZ 603733.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>