sort: Separate out branch stack specific sort keys
Patchwork-id: 71357
O-Subject: [PATCH RHEL6.6 BZ1034843 076/172] perf sort: Separate out branch stack specific sort keys
Bugzilla: 1034843
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: 1034843
https://bugzilla.redhat.com/show_bug.cgi?id=1034843

upstream
========
commit fc5871ed0dcf8c76dd1b3b36ff0f70112d2f0e74
Author: Namhyung Kim <namhyung.kim@lge.com>
Date: Thu Dec 27 18:11:46 2012 +0900

description
===========
Current perf report gets segmentation fault when a branch stack specific
sort key is provided by --sort option to a perf.data file which contains
no branch infomation.  It's because those sort keys reference branch
info of a hist entry unconditionally.  Maybe we can change it checks
whether such branch info is valid or not.  But if the branch stacks are
not recorded, it'd be nop.  Thus it'd be better to make those keys are
unselectable.

This patch separates those keys to a different dimension array, so that
if user passes such a key to a file which has no branch stack will get
following message rather than a segfault.

  Error: Invalid --sort key: `symbol_from'