python: Use exception to propagate errors
Patchwork-id: 38970
O-Subject: [PATCH RHEL6.2 BZ725522 62/67] perf python: Use exception to
	propagate errors
Bugzilla: 725522
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 725522
https://bugzilla.redhat.com/show_bug.cgi?id=725522

upstream status
---------------
commit 9c850d6c4b95bb07fb066eb7f43dd4e3b4842b85
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Thu Jun 2 10:55:10 2011 -0300

description
-----------
We were using pr_debug to tell the user about not being able to parse a sample
where we should really use the python way of reporting errors: exceptions.

Fixes this problem:

[root@emilia ~]# python
>>> import perf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/acme/git/build/perf/python/perf.so: undefined symbol: eprintf
>>>
[root@emilia ~]

As we want to keep the objects linked in the python binding (and in the future
in a shared library) minimal.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>