kexec: fix build error when hugetlbfs is disabled
Patchwork-id: 107026
O-Subject: [RHEL6.7 PATCH 4/4] kexec: fix build error when hugetlbfs is disabled
Bugzilla: 1121663
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>
RH-Acked-by: Dave Anderson <anderson@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Resolves: bz1121663
https://bugzilla.redhat.com/show_bug.cgi?id=1121663

This is back ported from upstream. In order to solve code conflict, adjust
the code position.

commit 3a1122d26c62d4e8c61ef9a0eaba6e21c0862c77
Author: David Rientjes <rientjes@google.com>
Date:   Wed Jul 30 19:05:55 2014 -0700

    kexec: fix build error when hugetlbfs is disabled

    free_huge_page() is undefined without CONFIG_HUGETLBFS and there's no
    need to filter PageHuge() page is such a configuration either, so avoid
    exporting the symbol to fix a build error:

       In file included from kernel/kexec.c:14:0:
       kernel/kexec.c: In function 'crash_save_vmcoreinfo_init':
       kernel/kexec.c:1623:20: error: 'free_huge_page' undeclared (first use in this function)
         VMCOREINFO_SYMBOL(free_huge_page);
                           ^

    Introduced by commit 8f1d26d0e59b ("kexec: export free_huge_page to
    VMCOREINFO")

    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Acked-by: Olof Johansson <olof@lixom.net>
    Cc: Atsushi Kumagai <kumagai-atsushi@mxc.nes.nec.co.jp>
    Cc: Baoquan He <bhe@redhat.com>
    Cc: Vivek Goyal <vgoyal@redhat.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: David Rientjes <rientjes@google.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Brew build:
https://brewweb.devel.redhat.com/taskinfo?taskID=8794090

Test: Passed on kvm guest.

Signed-off-by: Minfei Huang <mhuang@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>