bridge: add missing bridge port check for offloads
Message-id: <1465924603-6119-67-git-send-email-ivecera@redhat.com>
Patchwork-id: 152152
O-Subject: [RHEL7.3 net PATCH 066/570] bridge: add missing bridge port check for offloads
Bugzilla: 1275772 1297841 1331748
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Lance Richardson <lrichard@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

BZ#1297841

Upstream commit(s):
commit 1fd0bddb618aa970b87e7907a5703682aa119a6f
Author: Roopa Prabhu <roopa@cumulusnetworks.com>
Date:   Thu Feb 5 22:24:45 2015 -0800

    bridge: add missing bridge port check for offloads

    This patch fixes a missing bridge port check caught by smatch.

    setlink/dellink of attributes like vlans can come for a bridge device
    and there is no need to offload those today. So, this patch adds a bridge
    port check. (In these cases however, the BRIDGE_SELF flags will always be set
    and we may not hit a problem with the current code).

    smatch complaint:

    The patch 68e331c785b8: "bridge: offload bridge port attributes to
    switch asic if feature flag set" from Jan 29, 2015, leads to the
    following Smatch complaint:

    net/bridge/br_netlink.c:552 br_setlink()
    	 error: we previously assumed 'p' could be null (see line 518)

    net/bridge/br_netlink.c
       517
       518		if (p && protinfo) {
                        ^
    Check for NULL.

    Reported-By: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Roopa Prabhu <roopa@cumulusnetworks.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>