mlxsw: add DEVLINK dependencies
Message-id: <1472224621-22731-1-git-send-email-ivecera@redhat.com>
Patchwork-id: 157344
O-Subject: [RHEL-7.3 PATCH v2 506/571] net: mellanox: add DEVLINK dependencies
Bugzilla: 1275772 1297841 1331748
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1297841

Changes:
v2 - include whole upstream commit (including mlx4 parts)

Upstream commit(s):
commit 3d1cbe839ac3aa7b23a274b691092c90f9bf1b8e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Mar 2 10:40:54 2016 +0100

    net: mellanox: add DEVLINK dependencies

    The new NET_DEVLINK infrastructure can be a loadable module, but the drivers
    using it might be built-in, which causes link errors like:

    drivers/net/built-in.o: In function `mlx4_load_one':
    :(.text+0x2fbfda): undefined reference to `devlink_port_register'
    :(.text+0x2fc084): undefined reference to `devlink_port_unregister'
    drivers/net/built-in.o: In function `mlxsw_sx_port_remove':
    :(.text+0x33a03a): undefined reference to `devlink_port_type_clear'
    :(.text+0x33a04e): undefined reference to `devlink_port_unregister'

    There are multiple ways to avoid this:

    a) add 'depends on NET_DEVLINK || !NET_DEVLINK' dependencies
       for each user
    b) use 'select NET_DEVLINK' from each driver that uses it
       and hide the symbol in Kconfig.
    c) make NET_DEVLINK a 'bool' option so we don't have to
       list it as a dependency, and rely on the APIs to be
       stubbed out when it is disabled
    d) use IS_REACHABLE() rather than IS_ENABLED() to check for
       NET_DEVLINK in include/net/devlink.h

    This implements a variation of approach a) by adding an
    intermediate symbol that drivers can depend on, and changes
    the three drivers using it.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 09d4d087cd48 ("mlx4: Implement devlink interface")
    Fixes: c4745500e988 ("mlxsw: Implement devlink interface")
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>