alsa: timer: Adjust a condition check in snd_timer_resolution()
Patchwork-id: 186293
O-Subject: [RHEL 7.5 PATCH v3 09/10] ALSA: timer: Adjust a condition check in snd_timer_resolution()
Bugzilla: 1465999
Z-Bugzilla: 1465998
CVE: CVE-2017-1000380
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code place.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit dd1f7ab8a88ddc8fbb304aaca25f549e26fa8529)
Bugzilla: 1465999
Signed-off-by: Denys Vlasenko <dvlasenk@redhat.com>