xhci: Fix compile error when CONFIG_PM=n
Patchwork-id: 30311
O-Subject: [RHEL6 PATCH 098/107] USB: xhci: Fix compile error when CONFIG_PM=n
Bugzilla: 591794 591796 591797 624615 637237
RH-Acked-by: Bob Picco <bpicco@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=591794
https://bugzilla.redhat.com/show_bug.cgi?id=591796
https://bugzilla.redhat.com/show_bug.cgi?id=591797
https://bugzilla.redhat.com/show_bug.cgi?id=637237
https://bugzilla.redhat.com/show_bug.cgi?id=624615

commit b5b5c3ac5123dab047cfeff472053ab737052e9b
Author: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Date:   Fri Oct 15 11:24:14 2010 -0700

    USB: xhci: Fix compile error when CONFIG_PM=n

    Fix this error when CONFIG_PM is not enabled:

    drivers/usb/host/xhci.c:675: error: implicit declaration of function 'usb_root_hub_lost_power'

    Wrap xhci_suspend() and xhci_resume() into an ifdef CONFIG_PM, along with
    the functions that only they call -- xhci_save_registers() and
    xhci_restore_registers().

    Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>