tpm_tis: fix build when ACPI is not enabled
Patchwork-id: 129674
O-Subject: [RHEL6.8 PATCH BZ1254015 031/118] tpm_tis: fix build when ACPI is not enabled
Bugzilla: 1254015
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10222730
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1254015

	commit 1560ffe62a9d53a51faeec7417becfba4f2a0d18
	Author: Randy Dunlap <rdunlap@xenotime.net>
	Date:   Wed Aug 3 16:21:11 2011 -0700

	tpm_tis: fix build when ACPI is not enabled

	Fix tpm_tis.c build when CONFIG_ACPI is not enabled by providing a stub
	function.  Fixes many build errors/warnings:

	  drivers/char/tpm/tpm_tis.c:89: error: dereferencing pointer to incomplete type
	  drivers/char/tpm/tpm_tis.c:89: warning: type defaults to 'int' in declaration of 'type name'
	  drivers/char/tpm/tpm_tis.c:89: error: request for member 'list' in something not a structure or union
	  ...

	Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
	Cc: Leendert van Doorn <leendert@watson.ibm.com>
	Cc: James Morris <jmorris@namei.org>
	Cc: Ingo Molnar <mingo@elte.hu>
	Cc: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>