perf tools: Fix tracing_path_mount proper path
Message-id: <1230f06fcd67ffa2a177993f13e8c6af5e75bfe6.1558604935.git.mpetlan@redhat.com>
Patchwork-id: 259853
O-Subject: [RHEL8.1 BZ1709242 185/190] perf tools: Fix tracing_path_mount proper path
Bugzilla: 1709242
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1709242
https://bugzilla.redhat.com/show_bug.cgi?id=1709242

upstream
========
commit c458a6206d2a8600934617ccf88ba7d3a030faba
Author: Jiri Olsa <jolsa@kernel.org>
Date: Tue Oct 16 13:48:18 2018 +0200

description
===========
If there's no tracefs (RHEL7) support the tracing_path_mount
returns debugfs path which results in following fail:

  # perf probe sys_write
  kprobe_events file does not exist - please rebuild kernel with CONFIG_KPROBE_EVENTS.
  Error: Failed to add events.

In tracing_path_debugfs_mount function we need to return the
'tracing' path instead of just the mount to make it work:

  # perf probe sys_write
  Added new event:
    probe:sys_write      (on sys_write)

  You can now use it in all perf tools, such as:

          perf record -e probe:sys_write -aR sleep 1

Adding the 'return tracing_path;' also to tracing_path_tracefs_mount
function just for consistency with tracing_path_debugfs_mount.

Upstream keeps working, because it has the tracefs support.

Fixes: 23773ca18b39 ("perf tools: Make perf aware of tracefs")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>