bnxt_en: take coredump_record structure off stack
Message-id: <20190508140250.9014-20-sxavier@redhat.com>
Patchwork-id: 254006
O-Subject: [RHEL8.1 PATCH BZ 1664477 019/107] bnxt_en: take coredump_record structure off stack
Bugzilla: 1664477
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664477
Upstream: 1bbf3aed25e0fc256e825da1f5c45d7b4daa828e
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21351388
Test: Smoke testing with traffic passed.

commit 1bbf3aed25e0fc256e825da1f5c45d7b4daa828e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Aug 14 00:12:45 2018 +0200

    bnxt_en: take coredump_record structure off stack

    The bnxt_coredump_record structure is very long, causing a warning
    about possible stack overflow on 32-bit architectures:

    drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c: In function 'bnxt_get_coredump':
    drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:2989:1: error: the frame size of 1188 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    I could not see any reason to operate on an on-stack copy of the
    structure before copying it back into the caller-provided buffer, which
    also simplifies the code here.

    Fixes: 6c5657d085ae ("bnxt_en: Add support for ethtool get dump.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Selvin Xavier <sxavier@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>