perf probe: Clean up probe_point_lazy_walker() return value
Patchwork-id: 36546
O-Subject: [PATCH RHEL6.2 BZ691343 109/142] perf probe: Clean up probe_point_lazy_walker() return value
Bugzilla: 691343
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 691343
https://bugzilla.redhat.com/show_bug.cgi?id=691343

upstream status
---------------
commit 5e814dd597c42daeb8d2a276e64a6ec986ad0e2a
Author: Ingo Molnar <mingo@elte.hu>
Date:   Tue Mar 15 20:51:09 2011 +0100

description
-----------
Newer compilers (gcc 4.6) complains about:

        return ret < 0 ?: 0;

For the following reason:

  util/probe-finder.c: In function ‘probe_point_lazy_walker’:
  util/probe-finder.c:1331:18: error: the omitted middle operand in ?: will always be ‘true’, suggest explicit middle operand [-Werror=parentheses]

And indeed the return value is a somewhat obscure (but correct) value
of 'true', so return 'ret' instead - this is cleaner and unconfuses
GCC as well.

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>