sctp: Validate parameter size for SCTP_GET_ASSOC_STATS
Patchwork-id: 57276
O-Subject: [RHEL6.5 PATCH] net/sctp: Validate parameter size for SCTP_GET_ASSOC_STATS
Bugzilla: 755486
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Flavio Leitner <fbl@redhat.com>
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>
RH-Acked-by: Petr Matousek <pmatouse@redhat.com>
RH-Acked-by: Daniel Borkmann <dborkman@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Vlad Yasevich <vyasevic@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=755486
Upstream Status: 726bc6b092da4c093eb74d13c07184b18c1af0f1
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=5485625
Tested: Verified locally

The following follow-up fix is required to avoid becoming vulnerable
to CVE-2013-1828.

Upstream commit:
commit 726bc6b092da4c093eb74d13c07184b18c1af0f1
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Wed Feb 27 10:57:31 2013 +0000

    net/sctp: Validate parameter size for SCTP_GET_ASSOC_STATS

    Building sctp may fail with:

    In function ‘copy_from_user’,
        inlined from ‘sctp_getsockopt_assoc_stats’ at
        net/sctp/socket.c:5656:20:
    arch/x86/include/asm/uaccess_32.h:211:26: error: call to
        ‘copy_from_user_overflow’ declared with attribute error: copy_from_user()
        buffer size is not provably correct

    if built with W=1 due to a missing parameter size validation
    before the call to copy_from_user.

    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Vlad Yasevich <vyasevich@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Thomas Graf <tgraf@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>