time: Workaround gcc loop optimization that causes 64bit div errors
Patchwork-id: 48644
O-Subject: [RHEL6.4 PATCH BZ 836748 29/67] time: Workaround gcc loop optimization that causes 64bit div errors
Bugzilla: 836748
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

commit c7dcf87a6881bf796faee83003163eb3de41a309
Author: John Stultz <johnstul@us.ibm.com>
Date:   Fri Aug 13 11:30:58 2010 -0700

    time: Workaround gcc loop optimization that causes 64bit div errors

    Early 4.3 versions of gcc apparently aggressively optimize the raw
    time accumulation loop, replacing it with a divide.

    On 32bit systems, this causes the following link errors:
    	undefined reference to `__umoddi3'
    	undefined reference to `__udivdi3'

    The gcc issue has been fixed in 4.4 and greater.

    This patch replaces the accumulation loop with a do_div, as suggested
    by Linus.

    Signed-off-by: John Stultz <johnstul@us.ibm.com>
    CC: Jason Wessel <jason.wessel@windriver.com>
    CC: Larry Finger <Larry.Finger@lwfinger.net>
    CC: Ingo Molnar <mingo@elte.hu>
    CC: Linus Torvalds <torvalds@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>