kaslr: Use the right memcpy() implementation
Message-id: <1496236477-18954-7-git-send-email-bhe@redhat.com>
Patchwork-id: 179210
O-Subject: [RHEL7.4 PATCH 6/6] x86/KASLR: Use the right memcpy() implementation
Bugzilla: 1440928
RH-Acked-by: Pratyush Anand <panand@redhat.com>
RH-Acked-by: Dave Young <dyoung@redhat.com>

This is back ported from tip/x86/boot directly.

commit 5b8b9cf76add98e19ff8ceb4247c2920687591a0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 30 11:14:17 2017 +0200

    x86/KASLR: Use the right memcpy() implementation

    The decompressor has its own implementation of the string functions,
    but has to include the right header to get those, while implicitly
    including linux/string.h may result in a link error:

      arch/x86/boot/compressed/kaslr.o: In function `choose_random_location':
      kaslr.c:(.text+0xf51): undefined reference to `_mmx_memcpy'

    This has appeared now as KASLR started using memcpy(), via:

        d52e7d5a952c ("x86/KASLR: Parse all 'memmap=' boot option entries")

    Other files in the decompressor already do the same thing.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Baoquan He <bhe@redhat.com>
    Cc: Dave Jiang <dave.jiang@intel.com>
    Cc: Kees Cook <keescook@chromium.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Garnier <thgarnie@google.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Link: http://lkml.kernel.org/r/20170530091446.1000183-1-arnd@arndb.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>