Fix linker errors with CONFIG_PM=n
Patchwork-id: 30309
O-Subject: [RHEL6 PATCH 099/107] usb: Fix linker errors with CONFIG_PM=n
Bugzilla: 591794 591796 591797 624615 637237
RH-Acked-by: Bob Picco <bpicco@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=591794
https://bugzilla.redhat.com/show_bug.cgi?id=591796
https://bugzilla.redhat.com/show_bug.cgi?id=591797
https://bugzilla.redhat.com/show_bug.cgi?id=637237
https://bugzilla.redhat.com/show_bug.cgi?id=624615

commit 436a389096e1feda2c382cad83b6a8d6de8615a0
Author: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Date:   Fri Oct 15 14:59:15 2010 -0700

    usb: Fix linker errors with CONFIG_PM=n

    Fix these linker errors when CONFIG_PM=n:

    ERROR: "xhci_bus_resume" [drivers/usb/host/xhci-hcd.ko] undefined!
    ERROR: "xhci_bus_suspend" [drivers/usb/host/xhci-hcd.ko] undefined!

    Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
    Acked-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>