perf header: Fix unchecked usage of strncpy()
Message-id: <aef397d06b7bb53d1139a4c63e09b4dcad4cce86.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265121
O-Subject: [RHEL8.1 BZ1715507 099/234] perf header: Fix unchecked usage of strncpy()
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 5192bde7d98c99f2cd80225649e3c2e7493722f7
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Dec 6 11:09:46 2018 -0300

description
===========
The strncpy() function may leave the destination string buffer
unterminated, better use strlcpy() that we have a __weak fallback
implementation for systems without it.

This fixes this warning on an Alpine Linux Edge system with gcc 8.2:

  util/header.c: In function 'perf_event__synthesize_event_update_name':
  util/header.c:3625:2: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
    strncpy(ev->data, evsel->name, len);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  util/header.c:3618:15: note: length computed here
    size_t len = strlen(evsel->name);
                 ^~~~~~~~~~~~~~~~~~~

Fixes: a6e5281780d1 ("perf tools: Add event_update event unit type")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>