perf tools: Fix statfs.f_type data type mismatch build error with uclibc
Patchwork-id: 127462
O-Subject: [PATCH RHEL6 BZ1265262 154/210] perf tools: Fix statfs.f_type data type mismatch build error with uclibc
Bugzilla: 1265262
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1265262
https://bugzilla.redhat.com/show_bug.cgi?id=1265262

upstream
========
commit db1806edcfef007d9594435a331dcf7e7f1b8fac
Author: Alexey Brodkin <abrodkin@synopsys.com>
Date: Sat Jan 10 16:40:50 2015 +0530

description
===========
ARC Linux uses the no legacy syscalls abi and corresponding uClibc headers
statfs defines f_type to be U32 which causes perf build breakage

http://git.uclibc.org/uClibc/tree/libc/sysdeps/linux/common-generic/bits/statfs.h

  ----------->8---------------
    CC       fs/fs.o
  fs/fs.c: In function 'fs__valid_mount':
  fs/fs.c:82:24: error: comparison between signed and unsigned integer
  expressions [-Werror=sign-compare]
    else if (st_fs.f_type != magic)
                          ^
  cc1: all warnings being treated as errors
  ----------->8

Signed-off-by: Aristeu Rozanski <aris@redhat.com>