tg3: Fix VLAN creation problem
Patchwork-id: 40712
O-Subject: [RHEL6.2 PATCH] tg3: Fix VLAN creation problem
Bugzilla: 731268 732769
RH-Acked-by: Doug Ledford <dledford@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

bz732769
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=732769
VLANs do not work

bz731268
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=731268
Can't add vlan to a tg3 device

Description of problem:
The following command line does not work now.
$vconfig add eth1 10
 error: Operation not supported

Solution:
As part of the patch set for bz716693 "Update tg3 to 3.119+", the
upstream patch entitled "tg3: Use new VLAN code" (commit:
bf933c802763b2beb1a1d4977f00af1a78c4fb70) was included.
Unfortunately, the new code does not work with the tg3 driver in
RHEL6.2. Thus, you can't remove the call to tg3_vlan_rx_register()
as the value assigned to .ndo_vlan_rx_register and instead use
vlan_tx_tag_present(). If you back out this patch, VLANs can be
made successfully, which is what the patch below does.

Given the criticality of this regression, I am simply going to
back out the patch for now.

Brew: Successfully built in Brew for all architectures (task_3618493).

Testing:
I was able to successfully create a vlan on a system with a 5755 and
ran Connectathon successfully on that same system just for sanity's
sake.

Acks would be appreciated. Thanks.

Signed-off-by: Kyle McMartin <kmcmarti@redhat.com>