autofs4: fix false positive compile error
Message-id: <148877460271.7079.6390885940928894875.stgit@pluto.themaw.net>
Patchwork-id: 170720
O-Subject: [RHEL 7.4 BZ1413523 PATCH 05/66] autofs4: fix false positive compile error
Bugzilla: 1413523
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>

From: Ian Kent <raven@themaw.net>

Buzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1413523
Upstream commit: linux.git 571ff4731b
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=1247935

On strict build environments we can see:

  fs/autofs4/inode.c: In function 'autofs4_fill_super':
  fs/autofs4/inode.c:312: error: 'pgrp' may be used uninitialized in this function
  make[2]: *** [fs/autofs4/inode.o] Error 1
  make[1]: *** [fs/autofs4] Error 2
  make: *** [fs] Error 2
  make: *** Waiting for unfinished jobs....

This is due to the use of pgrp_set being used to indicate pgrp has has
been set rather than initializing pgrp itself.

Signed-off-by: Ian Kent <raven@themaw.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Rafael Aquini <aquini@redhat.com>