ALSA: usb-audio: Fix multiple definitions in AU0828_DEVICE() macro
Message-id: <15580872947136052-307-patchset-jkysela@redhat.com>
Patchwork-id: 256967
O-Subject: [RHEL 8.1 PATCH 0306/2119] ALSA: usb-audio: Fix multiple definitions in AU0828_DEVICE() macro
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

AU0828_DEVICE() macro in quirks-table.h uses USB_DEVICE_VENDOR_SPEC()
for expanding idVendor and idProduct fields.  However, the latter
macro adds also match_flags and bInterfaceClass, which are different
from the values AU0828_DEVICE() macro sets after that.

For fixing them, just expand idVendor and idProduct fields manually in
AU0828_DEVICE().

This fixes sparse warnings like:
  sound/usb/quirks-table.h:2892:1: warning: Initializer entry defined twice

Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit bd1cd0eb2ce9141100628d476ead4de485501b29)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>