vhost: silence an unused-variable warning
Message-id: <20190813075105.40324-59-jasowang@redhat.com>
Patchwork-id: 268998
O-Subject: [RHEL8.1 PATCH 58/62] vhost: silence an unused-variable warning
Bugzilla: 1738494
RH-Acked-by: Maxime Coquelin <maxime.coquelin@redhat.com>
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

On some architectures, the MMU can be disabled, leading to access_ok()
becoming an empty macro that does not evaluate its size argument,
which in turn produces an unused-variable warning:

drivers/vhost/vhost.c:1191:9: error: unused variable 's' [-Werror,-Wunused-variable]
        size_t s = vhost_has_feature(vq, VIRTIO_RING_F_EVENT_IDX) ? 2 : 0;

Mark the variable as __maybe_unused to shut up that warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit cfdbb4ed31aa777d59b288810f66eb06249ee5b7)
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>