tools: Work around lack of sched_getcpu in glibc < 2.6
Patchwork-id: 129281
O-Subject: [PATCH RHEL6 BZ1291071 232/315] perf tools: Work around lack of sched_getcpu in glibc < 2.6.
Bugzilla: 1291071
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1291071
https://bugzilla.redhat.com/show_bug.cgi?id=1291071

upstream
========
commit e1e455f4f4d35850c30235747620d0d078fe9f64
Author: Vinson Lee <vlee@twitter.com>
Date: Mon Mar 23 12:09:16 2015 -0700

description
===========
This patch fixes this build error with glibc < 2.6.

  CC       util/cloexec.o
cc1: warnings being treated as errors
util/cloexec.c: In function 'perf_flag_probe':
util/cloexec.c:24: error: implicit declaration of function
'sched_getcpu'
util/cloexec.c:24: error: nested extern declaration of 'sched_getcpu'
make: *** [util/cloexec.o] Error 1

Signed-off-by: Aristeu Rozanski <aris@redhat.com>