pseries: Fix build break when MEMORY_HOTREMOVE=n
Message-id: <1488806430-19116-35-git-send-email-thuth@redhat.com>
Patchwork-id: 170829
O-Subject: [RHEL7.4 kvm PATCH 34/41] powerpc/pseries: Fix build break when MEMORY_HOTREMOVE=n
Bugzilla: 1323417
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

From: Michael Ellerman <mpe@ellerman.id.au>

We broke the build when CONFIG_MEMORY_HOTREMOVE=n:

  arch/powerpc/platforms/pseries/hotplug-memory.c:821:8: error: implicit
  declaration of function 'dlpar_memory_readd_by_index'

Add a dummy to fix it.

Fixes: e70d59700fc3 ("powerpc/pseries: Introduce memory hotplug READD operation")
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit f84775c2d5d92581f2df60d53b574b0405c85be3)
Signed-off-by: Rafael Aquini <aquini@redhat.com>