scsi_error: Escalate to LUN reset if abort fails
Patchwork-id: 78997
O-Subject: [RHEL6.6 PATCH e-stor 2/4] [SCSI] scsi_error: Escalate to LUN reset if abort fails
Bugzilla: 987789
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Bryn M. Reeves <bmr@redhat.com>

If a command abort fails there is a fair chance that all other
aborts will be failing, too.
So we should be calling LUN reset directly after the first failed
abort and skip aborting the remaining commands.

Signed-off-by: Hannes Reinecke <hare@suse.de>
Signed-off-by: James Bottomley <JBottomley@Parallels.com>
(cherry picked from commit 6fd046f960354250de3fed411eecdb784601bbad)
Signed-off-by: Ewan D. Milne <emilne@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>