perf tools: Provide stub for missing pthread_attr_setaffinity_np
Patchwork-id: 127499
O-Subject: [PATCH RHEL6 BZ1265262 194/210] perf tools: Provide stub for missing pthread_attr_setaffinity_np
Bugzilla: 1265262
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1265262
https://bugzilla.redhat.com/show_bug.cgi?id=1265262

upstream
========
commit 459a3df76c99124fd222586be7f10f862547e7a9
Author: Vineet Gupta <Vineet.Gupta1@synopsys.com>
Date: Tue Jan 13 19:13:24 2015 +0530

description
===========
uClibc Linuxthreads.old doesn't support the pthread_attr_setaffinity_np()
functioo:

   ----------------->8-----------------------
  CC       bench/futex-hash.o
  CC       bench/futex-wake.o
bench/futex-hash.c: In function 'bench_futex_hash':
bench/futex-hash.c:161:3: error: implicit declaration of function
'pthread_attr_setaffinity_np' [-Werror=implicit-function-declaration]
   ret = pthread_attr_setaffinity_np(&thread_attr, sizeof(cpu_set_t),
&cpu);
   ^
bench/futex-hash.c:161:3: error: nested extern declaration of
'pthread_attr_setaffinity_np' [-Werror=nested-externs]
   ----------------->8-----------------------

So introduce a test to check that and if not available provide a stub.

Signed-off-by: Aristeu Rozanski <aris@redhat.com>