selftests: mqueue mq_perf_tests checkpatch fixes
Patchwork-id: 46759
O-Subject: [Patch RHEL6 8/8] tools-selftests-add-mq_perf_tests-checkpatch-fixes.patch added to -mm tree
Bugzilla: 750260
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Jay Fenlason <fenlason@redhat.com>

From: "akpm@linux-foundation.org" <akpm@linux-foundation.org>

The patch titled
     Subject: tools-selftests-add-mq_perf_tests-checkpatch-fixes
has been added to the -mm tree.  Its filename is
     tools-selftests-add-mq_perf_tests-checkpatch-fixes.patch

Before you just go and hit "reply", please:
   a) Consider who else should be cc'ed
   b) Prefer to cc a suitable mailing list as well
   c) Ideally: find the original patch on the mailing list and do a
      reply-to-all to that, adding suitable additional cc's

*** Remember to use Documentation/SubmitChecklist when testing your code ***

The -mm tree is included into linux-next and is updated
there every 3-4 working days

------------------------------------------------------
From: Andrew Morton <akpm@linux-foundation.org>
Subject: tools-selftests-add-mq_perf_tests-checkpatch-fixes

Cc: Doug Ledford <dledford@redhat.com>

ERROR: space required after that ',' (ctx:VxV)
+#define min(a,b) ((a) < (b) ? (a) : (b))
              ^

ERROR: that open brace { should be on the previous line
+const struct poptOption options[] =
+{

WARNING: externs should be avoided in .c files
+void shutdown(int exit_val, char *err_cause, int line_no);

WARNING: externs should be avoided in .c files
+void sig_action_SIGUSR1(int signum, siginfo_t *info, void *context);

WARNING: externs should be avoided in .c files
+void sig_action(int signum, siginfo_t *info, void *context);

WARNING: externs should be avoided in .c files
+void increase_limits(void);

ERROR: do not initialise statics to 0 or NULL
+	static int in_shutdown = 0;

ERROR: spaces required around that '=' (ctx:VxV)
+	for (i=0; i < num_cpus_to_pin; i++)
 	      ^

WARNING: quoted string split across lines
+		fprintf(stderr, "Caught signal %d in SIGUSR1 handler, "
+			"exiting\n", signum);

ERROR: do not use assignment in if condition
+	if ((queue = mq_open(queue_path, flags, perms, attr)) == -1)

ERROR: spaces required around that '=' (ctx:VxV)
+	for (i=0; i < num_cpus_to_pin; i++)
 	      ^

ERROR: space required before the open parenthesis '('
+	while(1) ;

ERROR: trailing statements should be on next line
+	while(1) ;

ERROR: spaces required around that '=' (ctx:VxV)
+	for (i=0; i < num_cpus_to_pin; i++)
 	      ^

ERROR: space required before the open parenthesis '('
+	while(1) {

ERROR: space required before the open parenthesis '('
+		while(mq_send(queue, buff, sizeof(buff), 0) == 0);

ERROR: trailing statements should be on next line
+		while(mq_send(queue, buff, sizeof(buff), 0) == 0);

ERROR: Macros with complex values should be enclosed in parenthesis
+#define drain_queue() \
+	while (mq_receive(queue, buff, MSG_SIZE, &prio_in) == MSG_SIZE)

ERROR: space required before the open parenthesis '('
+	} while(0)

WARNING: Statements terminations use 1 semicolon
+		*prio = 0;;

ERROR: do not use assignment in if condition
+	if ((mq_prio_max = sysconf(_SC_MQ_PRIO_MAX)) == -1)

WARNING: quoted string split across lines
+	printf("\n\tTest #1: Time send/recv message, queue "
+	       "empty\n");

ERROR: trailing statements should be on next line
+	while (try_set(max_msgs, cur_max_msgs += 10));

ERROR: trailing statements should be on next line
+	while (try_set(max_msgsize, cur_max_msgsize += 1024));

ERROR: do not use assignment in if condition
+	if ((cpu_set = CPU_ALLOC(cpus_online)) == NULL) {

WARNING: quoted string split across lines
+					fprintf(stderr, "CPU %d exceeds "
+						"cpus online, ignoring.\n",

WARNING: quoted string split across lines
+					fprintf(stderr, "Any given CPU may "
+						"only be given once.\n");

WARNING: quoted string split across lines
+		fprintf(stderr, "Must pass at least one CPU to continuous "
+			"mode.\n");

WARNING: quoted string split across lines
+		fprintf(stderr, "Not running as root, but almost all tests "
+			"require root in order to modify\nsystem settings.  "

ERROR: spaces required around that '=' (ctx:VxV)
+	for(cpu=1; cpu < num_cpus_to_pin; cpu++)
 	       ^

ERROR: space required before the open parenthesis '('
+	for(cpu=1; cpu < num_cpus_to_pin; cpu++)

ERROR: spaces required around that '=' (ctx:VxV)
+	for (i=0; i < num_cpus_to_pin; i++) {
 	      ^

ERROR: space required before the open parenthesis '('
+		while(1) sleep(1);

ERROR: trailing statements should be on next line
+		while(1) sleep(1);

ERROR: space required after that ',' (ctx:VxV)
+	shutdown(0,"",0);
 	          ^

ERROR: space required after that ',' (ctx:VxV)
+	shutdown(0,"",0);
 	             ^

total: 25 errors, 11 warnings, 747 lines checked

./patches/tools-selftests-add-mq_perf_tests.patch has style problems, please review.

If any of these errors are false positives, please report
them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Doug Ledford <dledford@redhat.com>
Cc: Frederic Weisbecker <fweisbec@gmail.com>
Cc: Manfred Spraul <manfred@colorfullife.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Jarod Wilson <jarod@redhat.com>