shmem: fix up rhel-6.4 kABI issues
Patchwork-id: 53952
O-Subject: [RHEL6 PATCH 4/4] tmpfs: fix kABI issues (RHEL only)
Bugzilla: 857000
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>

Bugzilla: 857000
https://bugzilla.redhat.com/show_bug.cgi?id=857000

The patch "tmpfs: clone shmem_file_splice_read()" introduces the following
kABI issue for RHEL6:

--8<--
*** ERROR - ABI BREAKAGE WAS DETECTED ***
The following symbols have been changed (this will cause an ABI breakage):
shmem_file_setup
-->8--

Such issue occurs due to struct pipe_inode_info being declared opaque (at fs.h)
and then changing (became defined) when 'splice.h' is included at mm/shmem.c

Here's the output from kabi checking (KBUILD_SYMTYPES make):
mm/shmem.c:2308: error: shmem_file_setup: modversion changed because of changes in struct pipe_inode_info (became defined)

This patch fixes such breakage by wrapping '#include <linux/splice.h>' with
'#ifndef __GENKSYMS__', thus avoiding such intended struct definition causing
the observed breakage.

(Special thanks to Don Zickus for guidance and RHEL6 commit 409236c741)

Signed-off-by: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>