tools, x86: Build perf on older user-space as well
Patchwork-id: 104058
O-Subject: [PATCH RHEL6.7 BZ1188336 056/280] perf tools, x86: Build perf on older user-space as well
Bugzilla: 1188336
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1188336
https://bugzilla.redhat.com/show_bug.cgi?id=1188336

upstream
========
commit eae7a755ee81129370c8f555b0d5672e6673735d
Author: Ingo Molnar <mingo@elte.hu>
Date: Wed Mar 14 12:42:34 2012 -0300

description
===========
On ancient systems I get this build failure:

  util/../../../arch/x86/include/asm/unistd.h:67:29: error: asm/unistd_64.h: No such file or directory
  In file included from util/cache.h:7,
                   from builtin-test.c:8:
  util/../perf.h: In function sys_perf_event_open:In file included from util/../perf.h:16
  perf.h:170: error: __NR_perf_event_open undeclared (first use in this function)

The reason is that this old system does not have the split
unistd.h headers yet, from which to pick up the syscall
definitions.

Add the syscall numbers to the already existing i386 and x86_64
blocks in perf.h, and also provide empty include file stubs.

With this patch perf builds and works fine on 5 years old
user-space as well.

Signed-off-by: Rafael Aquini <aquini@redhat.com>