intel_pstate: Fix 32 bit build
Patchwork-id: 59110
O-Subject: [RHEL 6.5 PATCH 06/14] cpufreq / intel_pstate: Fix 32 bit build
Bugzilla: 956824
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

From: Prarit Bhargava <prarit@redhat.com>

commit 191e5edf96dc4939f5db0605cc65de9f4d88d155
Author: Dirk Brandewie <dirk.brandewie@gmail.com>
Date:   Mon Feb 11 20:33:34 2013 +0100

    cpufreq / intel_pstate: Fix 32 bit build

    Fixes 32 bit build.

    on i386:
    drivers/built-in.o: In function `intel_pstate_timer_func':
    intel_pstate.c:(.text+0x4ce97e): undefined reference to `__udivdi3'
    drivers/built-in.o: In function `intel_pstate_cpu_init':
    intel_pstate.c:(.cpuinit.text+0x974): undefined reference to `__udivdi3'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Dirk Brandewie <dirk.j.brandewie@intel.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>