swiotlb: Remove the swiotlb variable usage
Patchwork-id: 107562
O-Subject: [PATCH RHEL6 13/27] swiotlb: Remove the swiotlb variable usage
Bugzilla: 1198380
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

From: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>

POWERPC doesn't expect it to be used.

This fixes the linux-next build failure reported by
Stephen Rothwell:

  lib/swiotlb.c: In function 'setup_io_tlb_npages':
  lib/swiotlb.c:114: error: 'swiotlb' undeclared (first use in this function)

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>
Cc: peterz@infradead.org
LKML-Reference: <20091112000258F.fujita.tomonori@lab.ntt.co.jp>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
(cherry picked from commit b18485e7acfe1a634615d1c628ef644c0d58d472)
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>