sched: act_nat: validate the control action inside init()
Message-id: <20190610212005.12299-140-ivecera@redhat.com>
Patchwork-id: 264127
O-Subject: [RHEL-8.1 net PATCH 139/194] net/sched: act_nat: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 1e45d043a8bb2ed8a541384db3cc133e92001f0c
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:06 2019 +0100

    net/sched: act_nat: validate the control action inside init()

    the following script:

     # tc qdisc add dev crash0 clsact
     # tc filter add dev crash0 egress matchall \
     > action nat ingress 1.18.1.1 1.18.2.2 pass index 90
     # tc actions replace action nat \
     > ingress 1.18.1.1 1.18.2.2 goto chain 42 index 90 cookie c1a0c1a0
     # tc actions show action nat

    had the following output:

     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0:  nat ingress 1.18.1.1/32 1.18.2.2 goto chain 42
              index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
     #PF error: [normal kernel read fault]
     PGD 800000002d180067 P4D 800000002d180067 PUD 7cb8b067 PMD 0
     Oops: 0000 [#1] SMP PTI
     CPU: 3 PID: 164 Comm: kworker/3:1 Not tainted 5.0.0-rc4.gotochain_crash+ #533
     Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
     Workqueue: ipv6_addrconf addrconf_dad_work
     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffffae4500e2fad0 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff9fa52e28c800 RCX: 0000000001011201
     RDX: 0000000000000000 RSI: 0000000000000056 RDI: ffff9fa52ca12800
     RBP: ffffae4500e2fb70 R08: 0000000000000022 R09: 000000000000000e
     R10: 00000000ffffffff R11: 0000000001011201 R12: ffff9fa52cbc9c00
     R13: ffff9fa52cbc9c08 R14: 0000000000000001 R15: ffff9fa52ca12780
     FS:  0000000000000000(0000) GS:ffff9fa57db80000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 0000000073f8c004 CR4: 00000000001606e0
     Call Trace:
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ndisc_next_option+0x50/0x50
      ? ___neigh_create+0x4d5/0x680
      ? ip6_finish_output2+0x1b5/0x590
      ip6_finish_output2+0x1b5/0x590
      ? ip6_output+0x68/0x110
      ip6_output+0x68/0x110
      ? nf_hook.constprop.28+0x79/0xc0
      ndisc_send_skb+0x248/0x2e0
      ndisc_send_ns+0xf8/0x200
      ? addrconf_dad_work+0x389/0x4b0
      addrconf_dad_work+0x389/0x4b0
      ? __switch_to_asm+0x34/0x70
      ? process_one_work+0x195/0x380
      ? addrconf_dad_completed+0x370/0x370
      process_one_work+0x195/0x380
      worker_thread+0x30/0x390
      ? process_one_work+0x380/0x380
      kthread+0x113/0x130
      ? kthread_park+0x90/0x90
      ret_from_fork+0x35/0x40
     Modules linked in: act_nat veth ip6table_filter ip6_tables iptable_filter binfmt_misc ext4 crct10dif_pclmul crc32_pclmul ghash_clmulni_intel mbcache jbd2 snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hwdep snd_hda_core snd_seq snd_seq_device snd_pcm aesni_intel crypto_simd cryptd glue_helper snd_timer snd joydev virtio_balloon pcspkr soundcore i2c_piix4 nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs qxl ata_generic pata_acpi drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm virtio_net virtio_blk net_failover failover virtio_console drm crc32c_intel floppy ata_piix libata virtio_pci virtio_ring virtio serio_raw dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_nat_init() proved to fix the
    above issue. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>