annotate: Fix 32-bit compilation error in util/annotate.c
Patchwork-id: 130408
O-Subject: [PATCH RHEL6.8 BZ1189317 32/32] perf annotate: Fix 32-bit compilation error in util/annotate.c
Bugzilla: 1189317
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1189317
https://bugzilla.redhat.com/show_bug.cgi?id=1189317

upstream
========
commit 3d7245b0946c13a97e3a10213b8fd0152972a0d5
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Aug 14 10:11:34 2015 +0300

description
===========
Fix the following 32-bit compilation errors:

  util/annotate.c: In function 'addr_map_symbol__account_cycles':
  util/annotate.c:643:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'u64' [-Werror=format=]
    pr_debug2("BB with bad start: addr %lx start %lx sym %lx saddr %lx\n",
      ^
  util/annotate.c:643:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'u64' [-Werror=format=]
  util/annotate.c:643:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 6 has type 'u64' [-Werror=format=]

These were introduced by the patch:

"perf report: Add infrastructure for a cycles histogram"

Also change the 'saddr' variable from 'unsigned long' to 'u64'
noting that theoretically we could be processing data captured
on a 64-bit machine but processing it on a 32-bit machine.

Fixes: d4957633bf9d ("perf report: Add infrastructure for a cycles histogram")
Signed-off-by: Aristeu Rozanski <aris@redhat.com>