Fix a build error with some GCC versions
Patchwork-id: 38914
O-Subject: =?UTF-8?q?=5BPATCH=20RHEL6=2E2=20BZ725522=2003/67=5D=20perf=3A=20Fix=20a=20build=20error=20with=20some=20GCC=20versions?=
Bugzilla: 725522
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 725522
https://bugzilla.redhat.com/show_bug.cgi?id=725522

upstream status
---------------
commit 621d26567fd0c222f419e3b5ddf39e529e0fdcb3
Author: Eric Dumazet <eric.dumazet@gmail.com>
Date:   Fri Apr 8 12:11:06 2011 +0200

description
-----------
Fix this:

 util/cgroup.c: In function ‘open_cgroup’:
 util/cgroup.c:16:16: error: ‘saved_ptr’ may be used uninitialized in this function
 util/cgroup.c:16:16: note: ‘saved_ptr’ was declared here

Apparently newer GCC (4.6) can figure out that this variable is properly
initialized - but some versions of GCC (such as 4.5.2) need help.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>