tools build: Fix objtool build with ARCH=x86_64
Message-id: <1477399629-8377-285-git-send-email-jolsa@redhat.com>
Patchwork-id: 159715
O-Subject: [PATCH RHEL7.4 BZ1387909 284/322] tools build: Fix objtool build with ARCH=x86_64
Bugzilla: 1387909
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1387909
https://bugzilla.redhat.com/show_bug.cgi?id=1387909

upstream
========
commit 60cbdf5d051d4f4db23d267d511ca241d4be7c0d
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date: Fri Jul 22 14:19:20 2016 -0500

description
===========
The objtool build fails in a cross-compiled environment on a non-x86
host with "ARCH=x86_64":

  tools/objtool/objtool-in.o: In function `decode_instructions':
  tools/objtool/builtin-check.c:276: undefined reference to `arch_decode_instruction'

We could override the ARCH environment variable and change it back to
x86, similar to what the objtool Makefile was doing before; but it's
tricky to override environment variables consistently.

Instead, take a similar approach used by the Linux top-level Makefile
and introduce a SRCARCH Makefile variable which evaluates to "x86" when
ARCH is either "x86_64" or "x86".

Signed-off-by: Rafael Aquini <aquini@redhat.com>