net/mlx5: fix an unused-function warning
Message-id: <20190611113043.27212-30-ahleihel@redhat.com>
Patchwork-id: 264480
O-Subject: [RHEL8.1 BZ 1691231 v2 29/76] net/mlx5: fix an unused-function warning
Bugzilla: 1691231
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691231
Upstream: v4.19-rc1

commit 6060d9d24e6d7c7959d0db8cd9f511cf43c409d9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jul 17 15:49:48 2018 +0200

    net/mlx5: fix an unused-function warning

    These dummy helpers are all intended to be inline functions,
    but one of them by accident came without the 'inline' keyword,
    causing a harmless warning:

    In file included from drivers/net/ethernet/mellanox/mlx5/core/main.c:63:
    drivers/net/ethernet/mellanox/mlx5/core/accel/tls.h:79:1: error: 'mlx5_accel_tls_add_flow' defined but not used [-Werror=unused-function]
     mlx5_accel_tls_add_flow(struct mlx5_core_dev *mdev, void *flow,

    Fixes: ab412e1dd7db ("net/mlx5: Accel, add TLS rx offload routines")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>