chelsio: use BUG() instead of BUG_ON(1)
Message-id: <20190424050627.23125-65-avynipad@redhat.com>
Patchwork-id: 250761
O-Subject: [RHEL8.1 PATCH 64/65] chelsio: use BUG() instead of BUG_ON(1)
Bugzilla: 1664670
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1664670

commit 047a013f8d0af8299ce2d02af152de6a30165ccc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 25 13:49:16 2019 +0100

    chelsio: use BUG() instead of BUG_ON(1)

    clang warns about possible bugs in a dead code branch after
    BUG_ON(1) when CONFIG_PROFILE_ALL_BRANCHES is enabled:

     drivers/net/ethernet/chelsio/cxgb4/sge.c:479:3: error: variable 'buf_size' is used uninitialized whenever 'if'
          condition is false [-Werror,-Wsometimes-uninitialized]
                    BUG_ON(1);
                    ^~~~~~~~~
     include/asm-generic/bug.h:61:36: note: expanded from macro 'BUG_ON'
     #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
                                       ^~~~~~~~~~~~~~~~~~~
     include/linux/compiler.h:48:23: note: expanded from macro 'unlikely'
     #  define unlikely(x)   (__branch_check__(x, 0, __builtin_constant_p(x)))
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     drivers/net/ethernet/chelsio/cxgb4/sge.c:482:9: note: uninitialized use occurs here
            return buf_size;
                   ^~~~~~~~
     drivers/net/ethernet/chelsio/cxgb4/sge.c:479:3: note: remove the 'if' if its condition is always true
                    BUG_ON(1);
                    ^
     include/asm-generic/bug.h:61:32: note: expanded from macro 'BUG_ON'
     #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
                                   ^
     drivers/net/ethernet/chelsio/cxgb4/sge.c:459:14: note: initialize the variable 'buf_size' to silence this warning
            int buf_size;
                        ^
                         = 0

    Use BUG() here to create simpler code that clang understands
    correctly.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: Kamal Heib <kheib@redhat.com>
Cc: Tony Camuso <tcamuso@redhat.com>
Cc: Venkatesh Pottem <vpottem@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>