mlx5e: use %pad format string for dma_addr_t
Message-id: <1488853076-16738-152-git-send-email-ddutile@redhat.com>
Patchwork-id: 171802
O-Subject: [PATCH RHEL-7.4 151/340] net/mlx5e: use %pad format string for dma_addr_t
Bugzilla: 1385330 1417286
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1417286
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1385330

commit 9afd895271d91cd6ed743d22fce043f8c28b30ce
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 8 22:57:03 2016 +0100

    net/mlx5e: use %pad format string for dma_addr_t

    On 32-bit ARM with 64-bit dma_addr_t I get this warning about an
    incorrect format string:

    In file included from /git/arm-soc/drivers/net/ethernet/mellanox/mlx5/core/alloc.c:42:0:
    drivers/net/ethernet/mellanox/mlx5/core/alloc.c: In function mlx5_frag_buf_alloc_node:
    drivers/net/ethernet/mellanox/mlx5/core/alloc.c:134:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]

    We have the special %pad format for printing dma_addr_t, so use that
    to print the correct address and avoid the warning.

    Fixes: 1c1b522808a1 ("net/mlx5e: Implement Fragmented Work Queue (WQ)")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>