build: Pass through all targets to Makefile.perf
Patchwork-id: 99521
O-Subject: [PATCH RHEL6.7 BZ1159929 076/320] tools/perf/build: Pass through all targets to Makefile.perf
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit b016a0dd08999218a05a4b176bc08a9ff68ccc5e
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Oct 3 14:32:10 2013 +0200

description
===========
Jiri reported that 'make .o' stopped working:

  > [jolsa@krava perf]$ make -f Makefile perf.o
  > cc    -c -o perf.o perf.c
  > In file included from builtin.h:4:0,
  >                  from perf.c:9:
  > util/util.h:74:24: fatal error: lk/debugfs.h: No such file or directory
  > compilation terminated.
  > make: *** [perf.o] Error 1

This is due to GNU make having built-in rules for popular targets such
as *.o. Clear them out so that all targets as passed through to Makefile.perf.

Signed-off-by: Rafael Aquini <aquini@redhat.com>