x86/qspinlock: Fix compile error
Message-id: <20190515141555.9281-1-longman@redhat.com>
Patchwork-id: 255931
O-Subject: [RHEL8.1 PATCH 29/29] x86/qspinlock: Fix compile error
Bugzilla: 1709451
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1709451

commit b987ffc18fb3b3b76b059aa9e372dbee26f7c4f2
Author: Peter Zijlstra <peterz@infradead.org>
Date:   Fri Nov 2 14:26:53 2018 +0100

    x86/qspinlock: Fix compile error

    With a compiler that has asm-goto but not asm-cc-output and
    CONFIG_PROFILE_ALL_BRANCHES=y we get a compiler error:

      arch/x86/include/asm/rmwcc.h:23:17: error: jump into statement expression

    Fix this by writing the if() as a boolean multiplication instead.

    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Will Deacon <will.deacon@arm.com>
    Cc: linux-kernel@vger.kernel.org
    Fixes: 7aa54be29765 ("locking/qspinlock, x86: Provide liveness guarantee")
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>