bpf: fix build error with clang
Message-id: <20190604085256.3304-550-yauheni.kaliuta@redhat.com>
Patchwork-id: 262545
O-Subject: [RHEL8.1 PATCH v2 550/627] bpf: fix build error with clang
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 3f6e138d41ddff196f452993528cfe75762ede0f
Author: Stefan Agner <stefan@agner.ch>
Date:   Mon Aug 27 21:30:42 2018 +0200

    bpf: fix build error with clang

    Building the newly introduced BPF_PROG_TYPE_SK_REUSEPORT leads to
    a compile time error when building with clang:
    net/core/filter.o: In function `sk_reuseport_convert_ctx_access':
      ../net/core/filter.c:7284: undefined reference to `__compiletime_assert_7284'

    It seems that clang has issues resolving hweight_long at compile
    time. Since SK_FL_PROTO_MASK is a constant, we can use the interface
    for known constant arguments which works fine with clang.

    Fixes: 2dbb9b9e6df6 ("bpf: Introduce BPF_PROG_TYPE_SK_REUSEPORT")
    Signed-off-by: Stefan Agner <stefan@agner.ch>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>