sched: avoid unused variable warning
Message-id: <97e4d29478777db071a42c4fe538e2b5e9e2c2c5.1490136269.git.jtoppins@redhat.com>
Patchwork-id: 174972
O-Subject: [RHEL7.4 net v4 38/59] mlx5: avoid unused variable warning
Bugzilla: 1393375
RH-Acked-by: Aaron Conole <aconole@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

When CONFIG_NET_CLS_ACT is disabled, we get a new warning in the mlx5
ethernet driver because the tc_for_each_action() loop never references
the iterator:

mellanox/mlx5/core/en_tc.c: In function 'mlx5e_stats_flower':
mellanox/mlx5/core/en_tc.c:431:20: error: unused variable 'a' [-Werror=unused-variable]
  struct tc_action *a;

This changes the dummy tc_for_each_action() macro by adding a
cast to void, letting the compiler know that the variable is
intentionally declared but not used here. I could not come up
with a nicer workaround, but this seems to do the trick.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: aad7e08d39bd ("net/mlx5e: Hardware offloaded flower filter statistics support")
Fixes: 00175aec941e ("net/sched: Macro instead of CONFIG_NET_CLS_ACT ifdef")
Acked-By: Amir Vadai <amir@vadai.me>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e6790fd861100a01838077b9b59bc339a80ee462)
Bugzilla: 1393375
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12825917
Tested: compile tested

Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>