script: Fix build error on Fedora 12
Patchwork-id: 80847
O-Subject: [PATCH RHEL6.6 BZ1101039 220/233] perf scripting perl: Fix build error on Fedora 12
Bugzilla: 1101039
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

[perf] scripting perl: Fix build error on Fedora 12

Message-id: <1401193895-15711-221-git-send-email-jolsa@redhat.com>
Patchwork-id: 80847
O-Subject: [PATCH RHEL6.6 BZ1101039 220/233] perf scripting perl: Fix build error on Fedora 12
Bugzilla: 1101039

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1101039
https://bugzilla.redhat.com/show_bug.cgi?id=1101039

upstream
========
commit 3b16ff89676d9902dc39976aee3cb0314ee37d93
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Oct 14 18:25:12 2013 -0300

description
===========
Cast __u64 to u64 to silence this warning on older distros, such as
Fedora 12:

    CC       /tmp/build/perf/util/scripting-engines/trace-event-perl.o
  cc1: warnings being treated as errors
  util/scripting-engines/trace-event-perl.c: In function 'perl_process_tracepoint':
  util/scripting-engines/trace-event-perl.c:285: error: format '%lu' expects type 'long unsigned int', but argument 2 has type '__u64'
  make[1]: *** [/tmp/build/perf/util/scripting-engines/trace-event-perl.o] Error 1
  make: *** [install] Error 2
  make: Leaving directory `/home/acme/git/linux/tools/perf'
  [acme@fedora12 linux]$

Signed-off-by: Rafael Aquini <aquini@redhat.com>