rtsx: fix possible linking error if built-in
Patchwork-id: 106534
O-Subject: [RHEL6 PATCH 10/12] mmc: rtsx: fix possible linking error if built-in
Bugzilla: 753699
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=753699

commit b677b8850322b210a81b72ffcc7de85a3df395c5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 8 10:27:54 2014 +0200

    mmc: rtsx: fix possible linking error if built-in

    rtsx_usb_sdmmc module uses the LED classdev if available, but the code
    failed to consider the situation that it is built-in and the LED classdev is a
    module, leading to following linking error:

       LD      init/built-in.o
    drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_remove':
    rtsx_usb_sdmmc.c:(.text+0x2a018e): undefined reference to
    `led_classdev_unregister'
    drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_probe':
    rtsx_usb_sdmmc.c:(.text+0x2a197e): undefined reference to
    `led_classdev_register'

    Fix by excluding such condition when defining macro RTSX_USB_USE_LEDS_CLASS.

    Signed-off-by: Roger Tseng <rogerable@realtek.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
    Signed-off-by: Chris Ball <chris@printf.net>

Signed-off-by: Rafael Aquini <aquini@redhat.com>