aacraid: avoid open-coded upper_32_bits
Message-id: <20170303222336.12208.75187.stgit@dhcp187-141.khw.lab.eng.bos.redhat.com>
Patchwork-id: 170164
O-Subject: [RHEL7.4 e-stor PATCH 30/48] scsi: aacraid: avoid open-coded upper_32_bits
Bugzilla: 1384213
RH-Acked-by: Maurizio Lombardi <mlombard@redhat.com>
RH-Acked-by: Tomas Henzl <thenzl@redhat.com>

From: Raghava Aditya Renukunta <RaghavaAditya.Renukunta@microsemi.com>

Backport jejb/scsi.git#misc commit  80a94bb357813901e61f2dc80deae2015c50fdcd
Author: Arnd Bergmann <arnd@arndb.de>
Date: 2017-02-07 13:59:30 +0100

scsi: aacraid: avoid open-coded upper_32_bits

Shifting a dma_addr_t right by 32 bits causes a compile-time warning
when that type is only 32 bit wide:

drivers/scsi/aacraid/src.c: In function 'aac_src_start_adapter':
drivers/scsi/aacraid/src.c:414:29: error: right shift count >= width of type [-Werror=shift-count-overflow]

This changes the driver to use the predefined macros consistently,
including one correct but open-coded upper_32_bits() instance.

Fixes: d1ef4da8487f ("scsi: aacraid: added support for init_struct_8")
Fixes: 423400e64d37 ("scsi: aacraid: Include HBA direct interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
Reviewed-by: Raghava Aditya Renukunta <RaghavaAditya.Renukunta@microsemi.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Acked-by: Scott Benesh <sbenesh@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>