qlcnic: include irq.h for irq definitions
Patchwork-id: 82299
O-Subject: [RHEL 6.6 PATCH 157/182] net: qlcnic: include irq.h for irq definitions
Bugzilla: 1054305
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla
--------

Bug 1054305 (https://bugzilla.redhat.com/show_bug.cgi?id=1054305)

Upstream Status
---------------

net commit id acdd32be6d3ec5f872d9fd930cac54d18d6c74ac

Description
-----------

From: Josh Boyer <jwboyer@fedoraproject.org>

Subject: [PATCH 157/182] net: qlcnic: include irq.h for irq definitions

The qlcnic driver fails to build on ARM with errors like:

In file included from drivers/net/qlcnic/qlcnic.h:36:0,
                 from drivers/net/qlcnic/qlcnic_hw.c:8:
drivers/net/qlcnic/qlcnic_83xx_hw.h:585:1: error: unknown type name 'irqreturn_t'
 irqreturn_t qlcnic_83xx_clear_legacy_intr(struct qlcnic_adapter *);
 ^

Nothing in the driver is explicitly including the irq definitions, so we
add an include of linux/irq.h to pick them up.

Signed-off-by: Josh Boyer <jwboyer@fedoraproject.org>
Signed-off-by: David S. Miller <davem@davemloft.net>