cleanup checkpatch warnings
Patchwork-id: 129698
O-Subject: [RHEL6.8 PATCH BZ1254015 083/118] tpm: cleanup checkpatch warnings
Bugzilla: 1254015
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=10222730
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1254015

	commit 0a4182692ef2b0131ffc9ae523c2dea0cd636201
	Author: Peter Huewe <peterhuewe@gmx.de>
	Date:   Tue Oct 22 00:29:14 2013 +0200

	tpm: cleanup checkpatch warnings

	before we rename the file it might be a good idea to cleanup the long
	persisting checkpatch warnings.
	Since everything is really trivial, splitting the patch up would only
	result in noise.

	For the interested reader - here the checkpatch warnings:
	(regrouped for easer readability)

	ERROR: trailing whitespace
	+ * Specifications at www.trustedcomputinggroup.org^I $
	+ * $
	+^I/* $
	+^I   parameters (RSA 12->bytes: keybit, #primes, expbit)  $

	WARNING: unnecessary whitespace before a quoted newline
	+			"invalid count value %x %zx \n", count, bufsiz);

	ERROR: do not use assignment in if condition
	+	if ((rc = chip->vendor.send(chip, (u8 *) buf, count)) < 0) {

	ERROR: space required after that ',' (ctx:VxV)
	+	len = tpm_transmit(chip,(u8 *) cmd, len);
				       ^

	ERROR: "foo * bar" should be "foo *bar"
	+ssize_t tpm_show_enabled(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_enabled(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_active(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_active(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_owned(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_owned(struct device * dev, struct device_attribute * attr,
	+ssize_t tpm_show_temp_deactivated(struct device * dev,
	+				struct device_attribute * attr, char *buf)

	WARNING: please, no space before tabs
	+ * @chip_num: ^Itpm idx # or ANY$
	+ * @res_buf: ^ITPM_PCR value$
	+ * ^I^Isize of res_buf is 20 bytes (or NULL if you don't care)$
	+ * @chip_num: ^Itpm idx # or AN&$
	+ * @hash: ^Ihash value used to extend pcr value$

	ERROR: code indent should use tabs where possible
	+^I                                     TPM_ORD_CONTINUE_SELFTEST);$

	WARNING: line over 80 characters
	+static bool wait_for_tpm_stat_cond(struct tpm_chip *chip, u8 mask, bool check_cancel,

	ERROR: trailing whitespace
	+ * Called from tpm_<specific>.c probe function only for devices $

	total: 16 errors, 7 warnings, 1554 lines checked

	Signed-off-by: Peter Huewe <peterhuewe@gmx.de>

Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Aristeu Rozanski <aris@redhat.com>