perf stat: Avoid segfaults caused by negated options
Message-id: <ad363155a8afe25e0de9fdf5d38a4a3ca6ae0785.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265041
O-Subject: [RHEL8.1 BZ1715507 115/234] perf stat: Avoid segfaults caused by negated options
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 51433ead1460fb3f46e1c34f68bb22fd2dd0f5d0
Author: Michael Petlan <mpetlan@redhat.com>
Date: Mon Dec 10 11:00:04 2018 -0500

description
===========
Some 'perf stat' options do not make sense to be negated (event,
cgroup), some do not have negated path implemented (metrics). Due to
that, it is better to disable the "no-" prefix for them, since
otherwise, the later opt-parsing segfaults.

Before:

  $ perf stat --no-metrics -- ls
  Segmentation fault (core dumped)

After:

  $ perf stat --no-metrics -- ls
   Error: option `no-metrics' isn't available
   Usage: perf stat [<options>] [<command>]

LPU-Reference: 1485912065.62416880.1544457604340.JavaMail.zimbra@redhat.com
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>