xhci: Fix DIV_ROUND_UP compile error
Patchwork-id: 64285
O-Subject: [RHEL6 PATCH 16/70] xhci: Fix DIV_ROUND_UP compile error.
Bugzilla: 815547
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Kyle McMartin <kmcmarti@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=815547

commit c88db160a30cccb81303212b256680f2e37e35ae
Author: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Date:   Mon May 21 08:44:33 2012 -0700

    xhci: Fix DIV_ROUND_UP compile error.

    Fengguang reports that the xHCI driver isn't linked properly on his
    machine:

    ERROR: "__udivdi3" [drivers/usb/host/xhci-hcd.ko] undefined!
    ERROR: "handle_edge_irq" [drivers/gpio/gpio-pch.ko] undefined!
    ERROR: "irq_to_desc" [drivers/gpio/gpio-pch.ko] undefined!

    The driver compiles fine on my 64-bit box (gcc version 4.6.1).
    Fengguang thinks it's because the xHCI driver was using DIV_ROUND_UP()
    instead of DIV_ROUND_UP_ULL() with arguments that were unsigned long
    long variables.

    Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
    Reported-by: Wu Fengguang <wfg@linux.intel.com>