header: Fix build on old systems
Patchwork-id: 43543
O-Subject: =?UTF-8?q?=5BPATCH=20RHEL6=2E3=20BZ784888=2086/97=5D=20perf=20header=3A=20Fix=20build=20on=20old=20systems?=
Bugzilla: 784888
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 784888
https://bugzilla.redhat.com/show_bug.cgi?id=784888

upstream status
===============
commit a9072bc0b0af991e274b699f17bc50cf201e377b
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Wed Oct 26 12:41:38 2011 -0200

description
===========
For instance, on Fedora 8:

CC /home/acme/git/build/perf/util/header.o
cc1: warnings being treated as errors
util/header.c: In function write_cpudesc:
util/header.c:281: warning: implicit declaration of function getline
util/header.c:281: warning: nested extern declaration of getline
make: *** [/home/acme/git/build/perf/util/header.o] Error 1
make: Leaving directory `/home/acme/git/linux/tools/perf'
[acme@localhost linux]$

This happens due to header ordering, in perf util.h sets _GNU_SOURCE, so
it must come first.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>