tracing: Convert nop macros to static inlines
Patchwork-id: 42322
O-Subject: [PATCH RHEL6.3 BZ734757 1/3] tracing: Convert nop macros to static
	inlines
Bugzilla: 734757
RH-Acked-by: Steven Rostedt <srostedt@redhat.com>

Bugzilla: 734757
https://bugzilla.redhat.com/show_bug.cgi?id=734757

Description:
============
The ftrace.h file contains several functions as macros when the
functions are disabled due to config options. This patch converts
most of them to static inlines.

There are two exceptions:

register_ftrace_function() and unregister_ftrace_function()

This is because their parameter "ops" must not be evaluated since
code using the function is allowed to #ifdef out the creation of
the parameter.

This also fixes an error caused by recent changes:

kernel/trace/trace_irqsoff.c: In function 'start_irqsoff_tracer':
kernel/trace/trace_irqsoff.c:571: error: expected expression before 'do'

Upstream status:
================
tracing: Convert nop macros to static inlines
commit 4dbf6bc239c169b032777616806ecc648058f6b2
Author: Steven Rostedt <srostedt@redhat.com>
Date:   Tue May 4 11:24:01 2010 -0400

Brew:
=====
https://brewweb.devel.redhat.com/taskinfo?taskID=3781153

Tested:
=======
tested with instructions in BZ

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>