python: Fix argument name list of read_on_cpu()
Patchwork-id: 38971
O-Subject: [PATCH RHEL6.2 BZ725522 64/67] perf python: Fix argument name list of
	read_on_cpu()
Bugzilla: 725522
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 725522
https://bugzilla.redhat.com/show_bug.cgi?id=725522

upstream status
---------------
commit b273fa9716aa1564bee88ceee62f9042981cdc81
Author: Frederic Weisbecker <fweisbec@gmail.com>
Date:   Thu Mar 31 18:27:42 2011 +0200

description
-----------
Mandatory arguments need to be present in the argument name list, as
well as optional arguments, otherwise python barfs:

	# ./python/twatch.py
	Traceback (most recent call last):
	  File "./python/twatch.py", line 41, in <module>
	    main()
	  File "./python/twatch.py", line 32, in main
	    event = evlist.read_on_cpu(cpu)
	RuntimeError: more argument specifiers than keyword list entries

Hence, add cpu to the name list.

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>