dm-space-map-metadata: fix sm_bootstrap_get_nr_blocks()
Patchwork-id: 103907
O-Subject: [RHEL6.7 PATCH 03/30] dm space map metadata: fix sm_bootstrap_get_nr_blocks()
Bugzilla: 1187757
RH-Acked-by: Heinz Mauelshagen <heinzm@redhat.com>
RH-Acked-by: Joe Thornber <thornber@redhat.com>

BZ: 1187757

Upstream commit c1c6156fe4d4577444b769d7edd5dd503e57bbc9
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Sat Nov 29 15:50:21 2014 +0300

    dm space map metadata: fix sm_bootstrap_get_nr_blocks()

    This function isn't right and it causes a static checker warning:

    	drivers/md/dm-thin.c:3016 maybe_resize_data_dev()
    	error: potentially using uninitialized 'sb_data_size'.

    It should set "*count" and return zero on success the same as the
    sm_metadata_get_nr_blocks() function does earlier.

    Fixes: 3241b1d3e0aa ('dm: add persistent data library')
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Joe Thornber <ejt@redhat.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>