perf: use XSI-complaint version of strerror_r() instead of GNU-specific
Patchwork-id: 53808
O-Subject: [PATCH RHEL6.4 BZ860404 53/74] perf tools: use XSI-complaint version of strerror_r() instead of GNU-specific
Bugzilla: 860404
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 860404
https://bugzilla.redhat.com/show_bug.cgi?id=860404

upstream status
===============
commit 4cc49d4dc82a39a542a31c1f51ead08a46fd33f1
Author: Kirill A. Shutemov <kirill@shutemov.name>
Date:   Tue Jul 24 00:06:54 2012 +0300

description
===========
Perf uses GNU-specific version of strerror_r(). The GNU-specific strerror_r()
returns a pointer to a string containing the error message.  This may be either
a pointer to a string that the function stores in buf, or a pointer to some
(immutable) static string (in which case buf is unused).

In glibc-2.16 GNU version was marked with attribute warn_unused_result.  It
triggers few warnings in perf:

util/target.c: In function ‘perf_target__strerror’:
util/target.c:114:13: error: ignoring return value of ‘strerror_r’, declared with attribute warn_unused_result [-Werror=unused-result]
ui/browsers/hists.c: In function ‘hist_browser__dump’:
ui/browsers/hists.c:981:13: error: ignoring return value of ‘strerror_r’, declared with attribute warn_unused_result [-Werror=unused-result]

They are bugs.

Let's fix strerror_r() usage.

Signed-off-by: Jarod Wilson <jarod@redhat.com>