selinux: fix parallel compile error
Patchwork-id: 59054
O-Subject: [RHEL6.5 PATCH] selinux: fix parallel compile error
Bugzilla: 962427
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>
RH-Acked-by: Nikola Pajkovsky <npajkovs@redhat.com>

Bugzilla   : https://bugzilla.redhat.com/show_bug.cgi?id=962427
Brew build : http://brewweb.devel.redhat.com/brew/taskinfo?taskID=5761473
Upstream   : ceba72a68d17ee36ef24a71b80dde39ee934ece8
Tested     : brew build

There is a wrong dependency on autogenerated flask.h file in
security/selinux/Makefile. Only avc.o has direct dependency on flask.h, but this
file is also included by other files e.g. selinuxfs.o. So in parallel build the
flask.h may not exist while compiling file incluing it.

We saw this problem during ppc64 dist-git build
+ Arch=powerpc
USING ARCH=powerpc
+ echo USING ARCH=powerpc
+ '[' powerpc == s390 -a debug == kdump ']'
+ make -s ARCH=powerpc nonint_oldconfig
+ make -s ARCH=powerpc V=1 -j16 vmlinux
<stdin>:1523:2: warning: #warning syscall recvmmsg not implemented
+ /usr/lib/rpm/debugedit -b /builddir/build/BUILD -d /usr/src/debug -i
arch/powerpc/kernel/vdso32/vdso32.so.dbg
+ /usr/lib/rpm/debugedit -b /builddir/build/BUILD -d /usr/src/debug -i
arch/powerpc/kernel/vdso64/vdso64.so.dbg
ipc/msg.c: In function 'msgctl_down':
ipc/msg.c:416: warning: 'msqid64' may be used uninitialized in this function
security/selinux/selinuxfs.c:35:19: error: flask.h: No such file or directory
In file included from security/selinux/hooks.c:80:
security/selinux/include/avc.h:20:19: error: flask.h: No such file or directory

    commit ceba72a68d17ee36ef24a71b80dde39ee934ece8
    Author: Paul Gortmaker <paul.gortmaker@windriver.com>
    Date:   Mon Aug 9 17:34:25 2010 -0400

    selinux: fix parallel compile error

    Selinux has an autogenerated file, "flask.h" which is included by
    two other selinux files.  The current makefile has a single dependency
    on the first object file in the selinux-y list, assuming that will get
    flask.h generated before anyone looks for it, but that assumption breaks
    down in a "make -jN" situation and you get:

       selinux/selinuxfs.c:35: fatal error: flask.h: No such file or directory
       compilation terminated.
       remake[9]: *** [security/selinux/selinuxfs.o] Error 1

    Since flask.h is included by security.h which in turn is included
    nearly everywhere, make the dependency apply to all of the selinux-y
    list of objs.

    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Signed-off-by: James Morris <jmorris@namei.org>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>