tools: Fix pmu object compilation error
Patchwork-id: 104132
O-Subject: [PATCH RHEL6.7 BZ1188336 129/280] perf tools: Fix pmu object compilation error
Bugzilla: 1188336
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Holasek <pholasek@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1188336
https://bugzilla.redhat.com/show_bug.cgi?id=1188336

upstream
========
commit 7c2f8164e5415ef48954f6929f4acae5764afdb4
Author: Jiri Olsa <jolsa@redhat.com>
Date: Wed Apr 16 20:49:02 2014 +0200

description
===========
After applying some patches got another shadowing error:

  CC       util/pmu.o
util/pmu.c: In function pmu_alias_terms:
util/pmu.c:287:35: error: declaration of clone shadows a global declaration [-Werror=shadow]

Renaming clone to cloned.

Signed-off-by: Rafael Aquini <aquini@redhat.com>