e1000e: Need to include vmalloc.h
Patchwork-id: 44903
O-Subject: [RHEL6.3 PATCH 31/50] e1000e: Need to include vmalloc.h
Bugzilla: 737713
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Resolves RHBZ 737713

Backport of:

commit c85c21ad1fe18daf26bfe8684df974d88cec50b7
Author: David S. Miller <davem@davemloft.net>
Date:   Thu Jan 26 16:25:55 2012 -0500

    e1000e: Need to include vmalloc.h

    Otherwise (on sparc64):

    drivers/net/ethernet/intel/e1000e/ethtool.c:657:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]

    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>