kaslr: fix build due to missing ALIGN definition
Message-id: <1487170014-11002-42-git-send-email-bhe@redhat.com>
Patchwork-id: 166226
O-Subject: [RHEL7.4 PATCH v2 041/105] x86: kaslr: fix build due to missing ALIGN definition
Bugzilla: 1290840
RH-Acked-by: Rik van Riel <riel@redhat.com>
RH-Acked-by: Xunlei Pang <xpang@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

This is back ported from upstream. There's conflict because
other x86 espfix patch is not back ported yet.

commit 535b3ddc285825c058cef3436a9aa207edffa6cd
Author: Jiri Kosina <jkosina@suse.cz>
Date:   Wed Apr 29 18:09:53 2015 +0200

    x86: kaslr: fix build due to missing ALIGN definition

    Fengguang's bot reported that 4545c898 ("x86: introduce kaslr_offset()") broke
    randconfig build

       In file included from arch/x86/xen/vga.c:5:0:
       arch/x86/include/asm/setup.h: In function 'kaslr_offset':
    >> arch/x86/include/asm/setup.h:77:2: error: implicit declaration of function 'ALIGN' [-Werror=implicit-function-declaration]
         return (unsigned long)&_text - __START_KERNEL;
         ^
    Fix that by making setup.h self-sufficient by explicitly including
    linux/kernel.h, which is needed for ALIGN() (which is what __START_KERNEL
    contains in its expansion).

    Reported-by: fengguang.wu@intel.com
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>