ns: fix get_net_ns_by_fd for !CONFIG_NET_NS
Patchwork-id: 56040
O-Subject: [RHEL6.5 PATCH 10/45] net: fix get_net_ns_by_fd for !CONFIG_NET_NS
Bugzilla: 880142
RH-Acked-by: Daniel Borkmann <dborkman@redhat.com>
RH-Acked-by: Thomas Graf <tgraf@redhat.com>
RH-Acked-by: Jiri Pirko <jpirko@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

(cherry picked from commit 956c920786694f51601a0ef7ee12956fd6aa216e)
	After merging the final tree, today's linux-next build (powerpc
	ppc44x_defconfig) failed like this:

	net/built-in.o: In function `get_net_ns_by_fd':
	(.text+0x11976): undefined reference to `netns_operations'
	net/built-in.o: In function `get_net_ns_by_fd':
	(.text+0x1197a): undefined reference to `netns_operations'

	netns_operations is only available if CONFIG_NET_NS is set ...

	Caused by commit f063052947f7 ("net: Allow setting the network namespace
	by fd").

	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Eric W. Biederman <ebiederm@xmission.com>

Signed-off-by: Cong Wang <amwang@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jarod Wilson <jarod@redhat.com>