fs/overlayfs/super.c needs pagemap.h
Message-id: <1484836995-28214-3-git-send-email-mszeredi@redhat.com>
Patchwork-id: 162827
O-Subject: [RHEL7.4 PATCH 02/38] fs/overlayfs/super.c needs pagemap.h
Bugzilla: 1414769
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1414769
Upstream status: Linus
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12366763
Testing: unionmount-testsuite, xfstests, pjd-fstest, ltp

commit e458bcd16f5bec6f19b60ef957b4f88af95aa78a
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Wed Jan 20 15:01:13 2016 -0800

    fs/overlayfs/super.c needs pagemap.h

    i386 allmodconfig:

      In file included from fs/overlayfs/super.c:10:0:
      fs/overlayfs/super.c: In function 'ovl_fill_super':
      include/linux/fs.h:898:36: error: 'PAGE_CACHE_SIZE' undeclared (first use in this function)
       #define MAX_LFS_FILESIZE (((loff_t)PAGE_CACHE_SIZE << (BITS_PER_LONG-1))-1)
                                          ^
      fs/overlayfs/super.c:939:19: note: in expansion of macro 'MAX_LFS_FILESIZE'
        sb->s_maxbytes = MAX_LFS_FILESIZE;
                         ^
      include/linux/fs.h:898:36: note: each undeclared identifier is reported only once for each function it appears in
       #define MAX_LFS_FILESIZE (((loff_t)PAGE_CACHE_SIZE << (BITS_PER_LONG-1))-1)
                                          ^
      fs/overlayfs/super.c:939:19: note: in expansion of macro 'MAX_LFS_FILESIZE'
        sb->s_maxbytes = MAX_LFS_FILESIZE;
                         ^

    Cc: Miklos Szeredi <miklos@szeredi.hu>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>