annotate: Fix build with NO_NEWT=1
Patchwork-id: 71464
O-Subject: [PATCH RHEL6.6 BZ1034843 167/172] perf annotate: Fix build with NO_NEWT=1
Bugzilla: 1034843
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: 1034843
https://bugzilla.redhat.com/show_bug.cgi?id=1034843

upstream
========
commit 1e825efb571a87d039cb3fe7ca833a25f11c7cb9
Author: Michael Ellerman <michael@ellerman.id.au>
Date: Tue Feb 26 16:02:02 2013 +1100

description
===========
Commit 18c9e5c "Make it to be able to skip unannotatable symbols" broke
the build with NO_NEWT=1:

   CC builtin-annotate.o
builtin-annotate.c: In function 'hists__find_annotations':
builtin-annotate.c:161:4: error: duplicate case value
builtin-annotate.c:154:4: error: previously used here
make: *** [builtin-annotate.o] Error 1

This is because without NEWT support K_LEFT is #defined to -1 in
utils/hist.h

Fix it by shifting the K_LEFT/K_RIGHT #defines out of the likely range
of error values.