probe: Check the orphaned -x option
Patchwork-id: 129343
O-Subject: [PATCH RHEL6 BZ1291071 296/315] perf probe: Check the orphaned -x option
Bugzilla: 1291071
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1291071
https://bugzilla.redhat.com/show_bug.cgi?id=1291071

upstream
========
commit 8cb0aa4c2db395b143cd5165586dc17677960002
Author: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Date: Wed Apr 1 19:25:42 2015 +0900

description
===========
To avoid probing in unintended binary, the orphaned -x option must be
checked and warned.

Without this patch, following command sets up the probe in the kernel.

  -----
  # perf probe -a strcpy -x ./perf
  Added new event:
    probe:strcpy         (on strcpy)

  You can now use it in all perf tools, such as:

          perf record -e probe:strcpy -aR sleep 1
  -----

But in this case, it seems that the user may want to probe in the perf
binary. With this patch, perf-probe correctly handles the orphaned -x.

  -----
  # perf probe -a strcpy -x ./perf
    Error: -x/-m must follow the probe definitions.
  ...

Signed-off-by: Aristeu Rozanski <aris@redhat.com>