ocrdma: Fix compiler warning
Patchwork-id: 83400
O-Subject: [RHEL6.6 Patch V2 356/434] RDMA/ocrdma: Fix compiler warning
Bugzilla: 1029861 1030158 1043993 1051207 1053497 1054375 1059083 1059086 1059087 1059089 1062766 1078538 696003 807078 826288
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Prarit Bhargava <prarit@redhat.com>

drivers/infiniband/hw/ocrdma/ocrdma_verbs.c: In function '_ocrdma_modify_qp':
drivers/infiniband/hw/ocrdma/ocrdma_verbs.c:1299:31: error: 'old_qps' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  status = ocrdma_mbx_modify_qp(dev, qp, attr, attr_mask, old_qps);

ocrdma_mbx_modify_qp() (and subsequent calls) doesn't appear to use old_qps
so it doesn't need to be passed on.  Removing the variable results in the
warning going away.

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Acked-by: Devesh Sharma (Devesh.sharma@emulex.com)
Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit bc1b04ab34a1485339571242cb0fbad823835685)
Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>