perf tools: Add missing object file to the python binding linkage list
Message-id: <1487851678-22505-135-git-send-email-jolsa@redhat.com>
Patchwork-id: 167510
O-Subject: [PATCH RHEL7.4 BZ1425612 134/298] perf tools: Add missing object file to the python binding linkage list
Bugzilla: 1425612
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1425612
https://bugzilla.redhat.com/show_bug.cgi?id=1425612

upstream
========
commit 46cb25b1a0ee74bf4a79cfb3081ae3567b2f7135
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Oct 26 19:02:35 2016 -0200

description
===========
In ac12f6764c50 ("perf tools: Implement branch_type event parameter") we
started using the parse_branch_str() function from one of the files used
in the python binding, which caused this entry in 'perf test' to fail:

  # perf test -v python
  16: Try 'import perf' in python, checking link problems      :
  --- start ---
  test child forked, pid 16667
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: /tmp/build/perf/python/perf.so: undefined symbol:
  parse_branch_str
  test child finished with -1
  ---- end ----
  Try 'import perf' in python, checking link problems: FAILED!
  #

I must've commited some mistake when running 'perf test' to send the
pull request for the perf-core-for-mingo-20161024 tag, to have let this
regression to pass, sigh.

Just add tools/perf/util/parse-branch-options.c and switch from using
ui__warning(), that is not available in the python binding, use
pr_warning() instead, which is good enough for this case.

Now:

  # perf test python
  16: Try 'import perf' in python, checking link problems      : Ok
  #

Fixes: ac12f6764c50 ("perf tools: Implement branch_type event parameter")
Signed-off-by: Rafael Aquini <aquini@redhat.com>