kmem: Fix compiles on RHEL6/OL6
Patchwork-id: 129350
O-Subject: [PATCH RHEL6 BZ1291071 306/315] perf kmem: Fix compiles on RHEL6/OL6
Bugzilla: 1291071
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1291071
https://bugzilla.redhat.com/show_bug.cgi?id=1291071

upstream
========
commit 4ad1f4300e3bddf63109aa63cfb2d37e8585ecc7
Author: David Ahern <david.ahern@oracle.com>
Date: Tue Apr 14 13:49:33 2015 -0400

description
===========
0d68bc92c48 breaks compiles on RHEL6/OL6:
    cc1: warnings being treated as errors
    builtin-kmem.c: In function 'search_page_alloc_stat':
    builtin-kmem.c:322: error: declaration of 'stat' shadows a global declaration
                            node = &parent->rb_left;
    /usr/include/sys/stat.h:455: error: shadowed declaration is here
    builtin-kmem.c: In function 'perf_evsel__process_page_alloc_event':
    builtin-kmem.c:378: error: declaration of 'stat' shadows a global declaration
    /usr/include/sys/stat.h:455: error: shadowed declaration is here
    builtin-kmem.c: In function 'perf_evsel__process_page_free_event':
    builtin-kmem.c:431: error: declaration of 'stat' shadows a global declaration
    /usr/include/sys/stat.h:455: error: shadowed declaration is here

Rename local variable to pstat to avoid the name conflict.

Signed-off-by: Aristeu Rozanski <aris@redhat.com>