tools: lib: traceevent: Use 'const' in variables pointing to const strings
Patchwork-id: 101871
O-Subject: [PATCH RHEL6.7 BZ1172076 093/313] tools lib traceevent: Use 'const' in variables pointing to const strings
Bugzilla: 1172076
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1172076
https://bugzilla.redhat.com/show_bug.cgi?id=1172076

upstream
========
commit 27f94d52394003d444a383eaf8d4824daf32432e
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Nov 9 17:40:47 2012 -0300

description
===========
Fixing the build on fedora 14, 32-bit:

  tools/lib/traceevent/event-parse.c: In function find_cmdline:
  tools/lib/traceevent/event-parse.c:183:3: error: return discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c:186:3: error: return discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c:195:2: error: return discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c: In function process_func_handler:
  tools/lib/traceevent/event-parse.c:2658:9: error: assignment discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c:2660:9: error: assignment discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c: In function print_mac_arg:
  tools/lib/traceevent/event-parse.c:3892:14: error: initialization discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c:3906:7: error: assignment discards qualifiers from pointer target type
  tools/lib/traceevent/event-parse.c: In function pevent_print_event:
  tools/lib/traceevent/event-parse.c:4412:24: error: initialization discards qualifiers from pointer target type

Signed-off-by: Rafael Aquini <aquini@redhat.com>