ethernet: amd: AMD_XGBE should depend on HAS_DMA
Message-id: <1488391487-134368-117-git-send-email-darcari@redhat.com>
Patchwork-id: 169030
O-Subject: [RHEL7.4 PATCH BZ 1339783 116/198] ethernet: amd: AMD_XGBE should depend on HAS_DMA
Bugzilla: 1339783
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1339783

commit 61e77d297dd1fc739828027a2790ee5365de50d2
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Thu Apr 23 19:59:33 2015 +0200

    ethernet: amd: AMD_XGBE should depend on HAS_DMA

    If NO_DMA=y:

        drivers/built-in.o: In function `xgbe_probe':
        xgbe-main.c:(.text+0x2def0a): undefined reference to `dma_set_mask'
        xgbe-main.c:(.text+0x2def20): undefined reference to `dma_supported'
        drivers/built-in.o: In function `xgbe_rx_poll':
        xgbe-drv.c:(.text+0x2e0320): undefined reference to `dma_sync_single_for_cpu'
        xgbe-drv.c:(.text+0x2e035e): undefined reference to `dma_sync_single_for_cpu'
        drivers/built-in.o: In function `xgbe_unmap_rdata':
        xgbe-desc.c:(.text+0x2e5fe4): undefined reference to `dma_unmap_page'
        xgbe-desc.c:(.text+0x2e5ffa): undefined reference to `dma_unmap_single'
        xgbe-desc.c:(.text+0x2e604a): undefined reference to `dma_unmap_page'
        xgbe-desc.c:(.text+0x2e6084): undefined reference to `dma_unmap_page'
        drivers/built-in.o: In function `xgbe_alloc_pages':
        xgbe-desc.c:(.text+0x2e6156): undefined reference to `dma_map_page'
        xgbe-desc.c:(.text+0x2e6164): undefined reference to `dma_mapping_error'
        drivers/built-in.o: In function `xgbe_free_ring':
        xgbe-desc.c:(.text+0x2e63d4): undefined reference to `dma_unmap_page'
        xgbe-desc.c:(.text+0x2e640e): undefined reference to `dma_unmap_page'
        xgbe-desc.c:(.text+0x2e644a): undefined reference to `dma_free_coherent'
        drivers/built-in.o: In function `xgbe_init_ring':
        xgbe-desc.c:(.text+0x2e64d4): undefined reference to `dma_alloc_coherent'
        drivers/built-in.o: In function `xgbe_map_tx_skb':
        xgbe-desc.c:(.text+0x2e6628): undefined reference to `dma_map_single'
        xgbe-desc.c:(.text+0x2e6638): undefined reference to `dma_mapping_error'
        xgbe-desc.c:(.text+0x2e66b2): undefined reference to `dma_map_single'
        xgbe-desc.c:(.text+0x2e66c2): undefined reference to `dma_mapping_error'
        xgbe-desc.c:(.text+0x2e6762): undefined reference to `dma_map_page'
        xgbe-desc.c:(.text+0x2e6772): undefined reference to `dma_mapping_error'

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>