btusb: Mark CW6622 devices to have broken link key commands
Message-id: <1488920286-50873-71-git-send-email-darcari@redhat.com>
Patchwork-id: 172687
O-Subject: [RHEL7.4 PATCH BZ 1415327 115/176] Bluetooth: btusb: Mark CW6622 devices to have broken link key commands
Bugzilla: 1415327
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1415327

commit 418678b01aca849b4f86224e609610ce87a9bdc4
Author: Szymon Janc <szymon.janc@codecoup.pl>
Date:   Thu Sep 1 17:22:37 2016 +0200

    Bluetooth: btusb: Mark CW6622 devices to have broken link key commands

    Conwise CW6622 seems to have a problem with the stored link key
    commands so just mark it as broken.

    < HCI Command: Read Local Supported Features (0x04|0x0003) plen 0
    > HCI Event: Command Complete (0x0e) plen 12
        Read Local Supported Features (0x04|0x0003) ncmd 1
        status 0x00
        Features: 0xff 0x3e 0x85 0x38 0x18 0x18 0x00 0x00
    < HCI Command: Read Local Version Information (0x04|0x0001) plen 0
    > HCI Event: Command Complete (0x0e) plen 12
        Read Local Version Information (0x04|0x0001) ncmd 1
        status 0x00
        HCI Version: 2.0 (0x3) HCI Revision: 0x1f4
        LMP Version: 2.0 (0x3) LMP Subversion: 0x1f4
        Manufacturer: CONWISE Technology Corporation Ltd (66)
    ...
    < HCI Command: Read Local Supported Commands (0x04|0x0002) plen 0
    > HCI Event: Command Complete (0x0e) plen 68
        Read Local Supported Commands (0x04|0x0002) ncmd 1
        status 0x00
        Commands: 7fffef03cedfffffffffff1ff20ff8ff3f
    ...
    < HCI Command: Read Stored Link Key (0x03|0x000d) plen 7
        bdaddr 00:00:00:00:00:00 all 1
    > HCI Event: Command Complete (0x0e) plen 8
        Read Stored Link Key (0x03|0x000d) ncmd 1
        status 0x11 max 0 num 0
        Error: Unsupported Feature or Parameter Value

    Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Cc: David Arcari <darcari@redhat.com>
Cc: Don Zickus <dzickus@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>