Convert some block events to DEFINE_EVENT
Patchwork-id: 24775
O-Subject: [PATCH 21/23] tracing: Convert some block events to DEFINE_EVENT
Bugzilla: 588108
RH-Acked-by: Jason Baron <jbaron@redhat.com>

BZ 588108

commit 77ca1e0294f25fc26053ba14353e703158acef26
Author: Li Zefan <lizf@cn.fujitsu.com>
Date:   Thu Nov 26 15:06:14 2009 +0800

    tracing: Convert some block events to DEFINE_EVENT

    use DECLARE_EVENT_CLASS to remove duplicate code:

       text    data     bss     dec     hex filename
      53570    3284     184   57038    dece block/blk-core.o.old
      43702    3284     144   47130    b81a block/blk-core.o

    12 events are converted:

      block_rq: block_rq_insert, block_rq_issue
      block_rq_with_error: block_rq_{abort, requeue, complete}
      block_bio: block_bio_{backmerge, frontmerge, queue}
      block_get_rq: block_getrq, block_sleeprq
      block_unplug: block_unplug_timer, block_unplug_io

    No change in functionality.

    Signed-off-by: Li Zefan <lizf@cn.fujitsu.com>
    Cc: Jens Axboe <jens.axboe@oracle.com>
    Cc: Steven Rostedt <rostedt@goodmis.org>
    Cc: Frederic Weisbecker <fweisbec@gmail.com>
    LKML-Reference: <4B0E28E6.7060609@cn.fujitsu.com>
    Signed-off-by: Ingo Molnar <mingo@elte.hu>

Signed-off-by: Mike Snitzer <snitzer@redhat.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>