report: Use parse_options_usage() for -s option failure
Patchwork-id: 99664
O-Subject: [PATCH RHEL6.7 BZ1159929 248/320] perf report: Use parse_options_usage() for -s option failure
Bugzilla: 1159929
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Bugzilla: 1159929
https://bugzilla.redhat.com/show_bug.cgi?id=1159929

upstream
========
commit 91aba0a62e24ff7a567e13e1d88deab711df6f0f
Author: Namhyung Kim <namhyung.kim@lge.com>
Date: Fri Nov 1 16:33:13 2013 +0900

description
===========
The -s (--sort) option was processed after normal option parsing so that
it cannot call the parse_options_usage() automatically.  Currently it
calls usage_with_options() which shows entire help messages for event
option.  Fix it by showing just -s options.

  $ perf report -s help
    Error: Unknown --sort key: `help'

   usage: perf report [<options>]

      -s, --sort <key[,key2...]>
                            sort by key(s): pid, comm, dso, symbol, ...

Signed-off-by: Rafael Aquini <aquini@redhat.com>