perf dso: Fix unchecked usage of strncpy()
Message-id: <ecb8237a297688fb655c953fad5b5b65e80e8022.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 264965
O-Subject: [RHEL8.1 BZ1715507 097/234] perf dso: Fix unchecked usage of strncpy()
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit fca5085c15255bbde203b7322c15f07ebb12f63e
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Dec 6 10:49:46 2018 -0300

description
===========
The strncpy() function may leave the destination string buffer
unterminated, better use strlcpy() that we have a __weak fallback
implementation for systems without it.

This fixes this warning on an Alpine Linux Edge system with gcc 8.2:

  In function 'decompress_kmodule',
      inlined from 'dso__decompress_kmodule_fd' at util/dso.c:305:9:
  util/dso.c:298:3: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
     strncpy(pathname, tmpbuf, len);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC       /tmp/build/perf/util/values.o
    CC       /tmp/build/perf/util/debug.o
  cc1: all warnings being treated as errors

Fixes: c9a8a6131fb6 ("perf tools: Move the temp file processing into decompress_kmodule")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>