Export 'boot_cpu_physical_apicid' to modules
Patchwork-id: 84008
O-Subject: [PATCH v3 RHEL6.6 BZ1032255 16/18] x86: Export 'boot_cpu_physical_apicid' to modules
Bugzilla: 1032255
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: "Chen, Gong" <gong.chen@linux.intel.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1032255

Backport of:
Original commit: cc08e04c3fdcaab767b8db27527002b2b4d758cb
Original Author: David Rientjes <rientjes@google.com>
Original Date: Thu, 14 Nov 2013 15:05:32 -0800

	Commit 9ebddac7ea2a "ACPI, x86: Fix extended error log driver to depend on
	CONFIG_X86_LOCAL_APIC" fixed a build error when CONFIG_X86_LOCAL_APIC was not
	selected and !CONFIG_SMP.

	However, since CONFIG_ACPI_EXTLOG is tristate, there is a second build error:

	  ERROR: "boot_cpu_physical_apicid" [drivers/acpi/acpi_extlog.ko] undefined!

	The symbol needs to be exported for it to be available.

Signed-off-by: Chen, Gong <gong.chen@linux.intel.com>
Signed-off-by: Wang, Rui <ruwang@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>