be2iscsi: add Kconfig dependency on NET
Patchwork-id: 30692
O-Subject: [RHEL 6.1 PATCH 27/33] be2iscsi: add Kconfig dependency on NET
Bugzilla: 585751 635746
RH-Acked-by: Rob Evers <revers@redhat.com>

From: Mike Christie <mchristi@redhat.com>

This is for BZ 635746 and 585751.

>From upstream commit:

commit 82c57028e4bf6e2755de91b36223f57406746fa8
Author: Randy Dunlap <randy.dunlap@oracle.com>
Date:   Tue May 4 10:29:52 2010 -0700

    [SCSI] scsi: add Kconfig dependency on NET

    be2iscsi driver should #include linux/if_ether.h since it uses
    sysfs_format_mac().

    It should also depend on NET since it selects SCSI_ISCSI_ATTRS,
    which depends on NET.

    These changes fix a build error when CONFIG_NET is not enabled:
    ERROR: "sysfs_format_mac" [drivers/scsi/be2iscsi/be2iscsi.ko] undefined!

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>