add dummy io_remap_pfn_range() to asm/pgtable.h
Patchwork-id: 79237
O-Subject: [RHEL6 PATCH 2/3 BZ1035242] s390: add dummy io_remap_pfn_range() to asm/pgtable.h
Bugzilla: 1035242
CVE: CVE-2013-2596
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

RHEL6 did not have the dummy io_remao_pfn_range definition in the kernel
so it needed to be added this is essentially a backport

commit 4f2e29031e6c67802e7370292dd050fd62f337ee
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Wed Apr 17 08:46:19 2013 -0700

s390: move dummy io_remap_pfn_range() to asm/pgtable.h

Commit b4cbb197c7e7 ("vm: add vm_iomap_memory() helper function") added
a helper function wrapper around io_remap_pfn_range(), and every other
architecture defined it in <asm/pgtable.h>.

The s390 choice of <asm/io.h> may make sense, but is not very convenient
for this case, and gratuitous differences like that cause unexpected errors like this:

	mm/memory.c: In function 'vm_iomap_memory': mm/memory.c:2439:2: error:
	implicit declaration of function 'io_remap_pfn_range' [-Werror=implicit-function-declaration]

Glory be the kbuild test robot who noticed this, bisected it,
and reported it to the guilty parties (ie me).

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1035242
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=7393163
Beaker: https://beaker.engineering.redhat.com/jobs/642358
        https://beaker.engineering.redhat.com/jobs/642966

Signed-off-by: Rafael Aquini <aquini@redhat.com>