perf: Fix include header files in util/parse-events.h
Patchwork-id: 49941
O-Subject: [PATCH RHEL6.4 BZ846702 103/198] perf tools: Fix include header files in util/parse-events.h
Bugzilla: 846702
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 846702
https://bugzilla.redhat.com/show_bug.cgi?id=846702

upstream status
===============
commit c651214e90e5c150015f7524a6bfc298ad61435f
Author: Robert Richter <robert.richter@amd.com>
Date:   Thu Apr 5 18:26:25 2012 +0200

description
===========
Include header fixes for

... bool:

 util/parse-events.h:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘have_tracepoints’

... and types.h:

 util/parse-events.h:28: error: expected ‘)’ before ‘config’
 util/parse-events.h:34: error: expected declaration specifiers or ‘...’ before ‘u64’
 util/parse-events.h:45: error: expected ‘)’ before ‘type’

This happens if now other include files are included before
util/parse-events.h.