test: Check for linking problems in the python binding
Patchwork-id: 71350
O-Subject: [PATCH RHEL6.6 BZ1034843 046/172] perf test: Check for linking problems in the python binding
Bugzilla: 1034843
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: 1034843
https://bugzilla.redhat.com/show_bug.cgi?id=1034843

upstream
========
commit 54359d3340241b4cf53e42ecd5c429d7ba6fbef3
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Dec 14 13:06:13 2012 -0300

description
===========
It just will add the O= builddir to PYTHONPATH and try to 'use perf',
which will, in verbose mode show the python backtrace with the missing
symbols, such as in the problem fixed in the patch after this one:

  # perf test -v 15
  15: Try 'use perf' in python, checking link problems       :
  --- start ---
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: /home/acme/git/build/perf//python/perf.so: undefined symbol: test_attr__enabled
  ---- end ----
  Try 'use perf' in python, checking link problems: FAILED!
  #

Loooong overdue, done.