nct6775: Fix size of data->temp array
Patchwork-id: 128295
O-Subject: [RHEL6.8 PATCH 29/52] hwmon: (nct6775) Fix size of data->temp array
Bugzilla: 1260117
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Resolves BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1260117

Upstream status:
This is a backport of the following from the linux tree...

commit f58876ac8c73f91c28f7825dee37ad64092eccf7
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Thu Jul 18 18:01:11 2013 +0300

    hwmon: (nct6775) Fix size of data->temp array

    Smatch complains that we have a array overflow:

    	drivers/hwmon/nct6775.c:1456 nct6775_update_device()
    		error: buffer overflow 'data->temp' 4 <= 4

    Guenter Roeck says that the array should have been made larger in
    7cbbd6aee6 (Add support for critical low/high temperature limits on
    NCT6106).  This patch does that.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>

Signed-off-by: Aristeu Rozanski <aris@redhat.com>