net/hyperv: avoid uninitialized variable
Message-id: <1478705370-7589-6-git-send-email-vkuznets@redhat.com>
Patchwork-id: 160307
O-Subject: [RHEL7.4 KERNEL PATCH 5/5] net/hyperv: avoid uninitialized variable
Bugzilla: 1392220
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

Upstream commit 52ccd6318481a467d8ad54ea40f60c61e957d58f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 18 00:16:09 2016 +0200

    net/hyperv: avoid uninitialized variable

    The hdr_offset variable is only if we deal with a TCP or UDP packet,
    but as the check surrounding its usage tests for skb_is_gso()
    instead, the compiler has no idea if the variable is initialized
    or not at that point:

    drivers/net/hyperv/netvsc_drv.c: In function 'netvsc_start_xmit':
    drivers/net/hyperv/netvsc_drv.c:494:42: error: 'hdr_offset' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    This adds an additional check for the transport type, which
    tells the compiler that this path cannot happen. Since the
    get_net_transport_info() function should always be inlined
    here, I don't expect this to result in additional runtime
    checks.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

RHEL-only: GCC4.8 in RHEL is not smart enough to figure out that hdr_offset
 may only be uninitialized when net_trans_info == TRANSPORT_INFO_NOT_IP and
 keeps complaining, silence it by doing hdr_offset = 0;

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>