tools: Pass the target in descend
Patchwork-id: 79082
O-Subject: [PATCH RHEL6.6 BZ1070896 06/89] tools: Pass the target in descend
Bugzilla: 1070896
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Bugzilla: 1070896
https://bugzilla.redhat.com/show_bug.cgi?id=1070896

upstream
========
commit 2b73f65d114b44b9bc9bd7d229f603e4cd5c1a88
Author: David Howells <dhowells@redhat.com>
Date: Tue Nov 13 14:14:38 2012 -0300

description
===========
 Fixing:

  [acme@sandy linux]$ cd tools
  [acme@sandy tools]$ make clean
      DESCEND power/cpupower
    CC       lib/cpufreq.o
    CC       lib/sysfs.o
    LD       libcpupower.so.0.0.0
    CC       utils/helpers/amd.o
  utils/helpers/amd.c:7:21: error: pci/pci.h: No such file or directory
  In file included from utils/helpers/amd.c:9:
  ./utils/helpers/helpers.h:137: warning: 'struct pci_access' declared inside parameter list
  ./utils/helpers/helpers.h:137: warning: its scope is only this definition or declaration, which is probably not what you want
  ./utils/helpers/helpers.h:139: warning: 'struct pci_access' declared inside parameter list
  utils/helpers/amd.c: In function 'amd_pci_get_num_boost_states':
  utils/helpers/amd.c:120: warning: passing argument 1 of 'pci_slot_func_init' from incompatible pointer type
  ./utils/helpers/helpers.h:138: note: expected 'struct pci_access **' but argument is of type 'struct pci_access **'
  utils/helpers/amd.c:125: warning: implicit declaration of function 'pci_read_byte'
  utils/helpers/amd.c:132: warning: implicit declaration of function 'pci_cleanup'
  make[1]: *** [utils/helpers/amd.o] Error 1
  make: *** [cpupower_clean] Error 2
  [acme@sandy tools]$

Signed-off-by: Rafael Aquini <aquini@redhat.com>