perf: Fix build for another rbtree.c change
Patchwork-id: 57959
O-Subject: [PATCH RHEL6.5 BZ927866 120/264] perf tools: Fix build for another rbtree.c change
Bugzilla: 927866
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

From: Adrian Hunter <adrian.hunter@intel.com>

Bugzilla: 927866
https://bugzilla.redhat.com/show_bug.cgi?id=927866

upstream status
===============
commit b155a09015135cf59ada8d48109ccbd9891c1b42
Author: Adrian Hunter <adrian.hunter@intel.com>
Date:   Fri Aug 31 10:49:27 2012 +0300

description
===========
Fixes:

../../lib/rbtree.c: In function 'rb_insert_color':
../../lib/rbtree.c:95:9: error: 'true' undeclared (first use in this function)
../../lib/rbtree.c:95:9: note: each undeclared identifier is reported only once for each function it appears in
../../lib/rbtree.c: In function '__rb_erase_color':
../../lib/rbtree.c:216:9: error: 'true' undeclared (first use in this function)
../../lib/rbtree.c: In function 'rb_erase':
../../lib/rbtree.c:368:2: error: unknown type name 'bool'
make: *** [util/rbtree.o] Error 1