x86: remove 64-bit division
Patchwork-id: 40146
O-Subject: [RHEL6.3 kernel PATCH 15/56] x86/PCI: remove 64-bit division
Bugzilla: 567487
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=567487
Brew build: https://brewweb.devel.redhat.com/taskinfo?taskID=3556098
Backport of upstream commit: ea7f1b6ee9dc96c5827b06ba21d7769d553efb7d

commit ea7f1b6ee9dc96c5827b06ba21d7769d553efb7d
Author: Bjorn Helgaas <bjorn.helgaas@hp.com>
Date:   Thu Nov 5 11:17:11 2009 -0600

x86/PCI: remove 64-bit division

The roundup() caused a build error (undefined reference to `__udivdi3').
We're aligning to power-of-two boundaries, so it's simpler to just use
ALIGN() anyway, which avoids the division.

Signed-off-by: Bjorn Helgaas <bjorn.helgaas@hp.com>
Acked-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Jesse Barnes <jbarnes@virtuousgeek.org>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>