aesni-intel: fix aesni build on i386
Patchwork-id: 59778
O-Subject: [RHEL6 PATCH 15/51] crypto: aesni-intel - fix aesni build on i386
Bugzilla: 786968 786972 969522
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=786968
https://bugzilla.redhat.com/show_bug.cgi?id=786972
https://bugzilla.redhat.com/show_bug.cgi?id=969522

commit 9bed4aca296fdf9c1b85a8f093e92018dc9864f3
Author: Randy Dunlap <randy.dunlap@oracle.com>
Date:   Wed May 18 09:03:34 2011 +1000

    crypto: aesni-intel - fix aesni build on i386

    Fix build error on i386 by moving function prototypes:

    arch/x86/crypto/aesni-intel_glue.c: In function 'aesni_init':
    arch/x86/crypto/aesni-intel_glue.c:1263: error: implicit declaration of function 'crypto_fpu_init'
    arch/x86/crypto/aesni-intel_glue.c: In function 'aesni_exit':
    arch/x86/crypto/aesni-intel_glue.c:1373: error: implicit declaration of function 'crypto_fpu_exit'

    Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Jarod Wilson <jarod@redhat.com>